
import base64
DATA_B64 = "ZGVmIGdldF9jZW50ZXIoY29vcmRzKToKICAgICIiIgogICAgVHLhuqMgduG7gSB0w6JtIGThu7FhIHRyw6puIHPhu5EgbMaw4bujbmcgxJFp4buDbToKICAgICAgLSAxIMSRaeG7g206IHRy4bqjIHbhu4EgY2jDrW5oIMSRaeG7g20gxJHDswogICAgICAtIDIgxJFp4buDbTogdHLhuqMgduG7gSB0cnVuZyDEkWnhu4NtCiAgICAgIC0gPj0zIMSRaeG7g206IHRy4bqjIHbhu4EgY2VudHJvaWQgcG9seWdvbiAodOG7sSBraMOpcCBrw61uKQogICAgIiIiCiAgICBuID0gbGVuKGNvb3JkcykKCiAgICBpZiBuID09IDA6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigiRGFuaCBzw6FjaCBy4buXbmciKQoKICAgICMgMSBQT0lOVCDihpIgcmV0dXJuIGNow61uaCBuw7MKICAgIGlmIG4gPT0gMToKICAgICAgICB4LCB5ID0gY29vcmRzWzBdCiAgICAgICAgcmV0dXJuIHgsIHkKCiAgICAjIDIgUE9JTlRTIOKGkiByZXR1cm4gdHJ1bmcgxJFp4buDbQogICAgaWYgbiA9PSAyOgogICAgICAgICh4MSwgeTEpLCAoeDIsIHkyKSA9IGNvb3JkcwogICAgICAgIHJldHVybiAoeDEgKyB4MikgLyAyLCAoeTEgKyB5MikgLyAyCgogICAgIyA+PTMgUE9JTlRTIOKGkiByZXR1cm4gY2VudHJvaWQgcG9seWdvbgogICAgIyBSZW1vdmUgZHVwbGljYXRlIGxhc3QgcG9pbnQgKG7hur91IMSRw6Mga8OtbikKICAgIGlmIGNvb3Jkc1swXSA9PSBjb29yZHNbLTFdOgogICAgICAgIGNvb3JkcyA9IGNvb3Jkc1s6LTFdCgogICAgIyBU4buxIGtow6lwIGvDrW4gcG9seWdvbgogICAgcmluZyA9IGNvb3JkcyArIFtjb29yZHNbMF1dCgogICAgcG9seSA9IFBvbHlnb24ocmluZykKCiAgICAjIE7hur91IHBvbHlnb24gdGjhurNuZyBow6BuZyAvIGtow7RuZyBo4bujcCBs4buHIOKGkiBmYWxsYmFjazogdHJ1bmcgxJFp4buDbSBib3VuZGluZyBib3gKICAgIGlmIHBvbHkuYXJlYSA9PSAwIG9yIG5vdCBwb2x5LmlzX3ZhbGlkOgogICAgICAgIG1pbngsIG1pbnksIG1heHgsIG1heHkgPSBwb2x5LmJvdW5kcwogICAgICAgIHJldHVybiAobWlueCArIG1heHgpIC8gMiwgKG1pbnkgKyBtYXh5KSAvIDIKCiAgICBjID0gcG9seS5jZW50cm9pZAogICAgcmV0dXJuIGMueCwgYy55"
def save(filename="code_moi_ve.py"):
    try:
        decoded = base64.b64decode(DATA_B64).decode("utf-8")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(decoded)
        print(f"OK: Da luu code vao {filename}")
    except Exception as e:
        print(f"LOI: {e}")
