
JOKES = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kats.",
    "There are 10 types of people in the world: those who understand binary, and those who don't.",
    "A SQL query starts walking into a bar. He walks up to two tables and asks, 'Can I join you?'",
    "Why did the Python programmer get rejected? Because he wasn't their type.",
    "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
    "What is a programmer's favorite hangout place? Foo Bar.",
    "Why do Java programmers have to wear glasses? Because they don't C#.",
    "What do you call a programmer from Finland? Nerdic.",
    "What did the router say to the doctor? 'It hurts when IP.'",
    "Why did the developer go broke? Because he used up his cache.",
    "First, solve the problem. Then, write the code. - John Johnson",
    "Real programmers count from 0.",
    "Why did the functions stop calling each other? Because they had constant arguments.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why don't bachelors like Git? They are afraid to commit.",
    "What do you call a computer that sings? A Dell.",
    "Hardware: The part of a computer that you can kick.",
    "Software: The part that you can only curse at.",
    "Why did the web developer leave the restaurant? Because of the table layout.",
    "What is the most used language in programming? Profanity.",
    "Why do programmers hate nature? It has too many bugs.",
    "What's a programmer's favorite game? Hide and Seek (but they always hide in the comments).",
    "Why was the computer cold? It left its Windows open.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "0 is false and 1 is true, right? 1.",
    "A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesn't.",
    "Programming is 10% coding and 90% googling the error.",
    "If you want to understand recursion, first you must understand recursion.",
    "Why do Python programmers prefer snake_case? Because they hiss at camelCase.",
    "Product Manager: 'Can we change this?' Developer: 'It depends.'",
    "What’s the object-oriented way to become wealthy? Inheritance.",
    "Why did the edge server go bankrupt? Because it lost its cache flow.",
    "Knock, knock. Who’s there? Recursion. Recursion who? Knock, knock.",
    "Why did the private classes break up? Because they couldn't see each other.",
    "What did the Java code say to the C code? You've got no class.",
    "Why do C programmers look so old? Because they don't have garbage collection.",
    "What is a backend developer's favorite drink? Java.",
    "Why did the developer stay at home? Because he works in a domain-isolated environment.",
    "How does a computer get drunk? It takes screenshots.",
    "What did the server say to the client? 'Here's that data you ordered.'",
    "Why was the cell phone wearing glasses? It lost its contacts.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why did the PowerPoint presentation cross the road? To get to the other slide.",
    "What do you call a group of 8 Hobbits? A Hobby-byte.",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the scarecrow become a successful software engineer? He was outstanding in his field.",
    "What do you call a fast zombie? A zoom-bie.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a fake noodle? An impasta.",
    "Why did the cookie go to the hospital? Because he felt crummy.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a pile of cats? A meowtain.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the picture go to jail? Because it was framed.",
    "What do you call a belt made of watches? A waist of time.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why did the math teacher open a bakery? He wanted to make some pi.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "Why did the music teacher go to jail? Because she got in treble.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "What do you call a pig that does karate? A pork chop.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call a dog magician? A labracadabrador.",
    "Why did the cow cross the road? To get to the udder side.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "Why did the melon jump into the lake? It wanted to be a water-melon.",
    "What do you call a horse who lives next door? A neigh-bor.",
    "Why did the chicken go to the seance? To get to the other side.",
    "What do you call a fly without wings? A walk.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the frog take the bus to work? His car got toad.",
    "What do you call a dinosaur that is sleeping? A dino-snore.",
    "Why did the orange stop rolling down the hill? It ran out of juice.",
    "What do you call a bee that can't make up its mind? A maybe.",
    "Why did the computer go to the dentist? It had a blue tooth.",
    "What do you call a lazy kangaroo? Pouch potato.",
    "Why did the robot go on a diet? It had too many bytes.",
    "What do you call a snake who builds things? A boa constructor.",
    "Why did the cookie cry? Because his mother was a wafer so long.",
    "What do you call a funny mountain? Hill-arious.",
    "Why did the gym close down? It just didn't work out.",
    "What do you call a deer with no eyes? No idea.",
    "Why did the tomato go out with a prune? Because he couldn't find a date.",
    "What do you call a sleeping wolf? An unaware-wolf.",
    "Why did the cookie go to the doctor? He was feeling crummy.",
    "What do you call a bear with no ears? B.",
    "Why did the bicycle fall over? It was two tired.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "What do you call a pig that knows karate? A pork chop.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a fish without an eye? Fsh."
]

FORTUNES = [
    "Talk is cheap. Show me the code. - Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Abelson & Sussman",
    "Truth can only be found in one place: the code. - Robert C. Martin",
    "The only way to go fast, is to go well. - Uncle Bob",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "Fix the cause, not the symptom. - Steve McConnell",
    "Optimism is an occupational hazard of programming: feedback is the treatment. - Kent Beck",
    "When to use iterative development? You should use iterative development only on projects that you want to succeed. - Martin Fowler",
    "Before software can be reusable it first has to be usable. - Ralph Johnson",
    "Make it work, make it right, make it fast. - Kent Beck",
    "Deleted code is debugged code. - Jeff Sickel",
    "It’s not a bug – it’s an undocumented feature. - Anonymous",
    "Software undergoes beta testing shortly before it’s released. Beta is Latin for 'still doesn’t work'. - Anonymous",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
    "Programming is the art of telling another human being what one wants the computer to do. - Donald Knuth",
    "The function of good software is to make the complex appear to be simple. - Grady Booch",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "First, solve the problem. Then, write the code. - John Johnson",
    "Experience is the name everyone gives to their mistakes. - Oscar Wilde",
    "In order to understand recursion, one must first understand recursion. - Anonymous",
    "The best error message is the one that never shows up. - Thomas Fuchs",
    "The most damaging phrase in the language is 'It's always been done this way.' - Grace Hopper",
    "One man's crappy software is another man's full-time job. - Jessica Gaston",
    "Don't comment your code. Rewrite it. - Brian W. Kernighan",
    "Without requirements or design, programming is the art of adding bugs to an empty text file. - Louis Srygley",
    "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
    "Software definitions are circular. - Unknown",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V Berard",
    "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing. - Dick Brandon",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - John Woods",
    "There are two ways to write error-free programs; only the third one works. - Alan J. Perlis",
    "It’s hard enough to find an error in your code when you’re looking for it; it’s even harder when you’ve assumed your code is error-free. - Steve McConnell",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "Nine people can't make a baby in a month. - Fred Brooks",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. - Patrick McKenzie",
    "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
    "Your most unhappy customers are your greatest source of learning. - Bill Gates",
    "The overarching goal of all software design is to reduce complexity. - Steve McConnell",
    "Good design adds value faster than it adds cost. - Thomas C. Gale",
    "Controlling complexity is the essence of computer programming. - Brian Kernighan",
    "Beauty is more important in computing than anywhere else in technology because software is so complicated. Beauty is the ultimate defense against complexity. - David Gelernter",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "It is better to wait for a productive programmer to become available than it is to wait for the first available programmer to become productive. - Steve McConnell",
    "Productivity is the bottleneck. - Unknown",
    "Don't worry if it doesn't work right. If everything did, you'd be out of a job. - Mosher's Law of Software Engineering",
    "The value of a prototype is in the education it gives you, not in the code itself. - Alan Cooper",
    "The craft of programming begins with empathy, not formatting. - Unknown",
    "Code never lies, comments sometimes do. - Ron Jeffries",
    "Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis. - Alan Perlis",
    "Look at the code. - Unknown",
    "The proper use of comments is to compensate for our failure to express ourself in code. - Robert C. Martin",
    "Clean code always looks like it was written by someone who cares. - Robert C. Martin",
    "Of all the things I've lost, I miss my mind the most. - Ozzy Osbourne (Relevant to debugging)",
    "Premature optimization is the root of all evil. - Donald Knuth",
    "Computer science is no more about computers than astronomy is about telescopes. - Edsger Dijkstra",
    "Computers are useless. They can only give you answers. - Pablo Picasso",
    "Simplicity is prerequisite for reliability. - Edsger Dijkstra",
    "Testing lists the presence of bugs, but never their absence. - Edsger Dijkstra",
    "When you don't create things, you become defined by your tastes rather than your ability. - Why The Lucky Stiff",
    "You can't have great software without a great team, and most software teams behave like dysfunctional families. - Jim McCarthy",
    "Programming is not about typing, it's about thinking. - Rich Hickey",
    "Confusion is part of programming. - Felienne Hermans",
    "The details are not the details. They make the design. - Charles Eames",
    "Design is not just what it looks like and feels like. Design is how it works. - Steve Jobs",
    "Styles come and go. Good design is a language, not a style. - Massimo Vignelli",
    "Good design is obvious. Great design is transparent. - Joe Sparano",
    "Digital design is like painting, except the paint never dries. - Neville Brody",
    "Technology over technique produces emotionless design. - Daniel Mall",
    "The user's going to pick the best tool for the job. - Unknown",
    "Make it simple, but significant. - Don Draper",
    "Design is intelligence made visible. - Alina Wheeler",
    "Everything is designed. Few things are designed well. - Brian Reed",
    "Creativity is allowing yourself to make mistakes. Design is knowing which ones to keep. - Scott Adams",
    "Design is the silent ambassador of your brand. - Paul Rand",
    "Accessible design is good design. - Steve Ballmer",
    "A user interface is like a joke. If you have to explain it, it's not that good. - Martin LeBlanc",
    "Good design is good business. - Thomas Watson Jr.",
    "Brevity is the soul of wit. - Shakespeare",
    "Do what you can, with what you have, where you are. - Teddy Roosevelt",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Stay hungry, stay foolish. - Steve Jobs",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
    "Knowledge is power. - Francis Bacon",
    "Time is money. - Benjamin Franklin",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "If you tell the truth, you don't have to remember anything. - Mark Twain",
    "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "We accept the love we think we deserve. - Stephen Chbosky",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "It is never too late to be what you might have been. - George Eliot"
]
