# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Empire**, the allocation and nomination platform of BritNed_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/britned/empire-platform-api) 

    The version of the OpenAPI document: 7.1.0
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AuctionTimescaleDayAheadOrIntraDay(str, Enum):
    """
    AuctionTimescaleDayAheadOrIntraDay
    """

    """
    allowed enum values
    """
    DAY_AHEAD = 'DAY_AHEAD'
    INTRA_DAY = 'INTRA_DAY'

    @classmethod
    def from_json(cls, json_str: str) -> AuctionTimescaleDayAheadOrIntraDay:
        """Create an instance of AuctionTimescaleDayAheadOrIntraDay from a JSON string"""
        return AuctionTimescaleDayAheadOrIntraDay(json.loads(json_str))


