

def get_mip_dim(mip: int, dim: int, add_compressed_format_padding: bool = False) -> int: ...

def get_mip_dims(mip: int, width: int, height: int, depth: int = 1, add_compressed_format_padding: bool = False) -> tuple[int, int, int]: ...

def get_maximum_mip_count(width: int, height: int, depth: int = 1) -> int: ...
