from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

class FastURLComponents:
    scheme: str
    netloc: str
    path: str
    query: str
    fragment: str
    host: str
    port: int

    def __init__(self, url: str) -> None: ...
    def get_query_dict(self) -> Dict[str, List[str]]: ...
    def reconstruct(self) -> str: ...

class URLCanonicalizer:
    def __init__(self, max_cache_size: int = ...) -> None: ...
    def canonicalize(self, url: str) -> str: ...
    def clear_cache(self) -> None: ...
    def set_tracking_params(self, params: Set[str]) -> None: ...
    def set_canonical_params(self, params: Set[str]) -> None: ...

def fast_canonicalize_domain(domain: str) -> str: ...
def fast_clean_path(path: str) -> str: ...
def fast_filter_query_params(
    query: str,
    keep_params: Optional[Set[str]] = ...,
    remove_params: Optional[Set[str]] = ...,
) -> str: ...
def fast_normalize_url(
    url: str,
    remove_fragment: bool = ...,
    remove_tracking: bool = ...,
) -> str: ...
def split_url_parts(url: str) -> Tuple[str, str, str, str, str]: ...
def join_url_parts(
    scheme: str,
    host: str,
    path: str = ...,
    query: str = ...,
    fragment: str = ...,
) -> str: ...
def is_tracking_param(param_name: str) -> bool: ...
