from cloud_harvester.infrastructure.providers.aws.compute import collect_ec2
from cloud_harvester.infrastructure.providers.aws.containers import (
    collect_ecs_clusters,
    collect_eks_clusters,
)
from cloud_harvester.infrastructure.providers.aws.databases import (
    collect_dynamodb_tables,
    collect_elasticache_clusters,
    collect_rds,
    collect_redshift_clusters,
)
from cloud_harvester.infrastructure.providers.aws.networking import (
    collect_api_gateway_http_apis,
    collect_api_gateway_rest_apis,
    collect_classic_elb_load_balancers,
    collect_cloudfront_distributions,
    collect_elbv2_load_balancers,
    collect_vpc,
    collect_route53_hosted_zones,
)
from cloud_harvester.infrastructure.providers.aws.observability import (
    collect_backup_vaults,
    collect_cloudtrail_trails,
    collect_cloudwatch_alarms,
    collect_config_recorders,
    collect_ssm_managed_instances,
)
from cloud_harvester.infrastructure.providers.aws.security import (
    collect_acm_certificates,
    collect_guardduty_detectors,
    collect_iam_roles,
    collect_kms_keys,
    collect_security_hub_hubs,
    collect_secrets_manager_secrets,
    collect_shield_protections,
    collect_waf_acls,
)
from cloud_harvester.infrastructure.providers.aws.serverless import (
    collect_lambda_functions,
)
from cloud_harvester.infrastructure.providers.aws.storage import (
    collect_ebs_volumes,
    collect_efs_file_systems,
    collect_s3_buckets,
)

AWS_COLLECTORS = (
    collect_ec2,
    collect_lambda_functions,
    collect_ecs_clusters,
    collect_eks_clusters,
    collect_vpc,
    collect_elbv2_load_balancers,
    collect_classic_elb_load_balancers,
    collect_api_gateway_rest_apis,
    collect_api_gateway_http_apis,
    collect_route53_hosted_zones,
    collect_cloudfront_distributions,
    collect_s3_buckets,
    collect_ebs_volumes,
    collect_efs_file_systems,
    collect_dynamodb_tables,
    collect_elasticache_clusters,
    collect_rds,
    collect_redshift_clusters,
    collect_iam_roles,
    collect_kms_keys,
    collect_secrets_manager_secrets,
    collect_acm_certificates,
    collect_waf_acls,
    collect_shield_protections,
    collect_guardduty_detectors,
    collect_security_hub_hubs,
    collect_cloudwatch_alarms,
    collect_cloudtrail_trails,
    collect_config_recorders,
    collect_ssm_managed_instances,
    collect_backup_vaults,
)

__all__ = [
    "AWS_COLLECTORS",
    "collect_ec2",
    "collect_lambda_functions",
    "collect_ecs_clusters",
    "collect_eks_clusters",
    "collect_vpc",
    "collect_elbv2_load_balancers",
    "collect_classic_elb_load_balancers",
    "collect_api_gateway_rest_apis",
    "collect_api_gateway_http_apis",
    "collect_route53_hosted_zones",
    "collect_cloudfront_distributions",
    "collect_s3_buckets",
    "collect_ebs_volumes",
    "collect_efs_file_systems",
    "collect_dynamodb_tables",
    "collect_elasticache_clusters",
    "collect_rds",
    "collect_redshift_clusters",
    "collect_iam_roles",
    "collect_kms_keys",
    "collect_secrets_manager_secrets",
    "collect_acm_certificates",
    "collect_waf_acls",
    "collect_shield_protections",
    "collect_guardduty_detectors",
    "collect_security_hub_hubs",
    "collect_cloudwatch_alarms",
    "collect_cloudtrail_trails",
    "collect_config_recorders",
    "collect_ssm_managed_instances",
    "collect_backup_vaults",
]
