LANGUAGES = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic (العربية)',
    'hy': 'armenian (հայերեն)',
    'az': 'azerbaijani (azərbaycan)',
    'eu': 'basque (euskara)',
    'be': 'belarusian (беларуская)',
    'bn': 'bengali (বাংলা)',
    'bs': 'bosnian (bosanski)',
    'bg': 'bulgarian (български)',
    'ca': 'catalan (català)',
    'ceb': 'cebuano (cebuano)',
    'ny': 'chichewa (chichewa)',
    'zh-cn': 'chinese (simplified) (中文)',
    'zh-tw': 'chinese (traditional) (中文)',
    'co': 'corsican (corsu)',
    'hr': 'croatian (hrvatski)',
    'cs': 'czech (čeština)',
    'da': 'danish (dansk)',
    'nl': 'dutch (nederlands)',
    'en': 'english (english)',
    'eo': 'esperanto (esperanto)',
    'et': 'estonian (eesti)',
    'tl': 'filipino (filipino)',
    'fi': 'finnish (suomi)',
    'fr': 'french (français)',
    'fy': 'frisian (frysk)',
    'gl': 'galician (galego)',
    'ka': 'georgian (ქართული)',
    'de': 'german (deutsch)',
    'el': 'greek (ελληνικά)',
    'gu': 'gujarati (ગુજરાતી)',
    'ht': 'haitian creole (kreyòl ayisyen)',
    'ha': 'hausa (hausa)',
    'haw': 'hawaiian (ʻōlelo hawaiʻi)',
    'he': 'hebrew (עברית)',
    'hi': 'hindi (हिन्दी)',
    'hmn': 'hmong (hmong)',
    'hu': 'hungarian (magyar)',
    'is': 'icelandic (íslenska)',
    'ig': 'igbo (igbo)',
    'id': 'indonesian (bahasa indonesia)',
    'ga': 'irish (gaeilge)',
    'it': 'italian (italiano)',
    'ja': 'japanese (日本語)',
    'jw': 'javanese (basa jawa)',
    'kn': 'kannada (ಕನ್ನಡ)',
    'kk': 'kazakh (қазақ тілі)',
    'km': 'khmer (ខ្មែរ)',
    'ko': 'korean (한국어)',
    'ku': 'kurdish (kurdî)',
    'ky': 'kyrgyz (кыргызча)',
    'lo': 'lao (ລາວ)',
    'la': 'latin (latina)',
    'lv': 'latvian (latviešu)',
    'lt': 'lithuanian (lietuvių)',
    'lb': 'luxembourgish (lëtzebuergesch)',
    'mk': 'macedonian (македонски)',
    'mg': 'malagasy (malagasy)',
    'ms': 'malay (bahasa melayu)',
    'ml': 'malayalam (മലയാളം)',
    'mt': 'maltese (malti)',
    'mi': 'maori (te reo māori)',
    'mr': 'marathi (मराठी)',
    'mn': 'mongolian (монгол)',
    'my': 'myanmar (burmese) (မြန်မာ)',
    'ne': 'nepali (नेपाली)',
    'no': 'norwegian (norsk)',
    'ps': 'pashto (پښتو)',
    'fa': 'persian (فارسی)',
    'pl': 'polish (polski)',
    'pt': 'portuguese (português)',
    'pa': 'punjabi (ਪੰਜਾਬੀ)',
    'ro': 'romanian (română)',
    'ru': 'russian (русский)',
    'sm': 'samoan (gagana samoa)',
    'gd': 'scots gaelic (gàidhlig)',
    'sr': 'serbian (српски)',
    'st': 'sesotho (sesotho)',
    'sn': 'shona (shona)',
    'sd': 'sindhi (سنڌي)',
    'si': 'sinhala (සිංහල)',
    'sk': 'slovak (slovenčina)',
    'sl': 'slovenian (slovenščina)',
    'so': 'somali (soomaali)',
    'es': 'spanish (español)',
    'su': 'sundanese (basa sunda)',
    'sw': 'swahili (kiswahili)',
    'sv': 'swedish (svenska)',
    'tg': 'tajik (тоҷикӣ)',
    'ta': 'tamil (தமிழ்)',
    'te': 'telugu (తెలుగు)',
    'th': 'thai (ไทย)',
    'tr': 'turkish (türkçe)',
    'ur': 'urdu (اردو)',
    'uz': 'uzbek (oʻzbek)',
    'vi': 'vietnamese (tiếng việt)',
    'cy': 'welsh (cymraeg)',
    'xh': 'xhosa (isiXhosa)',
    'yi': 'yiddish (ייִדיש)',
    'yo': 'yoruba (yorùbá)',
    'zu': 'zulu (isiZulu)'
}

LANGUAGES_RU = {
    "af": "африкаанс (Afrikaans)",
    "sq": "албанский (Shqip)",
    "am": "амхарский (አማርኛ)",
    "ar": "арабский (العربية)",
    "hy": "армянский (Հայերեն)",
    "az": "азербайджанский (Azərbaycan)",
    "eu": "баскский (Euskara)",
    "be": "белорусский (Беларуская)",
    "bn": "бенгальский (বাংলা)",
    "bs": "боснийский (Bosanski)",
    "bg": "болгарский (Български)",
    "ca": "каталанский (Català)",
    "ceb": "себуанский (Cebuano)",
    "ny": "чева (Chichewa)",
    "zh-cn": "китайский упрощенный (简体中文)",
    "zh-tw": "китайский традиционный (繁體中文)",
    "co": "корсиканский (Corsu)",
    "hr": "хорватский (Hrvatski)",
    "cs": "чешский (Čeština)",
    "da": "датский (Dansk)",
    "nl": "нидерландский (Nederlands)",
    "en": "английский (English)",
    "eo": "эсперанто (Esperanto)",
    "et": "эстонский (Eesti)",
    "tl": "филиппинский (Filipino)",
    "fi": "финский (Suomi)",
    "fr": "французский (Français)",
    "fy": "фризский (Frysk)",
    "gl": "галисийский (Galego)",
    "ka": "грузинский (ქართული)",
    "de": "немецкий (Deutsch)",
    "el": "греческий (Ελληνικά)",
    "gu": "гуджарати (ગુજરાતી)",
    "ht": "гаитянский креольский (Kreyòl Ayisyen)",
    "ha": "хауса (Hausa)",
    "haw": "гавайский (Ōlelo Hawaiʻi)",
    "he": "иврит (עברית)",
    "hi": "хинди (हिन्दी)",
    "hmn": "хмонг (Hmoob)",
    "hu": "венгерский (Magyar)",
    "is": "исландский (Íslenska)",
    "ig": "игбо (Igbo)",
    "id": "индонезийский (Indonesia)",
    "ga": "ирландский (Gaeilge)",
    "it": "итальянский (Italiano)",
    "ja": "японский (日本語)",
    "jw": "яванский (Jawa)",
    "kn": "каннада (ಕನ್ನಡ)",
    "kk": "казахский (Қазақ)",
    "km": "кхмерский (ខ្មែរ)",
    "ko": "корейский (한국어)",
    "ku": "курдский (Kurdî)",
    "ky": "киргизский (Кыргызча)",
    "lo": "лаосский (ລາວ)",
    "la": "латинский (Latina)",
    "lv": "латышский (Latviešu)",
    "lt": "литовский (Lietuvių)",
    "lb": "люксембургский (Lëtzebuergesch)",
    "mk": "македонский (Македонски)",
    "mg": "малагасийский (Malagasy)",
    "ms": "малайский (Melayu)",
    "ml": "малаялам (മലയാളം)",
    "mt": "мальтийский (Malti)",
    "mi": "маори (Māori)",
    "mr": "маратхи (मराठी)",
    "mn": "монгольский (Монгол)",
    "my": "бирманский (မြန်မာ)",
    "ne": "непальский (नेपाली)",
    "no": "норвежский (Norsk)",
    "ps": "пушту (پښتو)",
    "fa": "персидский (فارسی)",
    "pl": "польский (Polski)",
    "pt": "португальский (Português)",
    "pa": "панджаби (ਪੰਜਾਬੀ)",
    "ro": "румынский (Română)",
    "ru": "русский (Русский)",
    "sm": "самоанский (Samoan)",
    "gd": "шотландский гэльский (Gàidhlig)",
    "sr": "сербский (Српски)",
    "st": "сесото (Sesotho)",
    "sn": "шона (Shona)",
    "sd": "синдхи (سنڌي)",
    "si": "сингальский (සිංහල)",
    "sk": "словацкий (Slovenčina)",
    "sl": "словенский (Slovenščina)",
    "so": "сомали (Soomaali)",
    "es": "испанский (Español)",
    "su": "сунданский (Sunda)",
    "sw": "суахили (Kiswahili)",
    "sv": "шведский (Svenska)",
    "tg": "таджикский (Тоҷикӣ)",
    "ta": "тамильский (தமிழ்)",
    "te": "телугу (తెలుగు)",
    "th": "тайский (ไทย)",
    "tr": "турецкий (Türkçe)",
    "ur": "урду (اردو)",
    "uz": "узбекский (O'zbek)",
    "vi": "вьетнамский (Tiếng Việt)",
    "cy": "валлийский (Cymraeg)",
    "xh": "коса (isiXhosa)",
    "yi": "идиш (ייִדיש)",
    "yo": "йоруба (Yorùbá)",
    "zu": "зулу (isiZulu)"
}
