---
title: Getting started
---

## Installation

Python 3.7 or higher is required. `lintquarto` itself has only one required package: `toml`.

You can install **lintquarto** with pip ([from PyPI](https://pypi.org/project/lintquarto/)) or conda ([from conda-forge](https://anaconda.org/conda-forge/lintquarto)).

### Install with pip

Install `lintquarto` with:

```{.bash}
pip install lintquarto
```

Linters are installed separately. For example, to use `pylint` and `flake8`, run:

```{.bash}
pip install pylint flake8
```

If you want to install `lintquarto` along with all supported linters, use:

```{.bash}
pip install lintquarto[all]
```

You can verify your installation with:

```{.bash}
lintquarto --version
```

### Install with conda

```
conda install conda-forge::lintquarto
```

With conda, only the main lintquarto tool is installed. If you want to use any linters or type checkers, you must install them separately (either with conda or pip, depending on availability).

## Basic usage

Usage:

```
lintquarto -l LINTER [LINTER ...] -p PATH [PATH ...] [-e EXCLUDE [EXCLUDE ...]] [-k]
```

Options:

* `-l, --linters LINTER [LINTER ...]` - linters to run.
* `-p, --paths PATH [PATH ...]` - quarto files and/or directories to include.
* `-e, --exclude EXCLUDE [EXCLUDE ...]` - optional, files and/or directories to exclude.
* `-k, --keep-temp` - optional, keep temporary `.py` files created during linting (for debugging).

Passing extra arguments directly to linters is not supported. Only `.qmd` files are processed.

<br>

## Examples

The linter used is interchangeable in these examples.

Lint all `.qmd` files in the current directory (using `pylint`):

```{.bash}
lintquarto -l pylint -p .
```

Lint several specific files (using `pylint` and `flake8`):

```{.bash}
lintquarto -l pylint flake8 -p file1.qmd file2.qmd
```

Keep temporary `.py` files after linting (with `pylint`)

```{.bash}
lintquarto -l pylint -p . -k
```

Lint all files in current directory (using `ruff`):

* Excluding folders `examples/` and `ignore/`, or-
* Excluding a specific file `analysis/test.qmd`.

```{.bash}
lintquarto -l ruff -p . -e examples ignore
```

```{.bash}
lintquarto -l ruff -p . -e analysis/test.qmd
```
