# from distutils.core import setup
from setuptools import setup, find_packages

setup(
    name='elsciRL',
    version='0.4.0',
    packages=[
        'elsciRL', 
        'elsciRL.adapters',
        'elsciRL.adapters.LLM_state_generators',
        'elsciRL.agents',
        'elsciRL.agents.LLM_agents',
        'elsciRL.agents.stable_baselines',
        'elsciRL.analysis',
        'elsciRL.application_suite',
        'elsciRL.encoders', 
        'elsciRL.encoders.language_transformers',
        'elsciRL.environment_setup',
        'elsciRL.evaluation',
        'elsciRL.examples',
        'elsciRL.examples.adapters',
        'elsciRL.examples.environments',
        'elsciRL.examples.local_configs',
        'elsciRL.experiments',
        'elsciRL.experiments.experiment_utils',
        'elsciRL.experiments.training_procedures',
        'elsciRL.GUI',
        'elsciRL.GUI.static',
        'elsciRL.GUI.templates',
        'elsciRL.experiments',
        'elsciRL.instruction_following',
        'elsciRL.instruction_following.LLM_instr_planner',
        'elsciRL.instruction_following.instr_utils',
        'elsciRL.interaction_loops',
        'elsciRL.published_experiments',
        ],
    package_data={
        'elsciRL.GUI.templates': ['index.html', '_generic_agent_param_form.html'],
        'elsciRL.GUI.static': ['styles.css', 'app_setup.md'],
    },
    include_package_data=True,
    url='https://github.com/pdfosborne/elsciRL',
    license='Apache-2.0 license',
    author='Philip Osborne',
    author_email='pdfosborne@gmail.com',
    description='Apply language solutions to Reinforcement Learning problems.',
    install_requires=[
        'numpy',
        'pandas',
        'matplotlib',
        'seaborn',
        'scipy>=1.10.1',
        'torch',
        'tqdm',
        'httpimport',
        'sentence-transformers',
        'gymnasium',
        'stable-baselines3',
        'flask',
        'ollama',
        'markdown',
    ] 
)
