from .logic import multiplicity_e
from .logic import multiplicity_n
from .logic import multiplicity_o
from .logic import multiplicity_q
from .logic import multiplicity_z
from .logic import conjunction
from .logic import disjunction
from .logic import negation
from .logic import implication
from .logic import equivalence