# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
{
    "name": "Employee Payslip",
    "version": "14.0.2.2.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_hr",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_duration_mixin",
        "ssi_employee_document_mixin",
        "ssi_financial_accounting",
    ],
    "data": [
        "menu.xml",
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/policy_template_data.xml",
        "data/approval_template_data.xml",
        "views/hr_payslip_type_views.xml",
        "views/hr_payslip_input_type_views.xml",
        "views/hr_salary_contribution_views.xml",
        "views/hr_salary_rule_category_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_salary_structure_views.xml",
        "views/hr_payslip_input_views.xml",
        "views/hr_payslip_line_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_employee_input_type_views.xml",
        "views/hr_employee_input_views.xml",
        "views/hr_employee_views.xml",
    ],
    "demo": [
        # "demo/account_account_demo.xml",
        # "demo/account_journal_demo.xml",
        # "demo/hr_payslip_type_demo.xml",
        # "demo/hr_salary_contribution_demo.xml",
        # "demo/hr_salary_rule_category_demo.xml",
        # "demo/hr_payslip_input_type_demo.xml",
        # "demo/hr_employee_input_type_demo.xml",
        # "demo/hr_salary_rule_demo.xml",
        # "demo/hr_salary_structure_demo.xml",
    ],
    "images": [],
}
