datetime_format = [
    "%Y-%m-%dT%H:%M:%S",
    "%Y",
    "%Y/%m/%d",
    "%Y-%m-%d",
    "%d/%m/%Y",
    "%d-%m-%Y",
    "%Y/%m/%d %H:%M:%S",
    "%Y-%m-%d %H:%M:%S",
    "%d/%m/%Y %H:%M:%S",
    "%d-%m-%Y %H:%M:%S",
    "%Y/%m/%dT%H:%M:%S",
    "%d/%m/%yT%H:%M:%S",
    "%d-%m-%yT%H:%M:%S",
]
