IOC_PACKAGES = {
    # -------------------
    # Name-only Treffer (keine Versionen im Advisory genannt)
    # -------------------
    "@ahmedhfarag/ngx-perfect-scrollbar": None,
    "@ahmedhfarag/ngx-virtual-scroller": None,
    "@art-ws/common": None,
    "@art-ws/config-eslint": None,
    "@art-ws/config-ts": None,
    "@art-ws/db-context": None,
    "@art-ws/di-node": None,
    "@art-ws/di": None,
    "@art-ws/eslint": None,
    "@art-ws/fastify-http-server": None,
    "@art-ws/http-server": None,
    "@art-ws/openapi": None,
    "@art-ws/package-base": None,
    "@art-ws/prettier": None,
    "@art-ws/slf": None,
    "@art-ws/ssl-info": None,
    "@art-ws/web-app": None,
    "@hestjs/core": None,
    "@hestjs/cqrs": None,
    "@hestjs/demo": None,
    "@hestjs/eslint-config": None,
    "@hestjs/logger": None,
    "@hestjs/scalar": None,
    "@hestjs/validation": None,

    # -------------------
    # Mit Versionen
    # -------------------
    "@crowdstrike/commitlint": {"8.1.1", "8.1.2"},
    "@crowdstrike/falcon-shoelace": {"0.4.1", "0.4.2"},
    "@crowdstrike/foundry-js": {"0.19.1", "0.19.2"},
    "@crowdstrike/glide-core": {"0.34.2", "0.34.3"},
    "@crowdstrike/logscale-dashboard": {"1.205.1", "1.205.2"},
    "@crowdstrike/logscale-file-editor": {"1.205.1", "1.205.2"},
    "@crowdstrike/logscale-parser-edit": {"1.205.1", "1.205.2"},
    "@crowdstrike/logscale-search": {"1.205.1", "1.205.2"},
    "@crowdstrike/tailwind-toucan-base": {"5.0.1", "5.0.2"},

    "@ctrl/deluge": {"7.2.1", "7.2.2", "7.0.0"},
    "@ctrl/golang-template": {"1.4.2", "1.4.3"},
    "@ctrl/magnet-link": {"4.0.3", "4.0.4"},
    "@ctrl/ngx-codemirror": {"7.0.1", "7.0.2"},
    "@ctrl/ngx-csv": {"6.0.1", "6.0.2"},
    "@ctrl/ngx-emoji-mart": {"9.2.1", "9.2.2"},
    "@ctrl/ngx-rightclick": {"4.0.1", "4.0.2"},
    "@ctrl/qbittorrent": {"9.7.1", "9.7.2"},
    "@ctrl/react-adsense": {"2.0.1", "2.0.2"},
    "@ctrl/shared-torrent": {"6.3.1", "6.3.2"},
    "@ctrl/tinycolor": {"4.1.1", "4.1.2"},
    "@ctrl/torrent-file": {"4.1.1", "4.1.2"},
    "@ctrl/transmission": {"7.3.1"},
    "@ctrl/ts-base32": {"4.0.1", "4.0.2"},

    "@nativescript-community/arraybuffers": {"1.1.6", "1.1.7", "1.1.8"},
    "@nativescript-community/gesturehandler": {"2.0.35"},
    "@nativescript-community/perms": {"3.0.5", "3.0.6", "3.0.7", "3.0.8", "3.0.9"},
    "@nativescript-community/sentry": {"4.6.43"},
    "@nativescript-community/sqlite": {"3.5.2", "3.5.3", "3.5.4", "3.5.5"},
    "@nativescript-community/text": {"1.6.9", "1.6.10", "1.6.11", "1.6.12", "1.6.13"},
    "@nativescript-community/typeorm": {"0.2.30", "0.2.31", "0.2.32", "0.2.33"},
    "@nativescript-community/ui-collectionview": {"6.0.6"},
    "@nativescript-community/ui-document-picker": {"1.1.27", "1.1.28", "13.0.32"},
    "@nativescript-community/ui-drawer": {"0.1.30"},
    "@nativescript-community/ui-image": {"4.5.6"},
    "@nativescript-community/ui-material-bottomsheet": {"7.2.72"},
    "@nativescript-community/ui-material-core": {"7.2.76"},
    "@nativescript-community/ui-material-core-tabs": {"7.2.76"},

    "@teselagen/bio-parsers": {"0.4.29"},
    "@teselagen/bounce-loader": {"0.3.16"},
    "@teselagen/file-utils": {"0.3.21"},
    "@teselagen/liquibase-tools": {"0.4.1"},
    "@teselagen/ove": {"0.7.39"},
    "@teselagen/range-utils": {"0.3.14"},
    "@teselagen/react-list": {"0.8.19"},
    "@teselagen/react-table": {"6.10.21"},
    "@teselagen/sequence-utils": {"0.3.33"},
    "@teselagen/ui": {"0.9.9"},

    "angulartics2": {"14.1.2"},
    "encounter-playground": {"0.0.4", "0.0.5"},
    "eslint-config-teselagen": {"6.1.7"},
    "graphql-sequelize-teselagen": {"5.3.8"},
    "json-rules-engine-simplified": {"0.2.1", "0.2.3", "0.2.4"},
    "koa2-swagger-ui": {"5.11.1", "5.11.2"},
    "ng2-file-upload": {"8.0.3"},
    "ngx-bootstrap": {"18.1.4", "19.0.3", "20.0.4", "20.0.5", "20.0.6"},
    "ngx-color": {"10.0.2"},
    "ngx-toastr": {"19.0.2", "10.0.4", "11.1.0"},
    "ngx-trend": {"8.0.1"},
    "oradm-to-gql": {"35.0.14"},
    "oradm-to-sqlz": {"1.1.4"},
    "ove-auto-annotate": {"0.0.9"},
    "react-complaint-image": {"0.0.34", "0.0.35"},
    "react-jsonschema-form-conditionals": {"0.3.20", "0.3.21"},
    "react-jsonschema-form-extras": {"1.0.3", "1.0.4"},
    "react-jsonschema-rxnt-extras": {"0.4.8"},
    "rxnt-authentication": {"0.0.5", "0.0.6"},
    "rxnt-healthchecks-nestjs": {"1.0.4", "1.0.5"},
    "rxnt-kue": {"1.0.6", "1.0.7"},
    "swc-plugin-component-annotate": {"1.9.2"},
    "tg-client-query-builder": {"2.14.4"},
    "tg-redbird": {"1.3.1"},
    "tg-seq-gen": {"1.0.9"},
    "ts-gaussian": {"3.0.6"},
    "ve-bamreader": {"0.2.6"},
    "ve-editor": {"1.0.1"},
}

