# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .app_api_v2marketplace_skills_views_parameter_type import AppApiV2MarketplaceSkillsViewsParameterType


class AppApiV2MarketplaceSkillsViewsParameterSchema(UncheckedBaseModel):
    """
    Schema for a skill parameter.
    """

    name: str
    type: AppApiV2MarketplaceSkillsViewsParameterType
    required: typing.Optional[bool] = None
    description: typing.Optional[str] = None
    default: typing.Optional[typing.Optional[typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
