# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.306.1368
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.infra_alert_config_with_metadata import InfraAlertConfigWithMetadata

class TestInfraAlertConfigWithMetadata(unittest.TestCase):
    """InfraAlertConfigWithMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfraAlertConfigWithMetadata:
        """Test InfraAlertConfigWithMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfraAlertConfigWithMetadata`
        """
        model = InfraAlertConfigWithMetadata()
        if include_optional:
            return InfraAlertConfigWithMetadata(
                alert_channel_ids = [
                    ''
                    ],
                alert_channels = {
                    'key' : [
                        ''
                        ]
                    },
                created = 1,
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '', 
                        type = '', )
                    ],
                description = '',
                enabled = True,
                evaluation_type = 'PER_ENTITY',
                grace_period = 56,
                granularity = 60000,
                group_by = [
                    ''
                    ],
                id = '',
                initial_created = 1,
                name = '',
                read_only = True,
                rule = instana_client.models.infra_alert_rule.InfraAlertRule(
                    aggregation = 'SUM', 
                    alert_type = '', 
                    cross_series_aggregation = 'SUM', 
                    entity_type = '', 
                    metric_group_by = [
                        ''
                        ], 
                    metric_name = '', 
                    metric_tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                        type = '', ), 
                    regex = True, ),
                rules = [
                    instana_client.models.rule_with_threshold_infra_alert_rule.RuleWithThresholdInfraAlertRule(
                        rule = instana_client.models.infra_alert_rule.InfraAlertRule(
                            aggregation = 'SUM', 
                            alert_type = '', 
                            cross_series_aggregation = 'SUM', 
                            entity_type = '', 
                            metric_group_by = [
                                ''
                                ], 
                            metric_name = '', 
                            metric_tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                                type = '', ), 
                            regex = True, ), 
                        threshold_operator = '>', 
                        thresholds = {
                            'key' : instana_client.models.threshold_config_rule.ThresholdConfigRule(
                                type = '', )
                            }, )
                    ],
                severity = 56,
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                threshold = instana_client.models.threshold.Threshold(
                    operator = '>', 
                    type = '', ),
                time_threshold = instana_client.models.infra_time_threshold.InfraTimeThreshold(
                    time_window = 56, 
                    type = '', ),
                triggering = True
            )
        else:
            return InfraAlertConfigWithMetadata(
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '', 
                        type = '', )
                    ],
                description = '',
                granularity = 60000,
                group_by = [
                    ''
                    ],
                id = '',
                name = '',
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                time_threshold = instana_client.models.infra_time_threshold.InfraTimeThreshold(
                    time_window = 56, 
                    type = '', ),
        )
        """

    def testInfraAlertConfigWithMetadata(self):
        """Test InfraAlertConfigWithMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
