# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.306.1368
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.application_node import ApplicationNode

class TestApplicationNode(unittest.TestCase):
    """ApplicationNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationNode:
        """Test ApplicationNode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationNode`
        """
        model = ApplicationNode()
        if include_optional:
            return ApplicationNode(
                application_id = '',
                inclusive = True,
                services = {
                    'key' : instana_client.models.service_node.ServiceNode(
                        endpoints = {
                            'key' : instana_client.models.endpoint_node.EndpointNode(
                                endpoint_id = '', 
                                inclusive = True, )
                            }, 
                        inclusive = True, 
                        service_id = '', )
                    }
            )
        else:
            return ApplicationNode(
                application_id = '',
                services = {
                    'key' : instana_client.models.service_node.ServiceNode(
                        endpoints = {
                            'key' : instana_client.models.endpoint_node.EndpointNode(
                                endpoint_id = '', 
                                inclusive = True, )
                            }, 
                        inclusive = True, 
                        service_id = '', )
                    },
        )
        """

    def testApplicationNode(self):
        """Test ApplicationNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
