# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.306.1368
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.infrastructure_alert_configuration_api import InfrastructureAlertConfigurationApi


class TestInfrastructureAlertConfigurationApi(unittest.TestCase):
    """InfrastructureAlertConfigurationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfrastructureAlertConfigurationApi()

    def tearDown(self) -> None:
        pass

    def test_create_infra_alert_config(self) -> None:
        """Test case for create_infra_alert_config

        Create Infra Alert Config
        """
        pass

    def test_delete_infra_alert_config(self) -> None:
        """Test case for delete_infra_alert_config

        Delete Infra Alert Config
        """
        pass

    def test_disable_infra_alert_config(self) -> None:
        """Test case for disable_infra_alert_config

        Disable Infra Alert Config
        """
        pass

    def test_enable_infra_alert_config(self) -> None:
        """Test case for enable_infra_alert_config

        Enable Infra Alert Config
        """
        pass

    def test_find_active_infra_alert_configs(self) -> None:
        """Test case for find_active_infra_alert_configs

        All Infra Alert Configs
        """
        pass

    def test_find_infra_alert_config(self) -> None:
        """Test case for find_infra_alert_config

        Get Infra Alert Config
        """
        pass

    def test_find_infra_alert_config_versions(self) -> None:
        """Test case for find_infra_alert_config_versions

        Get versions of Infra Alert Config
        """
        pass

    def test_restore_infra_alert_config(self) -> None:
        """Test case for restore_infra_alert_config

        Restore Infra Alert Config
        """
        pass

    def test_update_infra_alert_config(self) -> None:
        """Test case for update_infra_alert_config

        Update Infra Alert Config
        """
        pass


if __name__ == '__main__':
    unittest.main()
