from __future__ import annotations

from typing import Dict, Iterable, List, Optional

class CompiledPatternMatcher:
    def __init__(self, max_cache_size: int = ...) -> None: ...
    def add_pattern(self, name: str, pattern: str, flags: int = ...) -> None: ...
    def add_compiled_pattern(self, name: str, pattern: object) -> None: ...
    def matches(self, text: str, pattern_name: str) -> bool: ...
    def match(self, text: str, pattern_name: str) -> object | None: ...
    def find_first_match(
        self, text: str, pattern_names: Iterable[str]
    ) -> str | None: ...
    def find_all_matches(
        self, text: str, pattern_names: Optional[Iterable[str]] = ...
    ) -> List[str]: ...
    def clear_cache(self) -> None: ...
    def get_patterns(self) -> Dict[str, str]: ...
    def cache_size(self) -> int: ...

class DomainRuleMatcher:
    def __init__(self, max_cache_size: int = ...) -> None: ...
    def add_domain_rule(self, domain_pattern: str, rules: Dict) -> None: ...
    def get_rules_for_domain(self, domain: str) -> Dict: ...
    def clear_cache(self) -> None: ...

class URLClassifier:
    def __init__(self, max_cache_size: int = ...) -> None: ...
    def classify_url(self, url: str) -> str: ...
    def add_custom_pattern(self, name: str, pattern: str, flags: int = ...) -> None: ...
    def clear_cache(self) -> None: ...
