# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""The engine package contains core functionality for indexing, chunking, and searching code and documentation data, but also for other data providers 🚋."""

from __future__ import annotations

from importlib import import_module
from types import MappingProxyType
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from codeweaver.engine.chunker import (
        ASTDepthExceededError,
        BinaryFileError,
        Boundary,
        ChunkerSelector,
        ChunkGovernor,
        ChunkingError,
        ChunkingTimeoutError,
        ChunkLimitExceededError,
        Delimiter,
        DelimiterChunker,
        DelimiterDict,
        DelimiterKind,
        DelimiterMatch,
        DelimiterPattern,
        GracefulChunker,
        LanguageFamily,
        LineStrategy,
        OversizedChunkError,
        ParseError,
        ResourceGovernor,
        SemanticChunker,
        SourceIdRegistry,
        chunk_files_parallel,
        chunk_files_parallel_dict,
        clear_store,
        detect_language_family,
        expand_pattern,
        get_store,
        source_id_for,
    )
    from codeweaver.engine.chunking_service import ChunkingService
    from codeweaver.engine.search import (
        AnyVariants,
        ArbitraryFilter,
        Condition,
        DatetimeRange,
        Entry,
        ExtendedPointId,
        FieldCondition,
        Filter,
        FilterableField,
        GeoBoundingBox,
        GeoLineString,
        GeoPoint,
        GeoPolygon,
        GeoRadius,
        HasIdCondition,
        HasVectorCondition,
        IsEmptyCondition,
        IsNullCondition,
        Match,
        MatchAny,
        MatchExcept,
        MatchPhrase,
        MatchText,
        MatchValue,
        MinShould,
        Nested,
        NestedCondition,
        PayloadField,
        PayloadMetadata,
        PayloadSchemaType,
        Range,
        ValuesCount,
        ValueVariants,
        make_partial_function,
        wrap_filters,
    )
    from codeweaver.engine.watcher import (
        CodeFilter,
        ConfigFilter,
        DefaultFilter,
        DocsFilter,
        ExtensionFilter,
        FileWatcher,
        IgnoreFilter,
    )

parent = __spec__.parent or "codeweaver.engine"

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ASTDepthExceededError": (f"{parent}.chunker", "exceptions"),
    "AnyVariants": (f"{parent}", "search"),
    "ArbitraryFilter": (f"{parent}", "search"),
    "BinaryFileError": (f"{parent}.chunker", "exceptions"),
    "Boundary": (f"{parent}.chunker", "delimiter_model"),
    "ChunkGovernor": (f"{parent}.chunker", "base"),
    "ChunkLimitExceededError": (f"{parent}.chunker", "exceptions"),
    "ChunkerSelector": (f"{parent}.chunker", "selector"),
    "ChunkingError": (f"{parent}.chunker", "exceptions"),
    "ChunkingService": (parent, "chunking_service"),
    "ChunkingTimeoutError": (f"{parent}.chunker", "exceptions"),
    "CodeFilter": (parent, "watcher"),
    "Condition": (parent, "search"),
    "ConfigFilter": (parent, "watcher"),
    "DatetimeRange": (parent, "search"),
    "DefaultFilter": (parent, "watcher"),
    "Delimiter": (f"{parent}.chunker", "delimiter_model"),
    "DelimiterChunker": (f"{parent}.chunker", "delimiter"),
    "DelimiterKind": (f"{parent}.chunker.delimiters", "kind"),
    "DelimiterMatch": (f"{parent}.chunker", "delimiter_model"),
    "DelimiterPattern": (f"{parent}.chunker.delimiters", "patterns"),
    "DelimiterDict": (f"{parent}.chunker.delimiters", "patterns"),
    "DocsFilter": (parent, "watcher"),
    "Entry": (parent, "search"),
    "ExtendedPointId": (parent, "search"),
    "ExtensionFilter": (parent, "watcher"),
    "FieldCondition": (parent, "search"),
    "FileWatcher": (parent, "watcher"),
    "Filter": (parent, "search"),
    "FilterableField": (parent, "search"),
    "GeoBoundingBox": (parent, "search"),
    "GeoLineString": (parent, "search"),
    "GeoPoint": (parent, "search"),
    "GeoPolygon": (parent, "search"),
    "GeoRadius": (parent, "search"),
    "GracefulChunker": (f"{parent}.chunker", "selector"),
    "HasIdCondition": (parent, "search"),
    "HasVectorCondition": (parent, "search"),
    "IgnoreFilter": (parent, "watcher"),
    "Indexer": (parent, "indexer"),
    "IsEmptyCondition": (parent, "search"),
    "IsNullCondition": (parent, "search"),
    "LanguageFamily": (f"{parent}.chunker.delimiters", "families"),
    "LineStrategy": (f"{parent}.chunker.delimiters", "kind"),
    "Match": (parent, "search"),
    "MatchAny": (parent, "search"),
    "MatchExcept": (parent, "search"),
    "MatchPhrase": (parent, "search"),
    "MatchText": (parent, "search"),
    "MatchValue": (parent, "search"),
    "MinShould": (parent, "search"),
    "Nested": (parent, "search"),
    "NestedCondition": (parent, "search"),
    "OversizedChunkError": (f"{parent}.chunker", "exceptions"),
    "ParseError": (f"{parent}.chunker", "exceptions"),
    "PayloadField": (parent, "search"),
    "PayloadMetadata": (parent, "search"),
    "PayloadSchemaType": (parent, "search"),
    "Range": (parent, "search"),
    "ResourceGovernor": (f"{parent}.chunker", "governance"),
    "SemanticChunker": (f"{parent}.chunker", "semantic"),
    "SourceIdRegistry": (f"{parent}.chunker", "registry"),
    "ValueVariants": (parent, "search"),
    "ValuesCount": (parent, "search"),
    "chunk_files_parallel": (f"{parent}.chunker", "parallel"),
    "chunk_files_parallel_dict": (f"{parent}.chunker", "parallel"),
    "clear_store": (f"{parent}.chunker", "registry"),
    "detect_language_family": (f"{parent}.chunker.delimiters", "families"),
    "expand_pattern": (f"{parent}.chunker.delimiters", "patterns"),
    "get_store": (f"{parent}.chunker", "registry"),
    "make_partial_function": (parent, "search"),
    "source_id_for": (f"{parent}.chunker", "registry"),
    "wrap_filters": (parent, "search"),
})


def __getattr__(name: str) -> object:
    """Dynamically import submodules and classes for the engine package."""
    if name in _dynamic_imports:
        module_name, submodule_name = _dynamic_imports[name]
        module = import_module(f"{module_name}.{submodule_name}")
        result = getattr(module, name)
        globals()[name] = result  # Cache in globals for future access
        return result
    if globals().get(name) is not None:
        return globals()[name]
    raise AttributeError(f"module {__name__} has no attribute {name}")


__all__ = (
    "ASTDepthExceededError",
    "AnyVariants",
    "ArbitraryFilter",
    "BinaryFileError",
    "Boundary",
    "ChunkGovernor",
    "ChunkLimitExceededError",
    "ChunkerSelector",
    "ChunkingError",
    "ChunkingService",
    "ChunkingTimeoutError",
    "CodeFilter",
    "Condition",
    "ConfigFilter",
    "DatetimeRange",
    "DefaultFilter",
    "Delimiter",
    "DelimiterChunker",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterMatch",
    "DelimiterPattern",
    "DocsFilter",
    "Entry",
    "ExtendedPointId",
    "ExtensionFilter",
    "FieldCondition",
    "FileWatcher",
    "Filter",
    "FilterableField",
    "GeoBoundingBox",
    "GeoLineString",
    "GeoPoint",
    "GeoPolygon",
    "GeoRadius",
    "GracefulChunker",
    "HasIdCondition",
    "HasVectorCondition",
    "IgnoreFilter",
    "Indexer",
    "IsEmptyCondition",
    "IsNullCondition",
    "LanguageFamily",
    "LineStrategy",
    "Match",
    "MatchAny",
    "MatchExcept",
    "MatchPhrase",
    "MatchText",
    "MatchValue",
    "MinShould",
    "Nested",
    "NestedCondition",
    "OversizedChunkError",
    "ParseError",
    "PayloadField",
    "PayloadMetadata",
    "PayloadSchemaType",
    "Range",
    "ResourceGovernor",
    "SemanticChunker",
    "SourceIdRegistry",
    "ValueVariants",
    "ValuesCount",
    "chunk_files_parallel",
    "chunk_files_parallel_dict",
    "clear_store",
    "detect_language_family",
    "expand_pattern",
    "get_store",
    "make_partial_function",
    "source_id_for",
    "wrap_filters",
)


def __dir__() -> list[str]:
    """List available attributes for the engine package."""
    return list(__all__)
