def getAtomLabel(tp, component, *args, **kwargs):
    eol = "\n"
    js = ""
    js += "(component, molecule) => {" + eol
    js += "  var labels = {" + eol
    js += "    'Hydrogen':'H'," + eol
    js += "    'Helium':'He'," + eol
    js += "    'Lithium':'Li'," + eol
    js += "    'Beryllium':'Be'," + eol
    js += "    'Boron':'B'," + eol
    js += "    'Carbon':'C'," + eol
    js += "    'Nitrogen':'N'," + eol
    js += "    'Oxygen':'O'," + eol
    js += "    'Fluorine':'F'," + eol
    js += "    'Neon':'Ne'," + eol
    js += "    'Sodium':'Na'," + eol
    js += "    'Magnesium':'Mg'," + eol
    js += "    'Aluminium':'Al'," + eol
    js += "    'Silicon':'Si'," + eol
    js += "    'Phosphorus':'P'," + eol
    js += "    'Sulfur':'S'," + eol
    js += "    'Chlorine':'Cl'," + eol
    js += "    'Argon':'Ar'," + eol
    js += "    'Potassium':'K'," + eol
    js += "    'Calcium':'Ca'," + eol
    js += "    'Scandium':'Sc'," + eol
    js += "    'Titanium':'Ti'," + eol
    js += "    'Vanadium':'V'," + eol
    js += "    'Chromium':'Cr'," + eol
    js += "    'Manganese':'Mn'," + eol
    js += "    'Iron':'Fe'," + eol
    js += "    'Cobalt':'Co'," + eol
    js += "    'Nickel':'Ni'," + eol
    js += "    'Copper':'Cu'," + eol
    js += "    'Zinc':'Zn'," + eol
    js += "    'Gallium':'Ga'," + eol
    js += "    'Germanium':'Ge'," + eol
    js += "    'Arsenic':'As'," + eol
    js += "    'Selenium':'Se'," + eol
    js += "    'Bromine':'Br'," + eol
    js += "    'Krypton':'Kr'," + eol
    js += "    'Rubidium':'Rb'," + eol
    js += "    'Strontium':'Sr'," + eol
    js += "    'Yttrium':'Y'," + eol
    js += "    'Zirconium':'Zr'," + eol
    js += "    'Niobium':'Nb'," + eol
    js += "    'Molybdenum':'Mo'," + eol
    js += "    'Technetium':'Tc'," + eol
    js += "    'Ruthenium':'Ru'," + eol
    js += "    'Rhodium':'Rh'," + eol
    js += "    'Palladium':'Pd'," + eol
    js += "    'Silver':'Ag'," + eol
    js += "    'Cadmium':'Cd'," + eol
    js += "    'Indium':'In'," + eol
    js += "    'Tin':'Sn'," + eol
    js += "    'Antimony':'Sb'," + eol
    js += "    'Tellurium':'Te'," + eol
    js += "    'Iodine':'I'," + eol
    js += "    'Xenon':'Xe'," + eol
    js += "    'Caesium':'Cs'," + eol
    js += "    'Barium':'Ba'," + eol
    js += "    'Lanthanum':'La'," + eol
    js += "    'Cerium':'Ce'," + eol
    js += "    'Praseodymium':'Pr'," + eol
    js += "    'Neodymium':'Nd'," + eol
    js += "    'Promethium':'Pm'," + eol
    js += "    'Samarium':'Sm'," + eol
    js += "    'Europium':'Eu'," + eol
    js += "    'Gadolinium':'Gd'," + eol
    js += "    'Terbium':'Tb'," + eol
    js += "    'Dysprosium':'Dy'," + eol
    js += "    'Holmium':'Ho'," + eol
    js += "    'Erbium':'Er'," + eol
    js += "    'Thulium':'Tm'," + eol
    js += "    'Ytterbium':'Yb'," + eol
    js += "    'Lutetium':'Lu'," + eol
    js += "    'Hafnium':'Hf'," + eol
    js += "    'Tantalum':'Ta'," + eol
    js += "    'Tungsten':'W'," + eol
    js += "    'Rhenium':'Re'," + eol
    js += "    'Osmium':'Os'," + eol
    js += "    'Iridium':'Ir'," + eol
    js += "    'Platinum':'Pt'," + eol
    js += "    'Gold':'Au'," + eol
    js += "    'Mercury':'Hg'," + eol
    js += "    'Thallium':'Tl'," + eol
    js += "    'Lead':'Pb'," + eol
    js += "    'Bismuth':'Bi'," + eol
    js += "    'Polonium':'Po'," + eol
    js += "    'Astatine':'At'," + eol
    js += "    'Radon':'Rn'," + eol
    js += "    'Francium':'Fr'," + eol
    js += "    'Radium':'Ra'," + eol
    js += "    'Actinium':'Ac'," + eol
    js += "    'Thorium':'Th'," + eol
    js += "    'Protactinium':'Pa'," + eol
    js += "    'Uranium':'U'," + eol
    js += "    'Neptunium':'Np'," + eol
    js += "    'Plutonium':'Pu'," + eol
    js += "    'Americium':'Am'," + eol
    js += "    'Curium':'Cm'," + eol
    js += "    'Berkelium':'Bk'," + eol
    js += "    'Californium':'Cf'," + eol
    js += "    'Einsteinium':'Es'," + eol
    js += "    'Fermium':'Fm'," + eol
    js += "    'Mendelevium':'Md'," + eol
    js += "    'Nobelium':'No'," + eol
    js += "    'Lawrencium':'Lr'," + eol
    js += "    'Rutherford:':'Rf'," + eol
    js += "    'Dubnium':'Db'," + eol
    js += "    'Seaborgium':'Sg'," + eol
    js += "    'Bohrium':'Bh'," + eol
    js += "    'Hassium':'Hs'," + eol
    js += "    'Meitnerium':'M'," + eol
    js += "  };" + eol
    js += "  if (molecule in labels) {" + eol
    js += "    return labels[molecule];" + eol
    js += (
        "  } else if (Number.isInteger(molecule) && molecule <= Object.keys(labels).length) {"
        + eol
    )
    js += "    return labels[Object.keys(labels)[molecule-1]];" + eol
    js += "  } else {" + eol
    js += "    return molecule;" + eol
    js += "  }" + eol
    js += "}" + eol

    component.addPropVariable("getAtomLabel", {"type": "func", "defaultValue": js})
    return {"type": "propCall2", "calls": "getAtomLabel", "args": ["self", "[]"]}

def getColor(tp, component, *args, **kwargs):
    getAtomLabel(tp, component)
    eol = "\n"
    js = ""
    js += "(component, molecule) => {" + eol
    js += "  var jcpk = {" + eol
    js += "    'H'  : 'rgba(255,255,255,1.0)'," + eol
    js += "    'He'  : 'rgba(20,20,20,1.0)'," + eol
    js += "    'Li' : 'rgba(188,190,187,1.0)'," + eol
    js += "    'Be' : 'rgba(134,134,134,1.0)'," + eol
    js += "    'B' : 'rgba(122,117,114,1.0)'," + eol
    js += "    'C' : 'rgba(31,120,180,1.0)'," + eol
    js += "    'N' : 'rgba(177,89,40,1.0)'," + eol
    js += "    'O' : 'rgba(238,32,16,1.0)'," + eol
    js += "    'F' : 'rgba(177,146,82,1.0)'," + eol
    js += "    'Ne' : 'rgba(255,0,0,1.0)'," + eol
    js += "    'Na' : 'rgba(218,220,217,1.0)'," + eol
    js += "    'Mg' : 'rgba(195,195,185,1.0)'," + eol
    js += "    'Al' : 'rgba(255,0,102,1.0)'," + eol
    js += "    'Si' : 'rgba(73,4,170,1.0)'," + eol
    js += "    'P' : 'rgba(255,0,9,1.0)'," + eol
    js += "    'S' : 'rgba(248,239,146,1.0)'," + eol
    js += "    'Cl' : 'rgba(251,154,153,1.0)'," + eol
    js += "    'Ar' : 'rgba(221,112,244,1.0)'," + eol
    js += "    'K' : 'rgba(165,171,171,1.0)'," + eol
    js += "    'Ca' : 'rgba(227,26,28,1.0)'," + eol
    js += "    'Sc' : 'rgba(176,173,166,1.0)'," + eol
    js += "    'Ti' : 'rgba(169,163,147,1.0)'," + eol
    js += "    'V' : 'rgba(191,189,202,1.0)'," + eol
    js += "    'Cr' : 'rgba(191,198,206,1.0)'," + eol
    js += "    'Mn' : 'rgba(206,205,200,1.0)'," + eol
    js += "    'Fe' : 'rgba(185,183,184,1.0)'," + eol
    js += "    'Co' : 'rgba(171,163,160,1.0)'," + eol
    js += "    'Ni' : 'rgba(181,165,150,1.0)'," + eol
    js += "    'Cu' : 'rgba(196,78,46,1.0)'," + eol
    js += "    'Zn' : 'rgba(255,0,0,1.0)'," + eol
    js += "    'Ga' : 'rgba(255,51,0,1.0)'," + eol
    js += "    'Ge' : 'rgba(0,255,0,1.0)'," + eol
    js += "    'As' : 'rgba(255,255,0,1.0)'," + eol
    js += "    'Se' : 'rgba(191,71,75,1.0)'," + eol
    js += "    'Br' : 'rgba(154,32,24,1.0)'," + eol
    js += "    'Kr' : 'rgba(164,162,175,1.0)'," + eol
    js += "    'Rb' : 'rgba(122,119,110,1.0)'," + eol
    js += "    'Sr' : 'rgba(217,206,160,1.0)'," + eol
    js += "    'Y' : 'rgba(153,155,154,1.0)'," + eol
    js += "    'Zr' : 'rgba(153,143,133,1.0)'," + eol
    js += "    'Nb' : 'rgba(98,91,138,1.0)'," + eol
    js += "    'Mo' : 'rgba(93,88,85,1.0)'," + eol
    js += "    'Tc' : 'rgba(131,120,116,1.0)'," + eol
    js += "    'Ru' : 'rgba(153,147,149,1.0)'," + eol
    js += "    'Rh' : 'rgba(156,143,135,1.0)'," + eol
    js += "    'Pd' : 'rgba(162,161,157,1.0)'," + eol
    js += "    'Ag' : 'rgba(202,178,214,1.0)'," + eol
    js += "    'Cd' : 'rgba(106,106,104,1.0)'," + eol
    js += "    'In' : 'rgba(106,61,154,1.0)'," + eol
    js += "    'Sn' : 'rgba(126,120,94,1.0)'," + eol
    js += "    'Sb' : 'rgba(0,0,191,1.0)'," + eol
    js += "    'Te' : 'rgba(150,155,158,1.0)'," + eol
    js += "    'I' : 'rgba(95,98,105,1.0)'," + eol
    js += "    'Xe' : 'rgba(0,0,255,1.0)'," + eol
    js += "    'Cs' : 'rgba(167,170,175,1.0)'," + eol
    js += "    'Ba' : 'rgba(62,71,86,1.0)'," + eol
    js += "    'La' : 'rgba(196,184,172,1.0)'," + eol
    js += "    'Ce' : 'rgba(110,101,94,1.0)'," + eol
    js += "    'Pr' : 'rgba(96,91,97,1.0)'," + eol
    js += "    'Nd' : 'rgba(156,154,155,1.0)'," + eol
    js += "    'Pm' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Sm' : 'rgba(136,117,100,1.0)'," + eol
    js += "    'Eu' : 'rgba(217,213,204,1.0)'," + eol
    js += "    'Gd' : 'rgba(119,129,105,1.0)'," + eol
    js += "    'Tb' : 'rgba(236,241,235,1.0)'," + eol
    js += "    'Dy' : 'rgba(134,121,102,1.0)'," + eol
    js += "    'Ho' : 'rgba(131,123,121,1.0)'," + eol
    js += "    'Er' : 'rgba(177,182,175,1.0)'," + eol
    js += "    'Tm' : 'rgba(168,163,160,1.0)'," + eol
    js += "    'Yb' : 'rgba(0,255,0,1.0)'," + eol
    js += "    'Lu' : 'rgba(160,161,153,1.0)'," + eol
    js += "    'Hf' : 'rgba(171,188,178,1.0)'," + eol
    js += "    'Ta' : 'rgba(154,155,160,1.0)'," + eol
    js += "    'W' : 'rgba(60,0,255,1.0)'," + eol
    js += "    'Re' : 'rgba(123,123,121,1.0)'," + eol
    js += "    'Os' : 'rgba(185,196,200,1.0)'," + eol
    js += "    'Ir' : 'rgba(137,130,112,1.0)'," + eol
    js += "    'Pt' : 'rgba(210,211,205,1.0)'," + eol
    js += "    'Au' : 'rgba(203,152,53,1.0)'," + eol
    js += "    'Hg' : 'rgba(80,46,48,1.0)'," + eol
    js += "    'Tl' : 'rgba(143,141,142,1.0)'," + eol
    js += "    'Pb' : 'rgba(81,81,81,1.0)'," + eol
    js += "    'Bi' : 'rgba(114,106,103,1.0)'," + eol
    js += "    'Po' : 'rgba(139,153,164,1.0)'," + eol
    js += "    'At' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Rn' : 'rgba(71,132,0,1.0)'," + eol
    js += "    'Fr' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Ra' : 'rgba(156,152,125,1.0)'," + eol
    js += "    'Ac' : 'rgba(66,73,224,1.0)'," + eol
    js += "    'Th' : 'rgba(80,73,65,1.0)'," + eol
    js += "    'Pa' : 'rgba(154,147,92,1.0)'," + eol
    js += "    'U' : 'rgba(120,122,119,1.0)'," + eol
    js += "    'Np' : 'rgba(90,73,53,1.0)'," + eol
    js += "    'Pu' : 'rgba(200,200,200,1.0)'," + eol
    js += "    'Am' : 'rgba(117,80,28,1.0)'," + eol
    js += "    'Cm' : 'rgba(62,65,58,1.0)'," + eol
    js += "    'Bk' : 'rgba(208,208,208,1.0)'," + eol
    js += "    'Cf' : 'rgba(231,231,231,1.0)'," + eol
    js += "    'Es' : 'rgba(59,163,200,1.0)'," + eol
    js += "    'Fm' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Md' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'No' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Lr' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Rf' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Db' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Sg' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Bh' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Hs' : 'rgba(102,102,102,1.0)'," + eol
    js += "    'Mt' : 'rgba(102,102,102,1.0)'," + eol
    js += "  };" + eol
    js += "  if (molecule in jcpk) {" + eol
    js += "    return jcpk[molecule];" + eol
    js += (
        "  } else if (Number.isInteger(molecule) && molecule < Object.keys(jcpk).length) {"
        + eol
    )
    js += "    return jcpk[Object.keys(jcpk)[molecule]];" + eol
    js += "  } else {" + eol
    js += "    molecule = component.props.getAtomLabel(component, molecule);" + eol
    js += "    if (molecule in jcpk) {" + eol
    js += "      return jcpk[molecule];" + eol
    js += "    } else {" + eol
    js += "      return '#000';" + eol
    js += "    }" + eol
    js += "  }" + eol
    js += "}" + eol

    component.addPropVariable("getColor", {"type": "func", "defaultValue": js})
    return {"type": "propCall2", "calls": "getColor", "args": ["self", "[]"]}

def getAtomName(tp, component, *args, **kwargs):
    eol = "\n"
    js = ""
    js += "(component, molecule) => {" + eol
    js += "  var names = {" + eol
    js += "    'H' : 'Hydrogen'," + eol
    js += "    'He' : 'Helium'," + eol
    js += "    'Li' : 'Lithium'," + eol
    js += "    'Be' : 'Beryllium'," + eol
    js += "    'B' : 'Boron'," + eol
    js += "    'C' : 'Carbon'," + eol
    js += "    'N' : 'Nitrogen'," + eol
    js += "    'O' : 'Oxygen'," + eol
    js += "    'F' : 'Fluorine'," + eol
    js += "    'Ne' : 'Neon'," + eol
    js += "    'Na' : 'Sodium'," + eol
    js += "    'Mg' : 'Magnesium'," + eol
    js += "    'Al' : 'Aluminium'," + eol
    js += "    'Si' : 'Silicon'," + eol
    js += "    'P' : 'Phosphorus'," + eol
    js += "    'S' : 'Sulfur'," + eol
    js += "    'Cl' : 'Chlorine'," + eol
    js += "    'Ar' : 'Argon'," + eol
    js += "    'K' : 'Potassium'," + eol
    js += "    'Ca' : 'Calcium'," + eol
    js += "    'Sc' : 'Scandium'," + eol
    js += "    'Ti' : 'Titanium'," + eol
    js += "    'V' : 'Vanadium'," + eol
    js += "    'Cr' : 'Chromium'," + eol
    js += "    'Mn' : 'Manganese'," + eol
    js += "    'Fe' : 'Iron'," + eol
    js += "    'Co' : 'Cobalt'," + eol
    js += "    'Ni' : 'Nickel'," + eol
    js += "    'Cu' : 'Copper'," + eol
    js += "    'Zn' : 'Zinc'," + eol
    js += "    'Ga' : 'Gallium'," + eol
    js += "    'Ge' : 'Germanium'," + eol
    js += "    'As' : 'Arsenic'," + eol
    js += "    'Se' : 'Selenium'," + eol
    js += "    'Br' : 'Bromine'," + eol
    js += "    'Kr' : 'Krypton'," + eol
    js += "    'Rb' : 'Rubidium'," + eol
    js += "    'Sr' : 'Strontium'," + eol
    js += "    'Y' : 'Yttrium'," + eol
    js += "    'Zr' : 'Zirconium'," + eol
    js += "    'Nb' : 'Niobium'," + eol
    js += "    'Mo' : 'Molybdenum'," + eol
    js += "    'Tc' : 'Technetium'," + eol
    js += "    'Ru' : 'Ruthenium'," + eol
    js += "    'Rh' : 'Rhodium'," + eol
    js += "    'Pd' : 'Palladium'," + eol
    js += "    'Ag' : 'Silver'," + eol
    js += "    'Cd' : 'Cadmium'," + eol
    js += "    'In' : 'Indium'," + eol
    js += "    'Sn' : 'Tin'," + eol
    js += "    'Sb' : 'Antimony'," + eol
    js += "    'Te' : 'Tellurium'," + eol
    js += "    'I' : 'Iodine'," + eol
    js += "    'Xe' : 'Xenon'," + eol
    js += "    'Cs' : 'Caesium'," + eol
    js += "    'Ba' : 'Barium'," + eol
    js += "    'La' : 'Lanthanum'," + eol
    js += "    'Cerium' : 'Cerium'," + eol
    js += "    'Pr' : 'Praseodymium'," + eol
    js += "    'Nd' : 'Neodymium'," + eol
    js += "    'Pm' : 'Promethium'," + eol
    js += "    'Sm' : 'Samarium'," + eol
    js += "    'Eu' : 'Europium'," + eol
    js += "    'Gd' : 'Gadolinium'," + eol
    js += "    'Tb' : 'Terbium'," + eol
    js += "    'Dy' : 'Dysprosium'," + eol
    js += "    'Ho' : 'Holmium'," + eol
    js += "    'Er' : 'Erbium'," + eol
    js += "    'Tm' : 'Thulium'," + eol
    js += "    'Yb' : 'Ytterbium'," + eol
    js += "    'Lu' : 'Lutetium'," + eol
    js += "    'Hf' : 'Hafnium'," + eol
    js += "    'Ta' : 'Tantalum'," + eol
    js += "    'W' : 'Tungsten'," + eol
    js += "    'Re' : 'Rhenium'," + eol
    js += "    'Os' : 'Osmium'," + eol
    js += "    'Ir' : 'Iridium'," + eol
    js += "    'Pt' : 'Platinum'," + eol
    js += "    'Au' : 'Gold'," + eol
    js += "    'Hg' : 'Mercury'," + eol
    js += "    'Tl' : 'Thallium'," + eol
    js += "    'Pb' : 'Lead'," + eol
    js += "    'Bi' : 'Bismuth'," + eol
    js += "    'Po' : 'Polonium'," + eol
    js += "    'At' : 'Astatine'," + eol
    js += "    'Rn' : 'Radon'," + eol
    js += "    'Fr' : 'Francium'," + eol
    js += "    'Ra' : 'Radium'," + eol
    js += "    'Ac' : 'Actinium'," + eol
    js += "    'Th' : 'Thorium'," + eol
    js += "    'Pa' : 'Protactinium'," + eol
    js += "    'U' : 'Uranium'," + eol
    js += "    'Np' : 'Neptunium'," + eol
    js += "    'Pu' : 'Plutonium'," + eol
    js += "    'Am' : 'Americium'," + eol
    js += "    'Cm' : 'Curium'," + eol
    js += "    'Bk' : 'Berkelium'," + eol
    js += "    'Cf' : 'Californium'," + eol
    js += "    'Es' : 'Einsteinium'," + eol
    js += "    'Fm' : 'Fermium'," + eol
    js += "    'Md' : 'Mendelevium'," + eol
    js += "    'No' : 'Nobelium'," + eol
    js += "    'Lr' : 'Lawrencium'," + eol
    js += "    'Rf' : 'Rutherfordium'," + eol
    js += "    'Db' : 'Dubnium'," + eol
    js += "    'Sg' : 'Seaborgium'," + eol
    js += "    'Bh' : 'Bohrium'," + eol
    js += "    'Hs' : 'Hassium'," + eol
    js += "    'Mt' : 'Meitnerium'" + eol
    js += "  };" + eol
    js += "  if (molecule in names) {" + eol
    js += "    return names[molecule];" + eol
    js += (
        "  } else if (Number.isInteger(molecule) && molecule <= Object.keys(names).length) {"
        + eol
    )
    js += "    return names[Object.keys(names)[molecule-1]];" + eol
    js += "  } else {" + eol
    js += "    return '';" + eol
    js += "  }" + eol
    js += "}" + eol

    component.addPropVariable("getAtomName", {"type": "func", "defaultValue": js})
    return {"type": "propCall2", "calls": "getAtomName", "args": ["self", "[]"]}
