# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""CodeWeaver: Extensible MCP server for semantic code search.

As a convenience, we lazily export (almost) every type in CodeWeaver so you can easily make use of them.

**Important**: You should not take these exports to mean it's CodeWeaver's public API. We are in alpha and the API **will change** substantially, and sometimes without notice. Once we're stable, then we'll adopt a more routined approach to public APIs.

(are we exporting too much? Yes. We'll refine this over time as we better understand what users need. For now, enjoy the convenience of having everything available.)
"""

from __future__ import annotations

# Suppress pydantic deprecation warnings from third-party dependencies
# This must be at the very top before any imports
import contextlib
import warnings

from types import MappingProxyType
from typing import TYPE_CHECKING, Final


with contextlib.suppress(ImportError):
    # Google's `genai` package uses outdated pydantic features that trigger deprecation warnings with our newer pydantic version.
    from pydantic.warnings import PydanticDeprecatedSince212

    warnings.simplefilter("ignore", PydanticDeprecatedSince212)

from codeweaver.common.utils.lazy_importer import create_lazy_getattr


def get_version() -> str:
    """Get the current version of CodeWeaver.

    Because our version is dynamically generated during build/release, we try several methods to get it. If you downloaded CodeWeaver from PyPi, then the first will work, or the second if the file didn't get generated for some reason. If you're running from source, we try to get the version from git tags. If all else fails, we return "0.0.0".
    """
    try:
        from codeweaver._version import __version__
    except ImportError:
        try:
            import importlib.metadata

            __version__ = importlib.metadata.version("codeweaver")
        except importlib.metadata.PackageNotFoundError:
            try:
                import shutil
                import subprocess

                # Try to get version from git if available
                # Git commands work from any directory within a repo, so no need to specify cwd
                # The subprocess call is safe because we use the system to find the executable, not user input
                if git := shutil.which("git"):
                    git_describe = subprocess.run(  # noqa: S603
                        [git, "describe", "--tags", "--always", "--dirty"],
                        capture_output=True,
                        text=True,
                        check=False,
                    )
                    if git_describe.returncode == 0:
                        __version__ = git_describe.stdout.strip()
                    else:
                        __version__ = "0.0.0"
                else:
                    __version__ = "0.0.0"
            except Exception:
                __version__ = "0.0.0"
    return __version__


__version__: Final[str] = get_version()


if TYPE_CHECKING:
    from codeweaver.agent_api import find_code
    from codeweaver.cli import CLIErrorHandler, StatusDisplay
    from codeweaver.common import (
        CODEWEAVER_PREFIX,
        CallHookTimingDict,
        FileStatistics,
        HttpRequestsDict,
        Identifier,
        LazyImport,
        McpComponentRequests,
        McpComponentTimingDict,
        McpOperationRequests,
        McpTimingDict,
        ResourceUri,
        SessionStatistics,
        TimingStatistics,
        TimingStatisticsDict,
        TokenCategory,
        TokenCounter,
        ToolOrPromptName,
    )
    from codeweaver.config import (
        AVAILABLE_MIDDLEWARE,
        AgentModelSettings,
        AgentProviderSettings,
        AWSProviderSettings,
        AzureCohereProviderSettings,
        AzureOpenAIProviderSettings,
        ChunkerSettings,
        ChunkerSettingsDict,
        CodeWeaverMCPConfig,
        CodeWeaverMCPConfigDict,
        CodeWeaverSettings,
        CodeWeaverSettingsDict,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        CustomDelimiter,
        DataProviderSettings,
        EmbeddingModelSettings,
        EmbeddingProviderSettings,
        ErrorHandlingMiddlewareSettings,
        FastembedGPUProviderSettings,
        FastMcpHttpRunArgs,
        FastMcpHttpServerSettings,
        FastMcpServerSettingsDict,
        FastMcpStdioServerSettings,
        FilterID,
        FiltersDict,
        FormatterID,
        FormattersDict,
        HandlerID,
        HandlersDict,
        IndexerSettings,
        IndexerSettingsDict,
        LoggerName,
        LoggersDict,
        LoggingConfigDict,
        LoggingMiddlewareSettings,
        LoggingSettings,
        MCPConfig,
        MCPConfigDict,
        MiddlewareOptions,
        ModelString,
        ProviderSettingsDict,
        ProviderSettingsView,
        ProviderSpecificSettings,
        RateLimitingMiddlewareSettings,
        RerankingModelSettings,
        RerankingProviderSettings,
        RetryMiddlewareSettings,
        RignoreSettings,
        SerializableLoggingFilter,
        SparseEmbeddingModelSettings,
        StdioCodeWeaverConfig,
        StdioCodeWeaverConfigDict,
        TelemetrySettings,
        UvicornServerSettings,
        UvicornServerSettingsDict,
        VectorStoreProviderSettings,
        get_settings_map,
    )
    from codeweaver.core import (
        BASEDMODEL_CONFIG,
        DATACLASS_CONFIG,
        FROZEN_BASEDMODEL_CONFIG,
        UNSET,
        AnonymityConversion,
        BaseDataclassEnum,
        BasedModel,
        BaseEnum,
        BaseEnumData,
        BlakeHashKey,
        BlakeKey,
        BlakeStore,
        CategoryName,
        CategoryNameT,
        ChunkKind,
        ChunkSequence,
        ChunkSource,
        CodeChunk,
        CodeChunkDict,
        ConfigLanguage,
        ConfigNamePair,
        DataclassSerializationMixin,
        DeserializationKwargs,
        DevToolName,
        DevToolNameT,
        DictView,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        DiscoveredFile,
        EmbeddingModelName,
        EmbeddingModelNameT,
        EnvVarInfo,
        ExtKind,
        ExtLangPair,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        LanguageConfigFile,
        LanguageName,
        LanguageNameT,
        LiteralStringT,
        LlmToolName,
        LlmToolNameT,
        Metadata,
        ModelName,
        ModelNameT,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        RootedRoot,
        SemanticMetadata,
        SemanticSearchLanguage,
        Sentinel,
        SentinelName,
        SentinelNameT,
        SerializationKwargs,
        SerializedCodeChunk,
        SerializedStrOnlyCodeChunk,
        Span,
        SpanGroup,
        SpanTuple,
        StoreDict,
        StructuredDataInput,
        ThingName,
        ThingNameT,
        Unset,
        UUID7Hex,
        UUID7HexT,
        UUIDStore,
        make_blake_store,
        make_uuid_store,
    )
    from codeweaver.engine import (
        AnyVariants,
        ArbitraryFilter,
        ASTDepthExceededError,
        BinaryFileError,
        Boundary,
        ChunkerSelector,
        ChunkGovernor,
        ChunkingError,
        ChunkingService,
        ChunkingTimeoutError,
        ChunkLimitExceededError,
        CodeFilter,
        Condition,
        ConfigFilter,
        DatetimeRange,
        DefaultFilter,
        Delimiter,
        DelimiterChunker,
        DelimiterDict,
        DelimiterKind,
        DelimiterMatch,
        DelimiterPattern,
        DocsFilter,
        Entry,
        ExtendedPointId,
        ExtensionFilter,
        FieldCondition,
        FileWatcher,
        Filter,
        FilterableField,
        GeoBoundingBox,
        GeoLineString,
        GeoPoint,
        GeoPolygon,
        GeoRadius,
        GracefulChunker,
        HasIdCondition,
        HasVectorCondition,
        IgnoreFilter,
        Indexer,
        IsEmptyCondition,
        IsNullCondition,
        LanguageFamily,
        LineStrategy,
        Match,
        MatchAny,
        MatchExcept,
        MatchPhrase,
        MatchText,
        MatchValue,
        MinShould,
        Nested,
        NestedCondition,
        OversizedChunkError,
        ParseError,
        PayloadField,
        PayloadMetadata,
        PayloadSchemaType,
        Range,
        ResourceGovernor,
        SemanticChunker,
        SourceIdRegistry,
        ValuesCount,
        ValueVariants,
    )
    from codeweaver.exceptions import (
        CodeWeaverError,
        CollectionNotFoundError,
        ConfigurationError,
        DimensionMismatchError,
        IndexingError,
        InitializationError,
        MissingValueError,
        ModelSwitchError,
        PersistenceError,
        ProviderError,
        ProviderSwitchError,
        QueryError,
        RerankingProviderError,
        ValidationError,
    )
    from codeweaver.mcp import (
        TOOL_DEFINITIONS,
        CwMcpHttpState,
        ErrorHandlingMiddleware,
        LoggingMiddleware,
        McpMiddleware,
        RateLimitingMiddleware,
        ResponseCachingMiddleware,
        RetryMiddleware,
        StatisticsMiddleware,
        StructuredLoggingMiddleware,
        ToolAnnotationsDict,
        ToolRegistrationDict,
        create_http_server,
        create_stdio_server,
        find_code_tool,
        find_code_tool_definition,
        get_bulk_tool,
        register_tool,
    )
    from codeweaver.providers import (
        CLIENT_MAP,
        PROVIDER_CAPABILITIES,
        VECTOR_PROVIDER_CAPABILITIES,
        AbstractToolset,
        AgentModel,
        AgentProfile,
        AgentProfileSpec,
        AgentProvider,
        AvailableOptimizations,
        BedrockEmbeddingProvider,
        BedrockRerankingProvider,
        ChunkEmbeddings,
        CohereEmbeddingProvider,
        CohereRerankingProvider,
        CollectionMetadata,
        CombinedToolset,
        DownloadedItem,
        EmbeddingBatchInfo,
        EmbeddingModelCapabilities,
        EmbeddingProvider,
        ExternalToolset,
        FastEmbedEmbeddingProvider,
        FastEmbedRerankingProvider,
        FastEmbedSparseProvider,
        FilteredToolset,
        FunctionToolset,
        GoogleEmbeddingProvider,
        HuggingFaceEmbeddingProvider,
        HybridVectorPayload,
        LiteralProvider,
        LiteralProviderKind,
        MemoryVectorStoreProvider,
        MistralEmbeddingProvider,
        OpenAIEmbeddingBase,
        OptimizationDecisions,
        PrefixedToolset,
        PreparedToolset,
        Provider,
        ProviderEnvVarInfo,
        ProviderEnvVars,
        ProviderKind,
        QdrantVectorStoreProvider,
        QueryType,
        RawEmbeddingVectors,
        RenamedToolset,
        RerankingProvider,
        RerankingResult,
        SentenceTransformersEmbeddingProvider,
        SentenceTransformersRerankingProvider,
        SentenceTransformersSparseProvider,
        SparseEmbedding,
        SparseEmbeddingModelCapabilities,
        StoredEmbeddingVectors,
        ToolsetTool,
        VectorStoreProvider,
        VoyageEmbeddingProvider,
        VoyageRerankingProvider,
        WrapperToolset,
    )
    from codeweaver.semantic import (
        AgentTask,
        AstThing,
        Category,
        ClassificationMethod,
        CompositeThing,
        ConnectionClass,
        ConnectionConstraint,
        CustomLang,
        DirectConnection,
        EvidenceKind,
        FileThing,
        Grammar,
        GrammarBasedClassifier,
        GrammarClassificationResult,
        ImportanceScores,
        MetaVar,
        NthChild,
        Pattern,
        Position,
        PositionalConnections,
        PosRule,
        RangeRule,
        Relation,
        Rule,
        RuleWithoutNot,
        SemanticClass,
        SemanticScorer,
        ThingClass,
        ThingKind,
        ThingRegistry,
        ThingType,
        Token,
        TokenPurpose,
        get_all_grammars,
    )
    from codeweaver.server import (
        CodeWeaverState,
        EmbeddingProviderServiceInfo,
        HealthResponse,
        HealthService,
        IndexingInfo,
        IndexingProgressInfo,
        ManagementServer,
        RerankingServiceInfo,
        ServicesInfo,
        SparseEmbeddingServiceInfo,
        StatisticsInfo,
        VectorStoreServiceInfo,
    )
    from codeweaver.tokenizers import TiktokenTokenizer, Tokenizer, Tokenizers


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ASTDepthExceededError": (__spec__.parent, "engine"),
    "AVAILABLE_MIDDLEWARE": (__spec__.parent, "config"),
    "AWSProviderSettings": (__spec__.parent, "config"),
    "AbstractToolset": (__spec__.parent, "providers"),
    "AgentModel": (__spec__.parent, "providers"),
    "AgentModelSettings": (__spec__.parent, "config"),
    "AgentProfile": (__spec__.parent, "providers"),
    "AgentProfileSpec": (__spec__.parent, "providers"),
    "AgentProvider": (__spec__.parent, "providers"),
    "AgentProviderSettings": (__spec__.parent, "config"),
    "AgentTask": (__spec__.parent, "semantic"),
    "AnonymityConversion": (__spec__.parent, "core"),
    "AnyVariants": (__spec__.parent, "engine"),
    "ArbitraryFilter": (__spec__.parent, "engine"),
    "AstThing": (__spec__.parent, "semantic"),
    "AvailableOptimizations": (__spec__.parent, "providers"),
    "AzureCohereProviderSettings": (__spec__.parent, "config"),
    "AzureOpenAIProviderSettings": (__spec__.parent, "config"),
    "BASEDMODEL_CONFIG": (__spec__.parent, "core"),
    "BaseDataclassEnum": (__spec__.parent, "core"),
    "BaseEnum": (__spec__.parent, "core"),
    "BaseEnumData": (__spec__.parent, "core"),
    "BasedModel": (__spec__.parent, "core"),
    "BedrockEmbeddingProvider": (__spec__.parent, "providers"),
    "BedrockRerankingProvider": (__spec__.parent, "providers"),
    "BinaryFileError": (__spec__.parent, "engine"),
    "BlakeHashKey": (__spec__.parent, "core"),
    "BlakeKey": (__spec__.parent, "core"),
    "BlakeStore": (__spec__.parent, "core"),
    "Boundary": (__spec__.parent, "engine"),
    "CLIENT_MAP": (__spec__.parent, "providers"),
    "CLIErrorHandler": (__spec__.parent, "cli"),
    "CODEWEAVER_PREFIX": (__spec__.parent, "common"),
    "CallHookTimingDict": (__spec__.parent, "common"),
    "Category": (__spec__.parent, "semantic"),
    "CategoryName": (__spec__.parent, "core"),
    "CategoryNameT": (__spec__.parent, "core"),
    "ChunkEmbeddings": (__spec__.parent, "providers"),
    "ChunkGovernor": (__spec__.parent, "engine"),
    "ChunkKind": (__spec__.parent, "core"),
    "ChunkLimitExceededError": (__spec__.parent, "engine"),
    "ChunkSequence": (__spec__.parent, "core"),
    "ChunkSource": (__spec__.parent, "core"),
    "ChunkerSelector": (__spec__.parent, "engine"),
    "ChunkerSettings": (__spec__.parent, "config"),
    "ChunkerSettingsDict": (__spec__.parent, "config"),
    "ChunkingError": (__spec__.parent, "engine"),
    "ChunkingService": (__spec__.parent, "engine"),
    "ChunkingTimeoutError": (__spec__.parent, "engine"),
    "ClassificationMethod": (__spec__.parent, "semantic"),
    "CodeChunk": (__spec__.parent, "core"),
    "CodeChunkDict": (__spec__.parent, "core"),
    "CodeFilter": (__spec__.parent, "engine"),
    "CodeWeaverError": (__spec__.parent, "exceptions"),
    "CodeWeaverMCPConfig": (__spec__.parent, "config"),
    "CodeWeaverMCPConfigDict": (__spec__.parent, "config"),
    "CodeWeaverSettings": (__spec__.parent, "config"),
    "CodeWeaverSettingsDict": (__spec__.parent, "config"),
    "CodeWeaverState": (__spec__.parent, "server"),
    "CohereEmbeddingProvider": (__spec__.parent, "providers"),
    "CohereRerankingProvider": (__spec__.parent, "providers"),
    "CollectionMetadata": (__spec__.parent, "providers"),
    "CollectionNotFoundError": (__spec__.parent, "exceptions"),
    "CombinedToolset": (__spec__.parent, "providers"),
    "CompositeThing": (__spec__.parent, "semantic"),
    "Condition": (__spec__.parent, "engine"),
    "ConfigFilter": (__spec__.parent, "engine"),
    "ConfigLanguage": (__spec__.parent, "core"),
    "ConfigNamePair": (__spec__.parent, "core"),
    "ConfigurationError": (__spec__.parent, "exceptions"),
    "ConnectionClass": (__spec__.parent, "semantic"),
    "ConnectionConfiguration": (__spec__.parent, "config"),
    "ConnectionConstraint": (__spec__.parent, "semantic"),
    "ConnectionRateLimitConfig": (__spec__.parent, "config"),
    "CustomDelimiter": (__spec__.parent, "config"),
    "CustomLang": (__spec__.parent, "semantic"),
    "CustomLanguage": (__spec__.parent, "config"),
    "CwMcpHttpState": (__spec__.parent, "mcp"),
    "DATACLASS_CONFIG": (__spec__.parent, "core"),
    "DataProviderSettings": (__spec__.parent, "config"),
    "DataclassSerializationMixin": (__spec__.parent, "core"),
    "DatetimeRange": (__spec__.parent, "engine"),
    "DefaultFilter": (__spec__.parent, "engine"),
    "Delimiter": (__spec__.parent, "engine"),
    "DelimiterChunker": (__spec__.parent, "engine"),
    "DelimiterDict": (__spec__.parent, "engine"),
    "DelimiterKind": (__spec__.parent, "engine"),
    "DelimiterMatch": (__spec__.parent, "engine"),
    "DelimiterPattern": (__spec__.parent, "engine"),
    "DeserializationKwargs": (__spec__.parent, "core"),
    "DevToolName": (__spec__.parent, "core"),
    "DevToolNameT": (__spec__.parent, "core"),
    "DictView": (__spec__.parent, "core"),
    "DimensionMismatchError": (__spec__.parent, "exceptions"),
    "DirectConnection": (__spec__.parent, "semantic"),
    "DirectoryName": (__spec__.parent, "core"),
    "DirectoryNameT": (__spec__.parent, "core"),
    "DirectoryPath": (__spec__.parent, "core"),
    "DirectoryPathT": (__spec__.parent, "core"),
    "DiscoveredFile": (__spec__.parent, "core"),
    "DocsFilter": (__spec__.parent, "engine"),
    "DownloadedItem": (__spec__.parent, "providers"),
    "EmbeddingBatchInfo": (__spec__.parent, "providers"),
    "EmbeddingModelCapabilities": (__spec__.parent, "providers"),
    "EmbeddingModelName": (__spec__.parent, "core"),
    "EmbeddingModelNameT": (__spec__.parent, "core"),
    "EmbeddingModelSettings": (__spec__.parent, "config"),
    "EmbeddingProvider": (__spec__.parent, "providers"),
    "EmbeddingProviderServiceInfo": (__spec__.parent, "server"),
    "EmbeddingProviderSettings": (__spec__.parent, "config"),
    "Entry": (__spec__.parent, "engine"),
    "EnvVarInfo": (__spec__.parent, "core"),
    "ErrorHandlingMiddleware": (__spec__.parent, "mcp"),
    "ErrorHandlingMiddlewareSettings": (__spec__.parent, "config"),
    "EvidenceKind": (__spec__.parent, "semantic"),
    "ExtKind": (__spec__.parent, "core"),
    "ExtLangPair": (__spec__.parent, "core"),
    "ExtendedPointId": (__spec__.parent, "engine"),
    "ExtensionFilter": (__spec__.parent, "engine"),
    "ExternalToolset": (__spec__.parent, "providers"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "core"),
    "FastEmbedEmbeddingProvider": (__spec__.parent, "providers"),
    "FastEmbedRerankingProvider": (__spec__.parent, "providers"),
    "FastEmbedSparseProvider": (__spec__.parent, "providers"),
    "FastMcpHttpRunArgs": (__spec__.parent, "config"),
    "FastMcpHttpServerSettings": (__spec__.parent, "config"),
    "FastMcpServerSettingsDict": (__spec__.parent, "config"),
    "FastMcpStdioServerSettings": (__spec__.parent, "config"),
    "FastembedGPUProviderSettings": (__spec__.parent, "config"),
    "FieldCondition": (__spec__.parent, "engine"),
    "FileExt": (__spec__.parent, "core"),
    "FileExtensionT": (__spec__.parent, "core"),
    "FileGlob": (__spec__.parent, "core"),
    "FileGlobT": (__spec__.parent, "core"),
    "FileName": (__spec__.parent, "core"),
    "FileNameT": (__spec__.parent, "core"),
    "FilePath": (__spec__.parent, "core"),
    "FilePathT": (__spec__.parent, "core"),
    "FileStatistics": (__spec__.parent, "common"),
    "FileThing": (__spec__.parent, "semantic"),
    "FileWatcher": (__spec__.parent, "engine"),
    "Filter": (__spec__.parent, "engine"),
    "FilterID": (__spec__.parent, "config"),
    "FilterableField": (__spec__.parent, "engine"),
    "FilteredKey": (__spec__.parent, "core"),
    "FilteredKeyT": (__spec__.parent, "core"),
    "FilteredToolset": (__spec__.parent, "providers"),
    "FiltersDict": (__spec__.parent, "config"),
    "FormatterID": (__spec__.parent, "config"),
    "FormattersDict": (__spec__.parent, "config"),
    "FunctionToolset": (__spec__.parent, "providers"),
    "GeoBoundingBox": (__spec__.parent, "engine"),
    "GeoLineString": (__spec__.parent, "engine"),
    "GeoPoint": (__spec__.parent, "engine"),
    "GeoPolygon": (__spec__.parent, "engine"),
    "GeoRadius": (__spec__.parent, "engine"),
    "GoogleEmbeddingProvider": (__spec__.parent, "providers"),
    "GracefulChunker": (__spec__.parent, "engine"),
    "Grammar": (__spec__.parent, "semantic"),
    "GrammarBasedClassifier": (__spec__.parent, "semantic"),
    "GrammarClassificationResult": (__spec__.parent, "semantic"),
    "HandlerID": (__spec__.parent, "config"),
    "HandlersDict": (__spec__.parent, "config"),
    "HasIdCondition": (__spec__.parent, "engine"),
    "HasVectorCondition": (__spec__.parent, "engine"),
    "HealthResponse": (__spec__.parent, "server"),
    "HealthService": (__spec__.parent, "server"),
    "HttpRequestsDict": (__spec__.parent, "common"),
    "HuggingFaceEmbeddingProvider": (__spec__.parent, "providers"),
    "HybridVectorPayload": (__spec__.parent, "providers"),
    "Identifier": (__spec__.parent, "common"),
    "IgnoreFilter": (__spec__.parent, "engine"),
    "ImportanceScores": (__spec__.parent, "semantic"),
    "Indexer": (__spec__.parent, "engine"),
    "IndexerSettings": (__spec__.parent, "config"),
    "IndexerSettingsDict": (__spec__.parent, "config"),
    "IndexingError": (__spec__.parent, "exceptions"),
    "IndexingInfo": (__spec__.parent, "server"),
    "IndexingProgressInfo": (__spec__.parent, "server"),
    "InitializationError": (__spec__.parent, "exceptions"),
    "IsEmptyCondition": (__spec__.parent, "engine"),
    "IsNullCondition": (__spec__.parent, "engine"),
    "LanguageConfigFile": (__spec__.parent, "core"),
    "LanguageFamily": (__spec__.parent, "engine"),
    "LanguageName": (__spec__.parent, "core"),
    "LanguageNameT": (__spec__.parent, "core"),
    "LazyImport": (__spec__.parent, "common"),
    "LineStrategy": (__spec__.parent, "engine"),
    "LiteralProvider": (__spec__.parent, "providers"),
    "LiteralProviderKind": (__spec__.parent, "providers"),
    "LiteralStringT": (__spec__.parent, "core"),
    "LlmToolName": (__spec__.parent, "core"),
    "LlmToolNameT": (__spec__.parent, "core"),
    "LoggerName": (__spec__.parent, "config"),
    "LoggersDict": (__spec__.parent, "config"),
    "LoggingConfigDict": (__spec__.parent, "config"),
    "LoggingMiddleware": (__spec__.parent, "mcp"),
    "LoggingMiddlewareSettings": (__spec__.parent, "config"),
    "LoggingSettings": (__spec__.parent, "config"),
    "MCPConfig": (__spec__.parent, "config"),
    "MCPConfigDict": (__spec__.parent, "config"),
    "ManagementServer": (__spec__.parent, "server"),
    "Match": (__spec__.parent, "engine"),
    "MatchAny": (__spec__.parent, "engine"),
    "MatchExcept": (__spec__.parent, "engine"),
    "MatchPhrase": (__spec__.parent, "engine"),
    "MatchText": (__spec__.parent, "engine"),
    "MatchValue": (__spec__.parent, "engine"),
    "McpComponentRequests": (__spec__.parent, "common"),
    "McpComponentTimingDict": (__spec__.parent, "common"),
    "McpMiddleware": (__spec__.parent, "mcp"),
    "McpOperationRequests": (__spec__.parent, "common"),
    "McpTimingDict": (__spec__.parent, "common"),
    "MemoryVectorStoreProvider": (__spec__.parent, "providers"),
    "MetaVar": (__spec__.parent, "semantic"),
    "Metadata": (__spec__.parent, "core"),
    "MiddlewareOptions": (__spec__.parent, "config"),
    "MinShould": (__spec__.parent, "engine"),
    "MissingValueError": (__spec__.parent, "exceptions"),
    "MistralEmbeddingProvider": (__spec__.parent, "providers"),
    "ModelName": (__spec__.parent, "core"),
    "ModelNameT": (__spec__.parent, "core"),
    "ModelString": (__spec__.parent, "config"),
    "ModelSwitchError": (__spec__.parent, "exceptions"),
    "Nested": (__spec__.parent, "engine"),
    "NestedCondition": (__spec__.parent, "engine"),
    "NthChild": (__spec__.parent, "semantic"),
    "OpenAIEmbeddingBase": (__spec__.parent, "providers"),
    "OptimizationDecisions": (__spec__.parent, "providers"),
    "OversizedChunkError": (__spec__.parent, "engine"),
    "PROVIDER_CAPABILITIES": (__spec__.parent, "providers"),
    "ParseError": (__spec__.parent, "engine"),
    "Pattern": (__spec__.parent, "semantic"),
    "PayloadField": (__spec__.parent, "engine"),
    "PayloadMetadata": (__spec__.parent, "engine"),
    "PayloadSchemaType": (__spec__.parent, "engine"),
    "PersistenceError": (__spec__.parent, "exceptions"),
    "PosRule": (__spec__.parent, "semantic"),
    "Position": (__spec__.parent, "semantic"),
    "PositionalConnections": (__spec__.parent, "semantic"),
    "PrefixedToolset": (__spec__.parent, "providers"),
    "PreparedToolset": (__spec__.parent, "providers"),
    "Provider": (__spec__.parent, "providers"),
    "ProviderEnvVarInfo": (__spec__.parent, "providers"),
    "ProviderEnvVars": (__spec__.parent, "providers"),
    "ProviderError": (__spec__.parent, "exceptions"),
    "ProviderKind": (__spec__.parent, "providers"),
    "ProviderSettingsDict": (__spec__.parent, "config"),
    "ProviderSettingsView": (__spec__.parent, "config"),
    "ProviderSpecificSettings": (__spec__.parent, "config"),
    "ProviderSwitchError": (__spec__.parent, "exceptions"),
    "QdrantVectorStoreProvider": (__spec__.parent, "providers"),
    "QueryError": (__spec__.parent, "exceptions"),
    "QueryType": (__spec__.parent, "providers"),
    "Range": (__spec__.parent, "engine"),
    "RangeRule": (__spec__.parent, "semantic"),
    "RateLimitingMiddleware": (__spec__.parent, "mcp"),
    "RateLimitingMiddlewareSettings": (__spec__.parent, "config"),
    "RawEmbeddingVectors": (__spec__.parent, "providers"),
    "Relation": (__spec__.parent, "semantic"),
    "RenamedToolset": (__spec__.parent, "providers"),
    "RerankingModelName": (__spec__.parent, "core"),
    "RerankingModelNameT": (__spec__.parent, "core"),
    "RerankingModelSettings": (__spec__.parent, "config"),
    "RerankingProvider": (__spec__.parent, "providers"),
    "RerankingProviderError": (__spec__.parent, "exceptions"),
    "RerankingProviderSettings": (__spec__.parent, "config"),
    "RerankingResult": (__spec__.parent, "providers"),
    "RerankingServiceInfo": (__spec__.parent, "server"),
    "ResourceGovernor": (__spec__.parent, "engine"),
    "ResourceUri": (__spec__.parent, "common"),
    "ResponseCachingMiddleware": (__spec__.parent, "mcp"),
    "RetryMiddleware": (__spec__.parent, "mcp"),
    "RetryMiddlewareSettings": (__spec__.parent, "config"),
    "RignoreSettings": (__spec__.parent, "config"),
    "Role": (__spec__.parent, "core"),
    "RoleT": (__spec__.parent, "core"),
    "RootedRoot": (__spec__.parent, "core"),
    "Rule": (__spec__.parent, "semantic"),
    "RuleWithoutNot": (__spec__.parent, "semantic"),
    "SemanticChunker": (__spec__.parent, "engine"),
    "SemanticClass": (__spec__.parent, "semantic"),
    "SemanticMetadata": (__spec__.parent, "core"),
    "SemanticScorer": (__spec__.parent, "semantic"),
    "SemanticSearchLanguage": (__spec__.parent, "core"),
    "SentenceTransformersEmbeddingProvider": (__spec__.parent, "providers"),
    "SentenceTransformersRerankingProvider": (__spec__.parent, "providers"),
    "SentenceTransformersSparseProvider": (__spec__.parent, "providers"),
    "Sentinel": (__spec__.parent, "core"),
    "SentinelName": (__spec__.parent, "core"),
    "SentinelNameT": (__spec__.parent, "core"),
    "SerializableLoggingFilter": (__spec__.parent, "config"),
    "SerializationKwargs": (__spec__.parent, "core"),
    "SerializedCodeChunk": (__spec__.parent, "core"),
    "SerializedStrOnlyCodeChunk": (__spec__.parent, "core"),
    "ServicesInfo": (__spec__.parent, "server"),
    "SessionStatistics": (__spec__.parent, "common"),
    "SourceIdRegistry": (__spec__.parent, "engine"),
    "Span": (__spec__.parent, "core"),
    "SpanGroup": (__spec__.parent, "core"),
    "SpanTuple": (__spec__.parent, "core"),
    "SparseEmbedding": (__spec__.parent, "providers"),
    "SparseEmbeddingModelCapabilities": (__spec__.parent, "providers"),
    "SparseEmbeddingModelSettings": (__spec__.parent, "config"),
    "SparseEmbeddingServiceInfo": (__spec__.parent, "server"),
    "StatisticsInfo": (__spec__.parent, "server"),
    "StatisticsMiddleware": (__spec__.parent, "mcp"),
    "StatusDisplay": (__spec__.parent, "cli"),
    "StdioCodeWeaverConfig": (__spec__.parent, "config"),
    "StdioCodeWeaverConfigDict": (__spec__.parent, "config"),
    "StoreDict": (__spec__.parent, "core"),
    "StoredEmbeddingVectors": (__spec__.parent, "providers"),
    "StructuredDataInput": (__spec__.parent, "core"),
    "StructuredLoggingMiddleware": (__spec__.parent, "mcp"),
    "TOOL_DEFINITIONS": (__spec__.parent, "mcp"),
    "TelemetrySettings": (__spec__.parent, "config"),
    "ThingClass": (__spec__.parent, "semantic"),
    "ThingKind": (__spec__.parent, "semantic"),
    "ThingName": (__spec__.parent, "core"),
    "ThingNameT": (__spec__.parent, "core"),
    "ThingRegistry": (__spec__.parent, "semantic"),
    "ThingType": (__spec__.parent, "semantic"),
    "TiktokenTokenizer": (__spec__.parent, "tokenizers"),
    "TimingStatistics": (__spec__.parent, "common"),
    "TimingStatisticsDict": (__spec__.parent, "common"),
    "Token": (__spec__.parent, "semantic"),
    "TokenCategory": (__spec__.parent, "common"),
    "TokenCounter": (__spec__.parent, "common"),
    "TokenPurpose": (__spec__.parent, "semantic"),
    "Tokenizer": (__spec__.parent, "tokenizers"),
    "Tokenizers": (__spec__.parent, "tokenizers"),
    "ToolAnnotationsDict": (__spec__.parent, "mcp"),
    "ToolOrPromptName": (__spec__.parent, "common"),
    "ToolRegistrationDict": (__spec__.parent, "mcp"),
    "ToolsetTool": (__spec__.parent, "providers"),
    "UNSET": (__spec__.parent, "core"),
    "UUID7Hex": (__spec__.parent, "core"),
    "UUID7HexT": (__spec__.parent, "core"),
    "UUIDStore": (__spec__.parent, "core"),
    "Unset": (__spec__.parent, "core"),
    "UvicornServerSettings": (__spec__.parent, "config"),
    "UvicornServerSettingsDict": (__spec__.parent, "config"),
    "VECTOR_PROVIDER_CAPABILITIES": (__spec__.parent, "providers"),
    "ValidationError": (__spec__.parent, "exceptions"),
    "ValueVariants": (__spec__.parent, "engine"),
    "ValuesCount": (__spec__.parent, "engine"),
    "VectorStoreProvider": (__spec__.parent, "providers"),
    "VectorStoreProviderSettings": (__spec__.parent, "config"),
    "VectorStoreServiceInfo": (__spec__.parent, "server"),
    "VoyageEmbeddingProvider": (__spec__.parent, "providers"),
    "VoyageRerankingProvider": (__spec__.parent, "providers"),
    "WrapperToolset": (__spec__.parent, "providers"),
    "create_http_server": (__spec__.parent, "mcp"),
    "create_stdio_server": (__spec__.parent, "mcp"),
    "find_code": (__spec__.parent, "agent_api"),
    "find_code_tool": (__spec__.parent, "mcp"),
    "find_code_tool_definition": (__spec__.parent, "mcp"),
    "get_all_grammars": (__spec__.parent, "semantic"),
    "get_bulk_tool": (__spec__.parent, "mcp"),
    "get_settings_map": (__spec__.parent, "config"),
    "make_blake_store": (__spec__.parent, "core"),
    "make_uuid_store": (__spec__.parent, "core"),
    "register_tool": (__spec__.parent, "mcp"),
})

__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "AVAILABLE_MIDDLEWARE",
    "BASEDMODEL_CONFIG",
    "CLIENT_MAP",
    "CODEWEAVER_PREFIX",
    "DATACLASS_CONFIG",
    "FROZEN_BASEDMODEL_CONFIG",
    "PROVIDER_CAPABILITIES",
    "TOOL_DEFINITIONS",
    "UNSET",
    "VECTOR_PROVIDER_CAPABILITIES",
    "ASTDepthExceededError",
    "AWSProviderSettings",
    "AbstractToolset",
    "AgentModel",
    "AgentModelSettings",
    "AgentModelSettings",
    "AgentProfile",
    "AgentProfileSpec",
    "AgentProvider",
    "AgentProviderSettings",
    "AgentTask",
    "AnonymityConversion",
    "AnyVariants",
    "ArbitraryFilter",
    "AstThing",
    "AvailableOptimizations",
    "AzureCohereProviderSettings",
    "AzureOpenAIProviderSettings",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BasedModel",
    "BedrockEmbeddingProvider",
    "BedrockRerankingProvider",
    "BinaryFileError",
    "BlakeHashKey",
    "BlakeKey",
    "BlakeStore",
    "Boundary",
    "CLIErrorHandler",
    "CallHookTimingDict",
    "Category",
    "CategoryName",
    "CategoryNameT",
    "ChunkEmbeddings",
    "ChunkGovernor",
    "ChunkKind",
    "ChunkLimitExceededError",
    "ChunkSequence",
    "ChunkSource",
    "ChunkerSelector",
    "ChunkerSettings",
    "ChunkerSettingsDict",
    "ChunkingError",
    "ChunkingService",
    "ChunkingTimeoutError",
    "ClassificationMethod",
    "CodeChunk",
    "CodeChunkDict",
    "CodeFilter",
    "CodeWeaverError",
    "CodeWeaverMCPConfig",
    "CodeWeaverMCPConfigDict",
    "CodeWeaverSettings",
    "CodeWeaverSettingsDict",
    "CodeWeaverState",
    "CohereEmbeddingProvider",
    "CohereRerankingProvider",
    "CollectionMetadata",
    "CollectionNotFoundError",
    "CombinedToolset",
    "CompositeThing",
    "Condition",
    "ConfigFilter",
    "ConfigLanguage",
    "ConfigNamePair",
    "ConfigurationError",
    "ConnectionClass",
    "ConnectionConfiguration",
    "ConnectionConstraint",
    "ConnectionRateLimitConfig",
    "CustomDelimiter",
    "CustomLang",
    "CustomLanguage",
    "CwMcpHttpState",
    "DataProviderSettings",
    "DataclassSerializationMixin",
    "DatetimeRange",
    "DefaultFilter",
    "Delimiter",
    "DelimiterChunker",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterMatch",
    "DelimiterPattern",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictView",
    "DimensionMismatchError",
    "DirectConnection",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DiscoveredFile",
    "DocsFilter",
    "DownloadedItem",
    "EmbeddingBatchInfo",
    "EmbeddingBatchInfo",
    "EmbeddingModelCapabilities",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "EmbeddingModelSettings",
    "EmbeddingProvider",
    "EmbeddingProviderServiceInfo",
    "EmbeddingProviderSettings",
    "Entry",
    "EnvVarInfo",
    "ErrorHandlingMiddleware",
    "ErrorHandlingMiddlewareSettings",
    "EvidenceKind",
    "ExtKind",
    "ExtLangPair",
    "ExtendedPointId",
    "ExtensionFilter",
    "ExternalToolset",
    "FastEmbedEmbeddingProvider",
    "FastEmbedRerankingProvider",
    "FastEmbedSparseProvider",
    "FastMcpHttpRunArgs",
    "FastMcpHttpServerSettings",
    "FastMcpServerSettingsDict",
    "FastMcpStdioServerSettings",
    "FastembedGPUProviderSettings",
    "FieldCondition",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FileStatistics",
    "FileThing",
    "FileWatcher",
    "Filter",
    "FilterID",
    "FilterableField",
    "FilteredKey",
    "FilteredKeyT",
    "FilteredToolset",
    "FiltersDict",
    "FormatterID",
    "FormattersDict",
    "FunctionToolset",
    "GeoBoundingBox",
    "GeoLineString",
    "GeoPoint",
    "GeoPolygon",
    "GeoRadius",
    "GoogleEmbeddingProvider",
    "GracefulChunker",
    "Grammar",
    "GrammarBasedClassifier",
    "GrammarClassificationResult",
    "HandlerID",
    "HandlersDict",
    "HasIdCondition",
    "HasVectorCondition",
    "HealthResponse",
    "HealthService",
    "HttpRequestsDict",
    "HuggingFaceEmbeddingProvider",
    "HybridVectorPayload",
    "Identifier",
    "IgnoreFilter",
    "ImportanceScores",
    "Indexer",
    "IndexerSettings",
    "IndexerSettingsDict",
    "IndexingError",
    "IndexingInfo",
    "IndexingProgressInfo",
    "InitializationError",
    "IsEmptyCondition",
    "IsNullCondition",
    "LanguageConfigFile",
    "LanguageFamily",
    "LanguageName",
    "LanguageNameT",
    "LazyImport",
    "LineStrategy",
    "LiteralProvider",
    "LiteralProviderKind",
    "LiteralStringT",
    "LlmToolName",
    "LlmToolNameT",
    "LoggerName",
    "LoggersDict",
    "LoggingConfigDict",
    "LoggingMiddleware",
    "LoggingMiddlewareSettings",
    "LoggingSettings",
    "MCPConfig",
    "MCPConfigDict",
    "ManagementServer",
    "Match",
    "MatchAny",
    "MatchExcept",
    "MatchPhrase",
    "MatchText",
    "MatchValue",
    "McpComponentRequests",
    "McpComponentTimingDict",
    "McpMiddleware",
    "McpOperationRequests",
    "McpTimingDict",
    "MemoryVectorStoreProvider",
    "MetaVar",
    "Metadata",
    "MiddlewareOptions",
    "MinShould",
    "MissingValueError",
    "MistralEmbeddingProvider",
    "ModelName",
    "ModelNameT",
    "ModelString",
    "ModelSwitchError",
    "Nested",
    "NestedCondition",
    "NthChild",
    "OpenAIEmbeddingBase",
    "OptimizationDecisions",
    "OversizedChunkError",
    "ParseError",
    "Pattern",
    "PayloadField",
    "PayloadMetadata",
    "PayloadSchemaType",
    "PersistenceError",
    "PosRule",
    "Position",
    "PositionalConnections",
    "PrefixedToolset",
    "PreparedToolset",
    "Provider",
    "ProviderEnvVarInfo",
    "ProviderEnvVars",
    "ProviderError",
    "ProviderKind",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "ProviderSpecificSettings",
    "ProviderSwitchError",
    "QdrantVectorStoreProvider",
    "QueryError",
    "QueryType",
    "Range",
    "Range",
    "RangeRule",
    "RateLimitingMiddleware",
    "RateLimitingMiddlewareSettings",
    "RawEmbeddingVectors",
    "Relation",
    "RenamedToolset",
    "RerankingModelName",
    "RerankingModelNameT",
    "RerankingModelSettings",
    "RerankingProvider",
    "RerankingProviderError",
    "RerankingProviderSettings",
    "RerankingResult",
    "RerankingServiceInfo",
    "ResourceGovernor",
    "ResourceUri",
    "ResponseCachingMiddleware",
    "RetryMiddleware",
    "RetryMiddlewareSettings",
    "RignoreSettings",
    "Role",
    "RoleT",
    "RootedRoot",
    "Rule",
    "RuleWithoutNot",
    "SemanticChunker",
    "SemanticClass",
    "SemanticMetadata",
    "SemanticScorer",
    "SemanticSearchLanguage",
    "SentenceTransformersEmbeddingProvider",
    "SentenceTransformersRerankingProvider",
    "SentenceTransformersSparseProvider",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "SerializableLoggingFilter",
    "SerializationKwargs",
    "SerializedCodeChunk",
    "SerializedStrOnlyCodeChunk",
    "ServicesInfo",
    "SessionStatistics",
    "SourceIdRegistry",
    "Span",
    "SpanGroup",
    "SpanTuple",
    "SparseEmbedding",
    "SparseEmbeddingModelCapabilities",
    "SparseEmbeddingModelSettings",
    "SparseEmbeddingServiceInfo",
    "StatisticsInfo",
    "StatisticsMiddleware",
    "StatusDisplay",
    "StdioCodeWeaverConfig",
    "StdioCodeWeaverConfigDict",
    "StoreDict",
    "StoredEmbeddingVectors",
    "StructuredDataInput",
    "StructuredLoggingMiddleware",
    "TelemetrySettings",
    "ThingClass",
    "ThingKind",
    "ThingName",
    "ThingNameT",
    "ThingRegistry",
    "ThingType",
    "TiktokenTokenizer",
    "TimingStatistics",
    "TimingStatisticsDict",
    "Token",
    "TokenCategory",
    "TokenCounter",
    "TokenPurpose",
    "Tokenizer",
    "Tokenizers",
    "ToolAnnotationsDict",
    "ToolOrPromptName",
    "ToolRegistrationDict",
    "ToolsetTool",
    "UUID7Hex",
    "UUID7HexT",
    "UUIDStore",
    "Unset",
    "UvicornServerSettings",
    "UvicornServerSettingsDict",
    "ValidationError",
    "ValueVariants",
    "ValuesCount",
    "VectorStoreProvider",
    "VectorStoreProviderSettings",
    "VectorStoreServiceInfo",
    "VoyageEmbeddingProvider",
    "VoyageRerankingProvider",
    "WrapperToolset",
    "__version__",
    "create_http_server",
    "create_stdio_server",
    "find_code",
    "find_code_tool",
    "find_code_tool_definition",
    "get_all_grammars",
    "get_bulk_tool",
    "get_settings_map",
    "make_blake_store",
    "make_uuid_store",
    "register_tool",
)


def __dir__() -> list[str]:
    return list(__all__)
