# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubevirt
from kubevirt.models.v1_virtual_machine_instance_condition import V1VirtualMachineInstanceCondition  # noqa: E501
from kubevirt.rest import ApiException


class TestV1VirtualMachineInstanceCondition(unittest.TestCase):
    """V1VirtualMachineInstanceCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1VirtualMachineInstanceCondition(self):
        """Test V1VirtualMachineInstanceCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubevirt.models.v1_virtual_machine_instance_condition.V1VirtualMachineInstanceCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
