# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubevirt
from kubevirt.models.v1_memory_dump_volume_source import V1MemoryDumpVolumeSource  # noqa: E501
from kubevirt.rest import ApiException


class TestV1MemoryDumpVolumeSource(unittest.TestCase):
    """V1MemoryDumpVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MemoryDumpVolumeSource(self):
        """Test V1MemoryDumpVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubevirt.models.v1_memory_dump_volume_source.V1MemoryDumpVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
