# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubevirt
from kubevirt.models.v1_sevsnp import V1SEVSNP  # noqa: E501
from kubevirt.rest import ApiException


class TestV1SEVSNP(unittest.TestCase):
    """V1SEVSNP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1SEVSNP(self):
        """Test V1SEVSNP"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubevirt.models.v1_sevsnp.V1SEVSNP()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
