import sourcepp._sourcepp_impl.vtfpp


def red(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def decompressedRed(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def green(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def decompressedGreen(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def blue(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def decompressedBlue(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def alpha(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def decompressedAlpha(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def bpp(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> int: ...

def containerFormat(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> sourcepp._sourcepp_impl.vtfpp.ImageFormat: ...

def large(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def decimal(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def compressed(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def transparent(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def opaque(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def console(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat) -> bool: ...

def get_data_length(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, width: int, height: int, depth: int = 1) -> int: ...

def get_data_length_extended(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, mip_count: int, frame_count: int, face_count: int, width: int, height: int, depth: int = 1) -> int: ...

def get_data_length_xbox(padded: bool, format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, mip_count: int, frame_count: int, face_count: int, width: int, height: int, depth: int = 1) -> int: ...

def get_data_position(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, mip: int, mip_count: int, frame: int, frame_count: int, face: int, face_count: int, width: int, height: int, slice: int = 0, depth: int = 1) -> tuple[int, int]: ...

def get_data_position_xbox(padded: bool, format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, mip: int, mip_count: int, frame: int, frame_count: int, face: int, face_count: int, width: int, height: int, slice: int = 0, depth: int = 1) -> tuple[int, int]: ...
