"""
Settings Package for {{ project_name }}
========================================

This package contains the modular Django settings:
- base.py: Common settings for all environments
- local.py: Development settings
- production.py: Production settings

Usage:
    # Development (default)
    python manage.py runserver
    
    # Production
    DJANGO_SETTINGS_MODULE=config.settings.production gunicorn config.wsgi

Generated by ADEMA Framework.
"""
