# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from kubevirt.configuration import Configuration


class V1CustomizeComponentsPatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'patch': 'str',
        'resource_name': 'str',
        'resource_type': 'str',
        'type': 'str'
    }

    attribute_map = {
        'patch': 'patch',
        'resource_name': 'resourceName',
        'resource_type': 'resourceType',
        'type': 'type'
    }

    def __init__(self, patch='', resource_name='', resource_type='', type='', _configuration=None):  # noqa: E501
        """V1CustomizeComponentsPatch - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._patch = None
        self._resource_name = None
        self._resource_type = None
        self._type = None
        self.discriminator = None

        self.patch = patch
        self.resource_name = resource_name
        self.resource_type = resource_type
        self.type = type

    @property
    def patch(self):
        """Gets the patch of this V1CustomizeComponentsPatch.  # noqa: E501


        :return: The patch of this V1CustomizeComponentsPatch.  # noqa: E501
        :rtype: str
        """
        return self._patch

    @patch.setter
    def patch(self, patch):
        """Sets the patch of this V1CustomizeComponentsPatch.


        :param patch: The patch of this V1CustomizeComponentsPatch.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and patch is None:
            raise ValueError("Invalid value for `patch`, must not be `None`")  # noqa: E501

        self._patch = patch

    @property
    def resource_name(self):
        """Gets the resource_name of this V1CustomizeComponentsPatch.  # noqa: E501


        :return: The resource_name of this V1CustomizeComponentsPatch.  # noqa: E501
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """Sets the resource_name of this V1CustomizeComponentsPatch.


        :param resource_name: The resource_name of this V1CustomizeComponentsPatch.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and resource_name is None:
            raise ValueError("Invalid value for `resource_name`, must not be `None`")  # noqa: E501

        self._resource_name = resource_name

    @property
    def resource_type(self):
        """Gets the resource_type of this V1CustomizeComponentsPatch.  # noqa: E501


        :return: The resource_type of this V1CustomizeComponentsPatch.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this V1CustomizeComponentsPatch.


        :param resource_type: The resource_type of this V1CustomizeComponentsPatch.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501

        self._resource_type = resource_type

    @property
    def type(self):
        """Gets the type of this V1CustomizeComponentsPatch.  # noqa: E501


        :return: The type of this V1CustomizeComponentsPatch.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1CustomizeComponentsPatch.


        :param type: The type of this V1CustomizeComponentsPatch.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CustomizeComponentsPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CustomizeComponentsPatch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1CustomizeComponentsPatch):
            return True

        return self.to_dict() != other.to_dict()
