# Label Keys
LABEL_PIPELINE = "pipeline"

LABEL_RESOURCE = "resource"
LABEL_RESOURCE_METHOD = "resource_method"

LABEL_MINION = "minion"
LABEL_MINION_INSTANCE_ID = "minion_instance_id"
LABEL_MINION_WORKFLOW_STEP = "minion_workflow_step"

LABEL_ERROR_TYPE = "error_type"

# Pipeline Metric Names
PIPELINE_EVENT_PRODUCED_TOTAL = "pipeline_event_produced_total"
PIPELINE_EVENT_FANOUT_TOTAL = "pipeline_event_fanout_total"
PIPELINE_ERROR_TOTAL = "pipeline_error_total"

# Resource Metric Names
RESOURCE_SERVES_TOTAL = "resource_serves_total"
RESOURCE_LATENCY_SECONDS = "resource_latency_seconds"
RESOURCE_ERROR_TOTAL = "resource_error_total"

# Minion Metric Names
MINION_WORKFLOW_STARTED_TOTAL = "minion_workflow_started_total"
MINION_WORKFLOW_INFLIGHT_GAUGE = "minion_workflow_inflight_gauge"
MINION_WORKFLOW_ABORTED_TOTAL = "minion_workflow_aborted_total"
MINION_WORKFLOW_FAILED_TOTAL = "minion_workflow_failed_total"
MINION_WORKFLOW_SUCCEEDED_TOTAL = "minion_workflow_succeeded_total"
MINION_WORKFLOW_DURATION_SECONDS = "minion_workflow_duration_seconds"

MINION_WORKFLOW_STEP_STARTED_TOTAL = "minion_workflow_step_started_total"
MINION_WORKFLOW_STEP_INFLIGHT_GAUGE = "minion_workflow_step_inflight_gauge"
MINION_WORKFLOW_STEP_ABORTED_TOTAL = "minion_workflow_step_aborted_total"
MINION_WORKFLOW_STEP_FAILED_TOTAL = "minion_workflow_step_failed_total"
MINION_WORKFLOW_STEP_SUCCEEDED_TOTAL = "minion_workflow_step_succeeded_total"
MINION_WORKFLOW_STEP_DURATION_SECONDS = "minion_workflow_step_duration_seconds"

# General Metric Names
SYSTEM_MEMORY_USED_PERCENT = "system_memory_used_percent"
SYSTEM_CPU_USED_PERCENT = "system_cpu_used_percent"
PROCESS_MEMORY_USED_PERCENT = "process_memory_used_percent"
PROCESS_CPU_USED_PERCENT = "process_cpu_used_percent"

# Metrics Label Names
METRIC_LABEL_NAMES = {
    PIPELINE_EVENT_PRODUCED_TOTAL: [LABEL_PIPELINE],
    PIPELINE_EVENT_FANOUT_TOTAL: [LABEL_PIPELINE],
    PIPELINE_ERROR_TOTAL: [LABEL_PIPELINE, LABEL_ERROR_TYPE],

    RESOURCE_SERVES_TOTAL: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD],
    RESOURCE_LATENCY_SECONDS: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD],
    RESOURCE_ERROR_TOTAL: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD, LABEL_ERROR_TYPE],

    MINION_WORKFLOW_STARTED_TOTAL: [LABEL_MINION],
    MINION_WORKFLOW_INFLIGHT_GAUGE: [LABEL_MINION],
    MINION_WORKFLOW_ABORTED_TOTAL: [LABEL_MINION],
    MINION_WORKFLOW_FAILED_TOTAL: [LABEL_MINION, LABEL_ERROR_TYPE],
    MINION_WORKFLOW_SUCCEEDED_TOTAL: [LABEL_MINION],
    MINION_WORKFLOW_DURATION_SECONDS: [LABEL_MINION],

    MINION_WORKFLOW_STEP_STARTED_TOTAL: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_INFLIGHT_GAUGE: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_ABORTED_TOTAL: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_FAILED_TOTAL: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP, LABEL_ERROR_TYPE],
    MINION_WORKFLOW_STEP_SUCCEEDED_TOTAL: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_DURATION_SECONDS: [LABEL_MINION, LABEL_MINION_WORKFLOW_STEP],

    SYSTEM_MEMORY_USED_PERCENT: [],
    SYSTEM_CPU_USED_PERCENT: [],
    PROCESS_MEMORY_USED_PERCENT: [],
    PROCESS_CPU_USED_PERCENT: [],
}