from .state_store import StateStore
from .._domain.minion_workflow_context import MinionWorkflowContext

class NoOpStateStore(StateStore):
    def __init__(self): ...
    
    async def save_context(self, ctx: MinionWorkflowContext): ...

    async def delete_context(self, workflow_id: str): ...
    
    async def load_all_contexts(self) -> list[MinionWorkflowContext]: ...
