from typing import Protocol

class LabelledMetric(Protocol):
    def labels(self, **kwargs: str) -> "LabelledMetric": ...
    def inc(self, amount: float = 1): ...
    def set(self, value: float): ...
    def observe(self, value: float): ...