# coding: utf-8

"""
    Document AI API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_documentai_api_client
from cloudmersive_documentai_api_client.api.run_batch_job_api import RunBatchJobApi  # noqa: E501
from cloudmersive_documentai_api_client.rest import ApiException


class TestRunBatchJobApi(unittest.TestCase):
    """RunBatchJobApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_documentai_api_client.api.run_batch_job_api.RunBatchJobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_extract_all_fields_and_tables_from_document_batch_job(self):
        """Test case for extract_all_fields_and_tables_from_document_batch_job

        Extract All Fields and Tables of Data from a Document using AI as a Batch Job  # noqa: E501
        """
        pass

    def test_extract_classification_from_document_batch_job(self):
        """Test case for extract_classification_from_document_batch_job

        Extract Classification or Category from a Document using AI as a Batch Job  # noqa: E501
        """
        pass

    def test_extract_fields_from_document_advanced_batch_job(self):
        """Test case for extract_fields_from_document_advanced_batch_job

        Extract Field Values from a Document using Advanced AI as a Batch Job  # noqa: E501
        """
        pass

    def test_extract_text_from_document_batch_job(self):
        """Test case for extract_text_from_document_batch_job

        Extract Text from a Document using AI as a Batch Job  # noqa: E501
        """
        pass

    def test_get_async_job_status(self):
        """Test case for get_async_job_status

        Get the status and result of an Extract Document Batch Job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
