def sanitize_filename(name: str) -> str: ...
def titleize(text: str) -> str: ...
def to_snake_case(text: str) -> str: ...
def parse_header(header: str, *, humanize: bool = True) -> tuple[str | None, str, str | None]: ...
