DATA = {
    "latitude": 50.45,
    "longitude": -104.617,
    "timezone": "America/Mexico_City",
    "offset": -6.0,
    "elevation": 579,
    "currently": {
        "time": 1765220280,
        "summary": "Partly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 183.55,
        "nearestStormBearing": 101,
        "precipIntensity": 0.0,
        "precipProbability": 0.0,
        "precipIntensityError": 0.0,
        "precipType": "none",
        "rainIntensity": 0.0,
        "snowIntensity": 0.0,
        "iceIntensity": 0.0,
        "temperature": -7.54,
        "apparentTemperature": -13.5,
        "dewPoint": -9.95,
        "humidity": 0.83,
        "pressure": 1008.31,
        "windSpeed": 20.26,
        "windGust": 32.87,
        "windBearing": 315,
        "cloudCover": 0.52,
        "uvIndex": 1.51,
        "visibility": 15.96,
        "ozone": 396.59,
        "smoke": 0.01,
        "fireIndex": 6.32,
        "feelsLike": -13.5,
        "currentDayIce": 0.0,
        "currentDayLiquid": 0.0,
        "currentDaySnow": 0.2593,
        "solar": 274.49,
        "cape": 0,
    },
    "minutely": {
        "summary": "Partly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1765220280,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none",
                "rainIntensity": 0.0,
                "snowIntensity": 0.0,
                "sleetIntensity": 0.0,
            }
        ],
    },
    "hourly": {
        "summary": "Light sleet tomorrow morning.",
        "icon": "sleet",
        "data": [
            {
                "time": 1765216800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "snow",
                "rainIntensity": 0.0,
                "snowIntensity": 0.0,
                "iceIntensity": 0.0,
                "temperature": -7.04,
                "apparentTemperature": -13.35,
                "dewPoint": -8.0,
                "humidity": 0.91,
                "pressure": 1008.55,
                "windSpeed": 21.6,
                "windGust": 33.84,
                "windBearing": 310,
                "cloudCover": 0.58,
                "uvIndex": 1.24,
                "visibility": 16.09,
                "ozone": 406.56,
                "smoke": 0.0,
                "liquidAccumulation": 0.0,
                "snowAccumulation": 0.0,
                "iceAccumulation": 0.0,
                "nearestStormDistance": 151.46,
                "nearestStormBearing": 104,
                "fireIndex": 6.0,
                "feelsLike": -14.45,
                "solar": 227.36,
                "cape": 0,
            }
        ],
    },
    "daily": {
        "summary": "Mixed precipitation tomorrow through Thursday, with high temperatures bottoming out at -25°C on Friday.",
        "icon": "sleet",
        "data": [
            {
                "time": 1765173600,
                "summary": "Mostly cloudy in the morning and evening.",
                "icon": "partly-cloudy-day",
                "dawnTime": 1765202837,
                "sunriseTime": 1765205195,
                "sunsetTime": 1765234463,
                "duskTime": 1765236820,
                "moonPhase": 0.63,
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipIntensityMaxTime": 1765173600,
                "precipProbability": 0.0,
                "precipType": "snow",
                "rainIntensity": 0.0,
                "rainIntensityMax": 0.0,
                "snowIntensity": 0.0,
                "snowIntensityMax": 0.0,
                "iceIntensity": 0.0,
                "iceIntensityMax": 0.0,
                "temperatureHigh": -6.24,
                "temperatureHighTime": 1765224000,
                "temperatureLow": -9.59,
                "temperatureLowTime": 1765242000,
                "apparentTemperatureHigh": -11.82,
                "apparentTemperatureHighTime": 1765227600,
                "apparentTemperatureLow": -15.03,
                "apparentTemperatureLowTime": 1765245600,
                "dewPoint": -10.92,
                "humidity": 0.91,
                "pressure": 1007.67,
                "windSpeed": 15.24,
                "windGust": 22.26,
                "windGustTime": 1765216800,
                "windBearing": 198,
                "cloudCover": 0.76,
                "uvIndex": 1.52,
                "uvIndexTime": 1765220400,
                "visibility": 15.55,
                "temperatureMin": -13.75,
                "temperatureMinTime": 1765173600,
                "temperatureMax": -6.24,
                "temperatureMaxTime": 1765224000,
                "apparentTemperatureMin": -20.23,
                "apparentTemperatureMinTime": 1765180800,
                "apparentTemperatureMax": -11.82,
                "apparentTemperatureMaxTime": 1765227600,
                "smokeMax": 0.02,
                "smokeMaxTime": 1765234800,
                "liquidAccumulation": 0.0,
                "snowAccumulation": 0.0,
                "iceAccumulation": 0.0,
                "fireIndexMax": 8.0,
                "fireIndexMaxTime": 1765238400,
                "solarMax": 272.62,
                "solarMaxTime": 1765220400,
                "capeMax": 0.0,
                "capeMaxTime": 1765173600,
            }
        ],
    },
    "day_night": {
        "summary": "Test day/night forecast",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1765216800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipProbability": 0.0,
                "precipType": "snow",
                "temperature": -7.04,
                "apparentTemperature": -13.35,
                "dewPoint": -8.0,
                "humidity": 0.91,
                "pressure": 1008.55,
                "windSpeed": 21.6,
                "windGust": 33.84,
                "windBearing": 310,
                "cloudCover": 0.58,
                "uvIndex": 1.24,
                "visibility": 16.09,
                "ozone": 406.56,
                "smoke": 0.0,
                "solar": 227.36,
                "feelsLike": -14.45,
                "cape": 0,
                "fireIndex": 6.0,
            }
        ],
    },
    "alerts": [
        {
            "title": "special weather statement in effect",
            "regions": ["City of Regina"],
            "severity": "Minor",
            "time": 1765189611,
            "expires": 1765247211,
            "description": "Strong winds and a wintry mix of precipitation is expected.\n\nLocations: Portions of southern Saskatchewan and southern Manitoba.\n\nTime span: Tuesday morning through to Wednesday morning.\n\nRemarks: A low-pressure system is expected to develop just east of the Rocky Mountains over southern Alberta Monday night and track southeast into southern Saskatchewan and western North Dakota on Tuesday.\n\nA narrow band of freezing rain is possible beginning Tuesday morning, extending from Kindersley to Estevan, presenting potential hazardous travel conditions.\n\nAs the system progresses eastward, heavier snowfall is likely across southeastern Saskatchewan and southwestern Manitoba, including the parklands. While exact accumulations remain uncertain, a general range of 10 to 20 cm is anticipated, with higher totals possible over elevated terrain.\n\nBehind the system, winds will strengthen and could produce blowing snow across southern Saskatchewan on Tuesday. However, warmer air and the potential for freezing rain in southern areas may limit both snowfall and the extent of blowing snow there. The windiest locations are expected to see reduced new-snow amounts, except in southeast Saskatchewan where sufficient snowfall combined with stronger winds may still result in localized blowing snow.\n\nMeteorologists are actively monitoring the evolving situation, and it is anticipated that warnings will be issued later today.\n\n###\n\nPlease continue to monitor alerts and forecasts issued by Environment Canada. To report severe weather, send an email to SKstorm@ec.gc.ca, call 1-800-239-0484 or post reports on X using #SKStorm.\n\nFor more information about the alerting program, please visit: https://www.canada.ca/en/services/environment/weather/severeweather/weather-alerts/colour-coded-alerts.",
            "uri": "https://severeweather.wmo.int/v2/cap-alerts/ca-msc-xx/2025/12/08/10/26/51-5f851e56aa977246cbaef9166ec56197.xml",
        }
    ],
    "flags": {
        "sources": [
            "ETOPO1",
            "hrrrsubh",
            "rtma_ru",
            "hrrr_0-18",
            "nbm",
            "nbm_fire",
            "ecmwf_ifs",
            "hrrr_18-48",
            "gfs",
            "gefs",
        ],
        "sourceTimes": {
            "hrrr_subh": "2025-12-08 17Z",
            "rtma_ru": "2025-12-08 18:30Z",
            "hrrr_0-18": "2025-12-08 16Z",
            "nbm": "2025-12-08 15Z",
            "nbm_fire": "2025-12-08 12Z",
            "ecmwf_ifs": "2025-12-08 00Z",
            "hrrr_18-48": "2025-12-08 12Z",
            "gfs": "2025-12-08 12Z",
            "gefs": "2025-12-08 06Z",
        },
        "nearest-station": 0,
        "units": "ca",
        "version": "V2.8.5",
        "sourceIDX": {
            "hrrr": {"x": 727, "y": 982, "lat": 50.45, "lon": -104.63},
            "nbm": {"x": 989, "y": 1270, "lat": 50.45, "lon": -104.6},
            "ecmwf_ifs": {"x": 302, "y": 158, "lat": 50.5, "lon": -104.5},
            "rtma_ru": {"x": 989, "y": 1270, "lat": 50.45, "lon": -104.6},
            "gfs": {"x": 1022, "y": 562, "lat": 50.5, "lon": -104.5},
            "etopo": {"x": 4523, "y": 8427, "lat": 50.45, "lon": -104.6167},
        },
        "processTime": 32951,
        "ingestVersion": "v30",
        "nearestCity": "Regina",
        "nearestCountry": "Canada",
        "nearestSubNational": "Saskatchewan",
    },
}
