

class Steam:
    def __init__(self) -> None: ...

    @property
    def install_dir(self) -> str: ...

    @property
    def library_dirs(self) -> list[str]: ...

    @property
    def sourcemod_dir(self) -> str: ...

    @property
    def installed_apps(self) -> list[int]: ...

    def is_app_installed(self, appID: int) -> bool: ...

    def get_app_name(self, appID: int) -> str: ...

    def get_app_install_dir(self, appID: int) -> str: ...

    def get_app_icon_path(self, appID: int) -> str: ...

    def get_app_logo_path(self, appID: int) -> str: ...

    def get_app_hero_path(self, appID: int) -> str: ...

    def get_app_box_art_path(self, appID: int) -> str: ...

    def get_app_store_art_path(self, appID: int) -> str: ...

    def is_app_using_goldsrc_engine(self, appID: int) -> bool: ...

    def is_app_using_source_engine(self, appID: int) -> bool: ...

    def is_app_using_source_2_engine(self, appID: int) -> bool: ...

    def __bool__(self) -> bool: ...
