"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2

class PhysicsAiInferenceServiceStub:
    """Manages physics AI inference jobs."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    CreateInferenceServiceJob: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.CreateInferenceServiceJobRequest,
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse,
    ]
    """Creates an inference service job synchronously, waiting for completion."""
    CreateInferenceServiceJobAsync: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.CreateInferenceServiceJobRequest,
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse,
    ]
    """Creates an inference service job asynchronously without waiting for completion."""
    GetInferenceServiceJob: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobRequest,
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse,
    ]
    """Retrieves an inference service job by its ID."""
    ListInferenceServiceJobs: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.ListInferenceServiceJobsRequest,
        luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.ListInferenceServiceJobsResponse,
    ]
    """Lists all inference service jobs for a given project."""

class PhysicsAiInferenceServiceServicer(metaclass=abc.ABCMeta):
    """Manages physics AI inference jobs."""

    @abc.abstractmethod
    def CreateInferenceServiceJob(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.CreateInferenceServiceJobRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse:
        """Creates an inference service job synchronously, waiting for completion."""
    @abc.abstractmethod
    def CreateInferenceServiceJobAsync(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.CreateInferenceServiceJobRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse:
        """Creates an inference service job asynchronously without waiting for completion."""
    @abc.abstractmethod
    def GetInferenceServiceJob(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.GetInferenceServiceJobResponse:
        """Retrieves an inference service job by its ID."""
    @abc.abstractmethod
    def ListInferenceServiceJobs(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.ListInferenceServiceJobsRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.physicsaiinference.physicsaiinference_pb2.ListInferenceServiceJobsResponse:
        """Lists all inference service jobs for a given project."""

def add_PhysicsAiInferenceServiceServicer_to_server(servicer: PhysicsAiInferenceServiceServicer, server: grpc.Server) -> None: ...
