"""
Template sample URLs configuration.

This module contains the mapping of template names to their sample image URLs.
Add your S3 URLs here as they become available.
"""

# Template name to S3 URL mapping
# Template name to S3 URL mapping
TEMPLATE_SAMPLE_URLS = {
    "education_info_2": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/education_info_2.png",
    "coming_soon_post_2": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/coming_soon_post_2.png",
    "quote_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/quote_template.png",
    "calendar_app_promo": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/calendar_app_promo.png",
    "product_service": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/product_service.png",
    "product_showcase_5": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesproduct_showcase_5.png",
    "product_showcase_4": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/product_showcase_4.png",
    "product_showcase_3": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/product_showcase_3.png",
    "coming_soon_page": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/coming_soon_page.png",
    "job_opening": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/job_opening.png",
    "education_info": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/education_info.png",
    "product_service_minimal": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/product_service_minimal.png",
    "coming_soon": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/coming_soon.png",
    "brand_info": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesbrand_info.png",
    "product_marketing": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesproduct_marketing.png",
    "brand_info_2": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesbrand_info_2.png",
    "sale_alert": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatessale_alert.png",
    "testimonials": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatestestimonials.png",
    "event_alert": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesevent_alert.png",
    "product_sale_2": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesproduct_sale_2.png",
    "event_announcement": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templates/baseevent_announcement.png",
    "super_king_burgers_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatessuper_king_burgers_template.png",
    "shoe_ad_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesshoe_ad_template.png",
    "grilled_chicken_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesgrilled_chicken_template.png",
    "healthy_food_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templateshealthy_food_template.png",
    "product_poster": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesproduct_poster.png",
    "orchid_baby_post": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesorchid_baby_post.png",
    "shelf_engine_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesshelf_engine_template.png",
    "learn_gif_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templateslearn_gif_template.png",
    "sales_offer_poster": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesjuice_poster.png",
    "stamped_loyalty_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesstamped_loyalty_template.png",
    "product_promotion": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/product_promotion.png",
    "product_promotion_6": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesbaby_product_promotion.png",
    "food_menu_promo": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesfood_menu_promo.png",
    "reward_program_template": "https://dolze-templates-uat.s3.eu-north-1.amazonaws.com/uploads/templatesreward_program_template.png",
    "social_media_tips": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/social_media_tips.png",
    "spotlight_launching": "https://i.ibb.co/rGVRbWJN/Black-White-Modern-Launching-Soon-Instagram-Post.png",
    "launch_announcement": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/launch_announcement.png",
    "business_highlights_2035_html": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/business_highlights_2035_html.png",
"process_steps": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/process_steps.png",
    "faq_template": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/faq_template.png",
    "neon_creative_agency": "https://i.ibb.co/SDL3bJ58/neon-creative-agency.png",
    "search_services_listing": "https://i.ibb.co/0VCJS87S/Blue-Modern-Search-Our-Services-Instagram-Post-1.png",
    "social_media": "https://i.ibb.co/nsYFg6GJ/Navy-Modern-Social-Media-Marketing-Instagram-Post.png",
    "contact_us": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/contact_us.png",
    "neon_creative_agency":"https://i.ibb.co/SDL3bJ58/neon-creative-agency.png",
    "social_media": "https://i.ibb.co/nsYFg6GJ/Navy-Modern-Social-Media-Marketing-Instagram-Post.png",
    "neon_creative_agency": "https://i.ibb.co/SDL3bJ58/neon-creative-agency.png",
    "marketing_trends_list": "https://i.ibb.co/Pqf9p6s/Untitled-design-2.png",
    "why_us_reasons": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/why_us_reasons.png",
    "social_media":"https://i.ibb.co/nsYFg6GJ/Navy-Modern-Social-Media-Marketing-Instagram-Post.png",
    "social_media_2":"https://i.ibb.co/6R3p5hMJ/Black-Clean-What-Exactly-Is-Marketing-Instagram-Post.png",
    "strategy_cards": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/strategy_cards.png",
    "neon_creative_agency": "https://i.ibb.co/SDL3bJ58/neon-creative-agency.png",
    "services_showcase": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/services_showcase.png",
    "social_media": "https://i.ibb.co/nsYFg6GJ/Navy-Modern-Social-Media-Marketing-Instagram-Post.png",
    "faq_white_post": "https://i.ibb.co/BKGqh2vD/White-Aesthetic-Simple-Product-FAQ-Instagram-Post-1.png",
    "social_media_2": "https://i.ibb.co/6R3p5hMJ/Black-Clean-What-Exactly-Is-Marketing-Instagram-Post.png",
    "financial_education": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/financial_education.png",
    "hiring_announcement": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/hiring_announcement.png",
    "testimonial_card": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/testimonial_card.png",
    "myth_vs_fact": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/myth_vs_fact.png",
    "service_promotion": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/service_promotion.png",
    "partnership_announcement": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/partnership_announcement.png",
    "job_search_promotion": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/job_search_promotion.png",
    "annual_report": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/annual_report.png",
    "product_promotion_v2": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/product_promotion_v2.png",
    "smart_investment": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/smart_investment.png",
    "we_are_hiring": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/we_are_hiring.png",
    "flash_sale": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/flash_sale.png",
    "creative_marketing_agency": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/creative_marketing_agency.png",
    "pricing_plans": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/pricing_plans.png",
    "3_tips": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/3_tips.png",
"app_promo_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/app_promo_1.png",
"app_promo_2": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/app_promo_2.png",
"black_friday_offer_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/black_friday_offer_1.png",
"bundle_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/bundle_offer.png",
"countdown_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/countdown_1.png",
"countdown_2": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/countdown_2.png",
"happy_christmas_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/happy_christmas_1.png",
"invitation_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/invitation_1.png",
"menu_card_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/menu_card_1.png",
"new_year_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/new_year_offer.png",
"new_year_wishes_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/new_year_wishes_1.png",
"quiz_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/quiz_1.png",
"quiz_3": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/quiz_3.png",
"app_promo_3": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/app_promo_3.png",
"question_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/question_1.png",
"text_block_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/text_block_1.png",
"product_promo_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/product_promo_1.png",
"buy_one_get_one": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/buy_one_get_one.png",
"challenge": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/challenge.png",
"clearance_sale": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/clearance_sale.png",
"download_template": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/download_template.png",
"early_bird_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/early_bird_offer.png",
"flash_sale_simple": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/flash_sale_simple.png",
"guru_nanak_jayanti": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/guru_nanak_jayanti.png",
"indian_constitution_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/indian_constitution_day.png",
"international_day_persons_disabilities": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/international_day_persons_disabilities.png",
"lohri": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/lohri.png",
"makar_sankranti": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/makar_sankranti.png",
"myth_or_truth": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/myth_or_truth.png",
"national_youth_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/national_youth_day.png",
"new_year": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/new_year.png",
"new_year_eve": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/new_year_eve.png",
"plan_post_1": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/plan_post_1.png",
"pongal": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/pongal.png",
"preorder": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/preorder.png",
"product_launch": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/product_launch.png",
"referral_program": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/referral_program.png",
"republic_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/republic_day.png",
"valentines_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/valentines_day.png",
"world_aids_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/world_aids_day.png",
"world_cancer_day": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/world_cancer_day.png",
"bihu": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/bihu.png",
"qna": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/qna.png",
"tripwire": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/tripwire.png",
"giveaway": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/giveaway.png",
"followers_celebration": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/followers_celebration.png",
"email_template": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/email_template.png",
"reactivation_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/reactivation_offer.png",
"product_intro": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/product_intro.png",
"ecommerce_and_retail_email": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/ecommerce_and_retail_email.png",
"ecommerce": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/ecommerce.png",
"newsletter": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/newsletter.png",
"generic_email": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/generic_email.png",
"generic_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/generic_offer.png",
"cyber_monday_offer": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/cyber_monday_offer.png",
"welcome_email": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/welcome_email.png",
"welcome_email_professional": "https://dolze-docs-uat.s3.ap-south-1.amazonaws.com/post_templates/welcome_email_professional.png",
}


def get_sample_url(template_name: str) -> str:
    """
    Get the sample URL for a template.

    Args:
        template_name: Name of the template

    Returns:
        str: The sample URL if exists, empty string otherwise
    """
    return TEMPLATE_SAMPLE_URLS.get(template_name, "")
