from enum import Enum


class Provider(Enum):
    AWS = "aws"
    AZURE = "azure"


class AwsResource(Enum):
    EC2 = "ec2"
    LAMBDA = "lambda"
    ECS = "ecs"
    EKS = "eks"
    VPC = "vpc"
    ELB = "elb"
    CLASSIC_ELB = "classic-elb"
    API_GATEWAY_REST = "api-gateway-rest"
    API_GATEWAY_HTTP = "api-gateway-http"
    ROUTE53 = "route53"
    CLOUDFRONT = "cloudfront"
    S3 = "s3"
    EBS = "ebs"
    EFS = "efs"
    RDS = "rds"
    DYNAMODB = "dynamodb"
    ELASTICACHE = "elasticache"
    REDSHIFT = "redshift"
    IAM = "iam"
    ORGANIZATIONS = "organizations"
    KMS = "kms"
    SECRETS_MANAGER = "secrets-manager"
    ACM = "acm"
    WAF = "waf"
    SHIELD = "shield"
    GUARDDUTY = "guardduty"
    SECURITY_HUB = "security-hub"
    CLOUDWATCH = "cloudwatch"
    CLOUDTRAIL = "cloudtrail"
    CONFIG = "config"
    SYSTEMS_MANAGER = "systems-manager"
    BACKUP = "backup"


class AzureResource(Enum):
    VM = "vm"
    VNET = "vnet"
    FUNCTIONS = "functions"
    CONTAINER_INSTANCE = "container-instance"
    CONTAINER_APP = "container-app"
    AKS = "aks"
    LOAD_BALANCER = "load-balancer"
    APPLICATION_GATEWAY = "application-gateway"
    TRAFFIC_MANAGER = "traffic-manager"
    API_MANAGEMENT = "api-management"
    DNS = "dns"
    FRONT_DOOR = "front-door"
    CDN = "cdn"
    STORAGE_ACCOUNT = "storage-account"
    MANAGED_DISK = "managed-disk"
    STORAGE_FILE_SHARE = "storage-file-share"
    SQL_DATABASE = "sql-database"
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    MARIADB = "mariadb"
    COSMOS_DB = "cosmos-db"
    REDIS = "redis"
    SYNAPSE = "synapse"
    ACTIVE_DIRECTORY = "active-directory"
    MANAGEMENT_GROUP = "management-group"
    KEY_VAULT = "key-vault"
    KEY_VAULT_KEY = "key-vault-key"
    KEY_VAULT_SECRET = "key-vault-secret"
    KEY_VAULT_CERTIFICATE = "key-vault-certificate"
    WAF = "waf"
    DDOS = "ddos"
    DEFENDER = "defender"
    SECURE_SCORE = "secure-score"
    MONITOR = "monitor"
    ACTIVITY_LOG = "activity-log"
    POLICY = "policy"
    AUTOMATION = "automation"
    BACKUP = "backup"


class ResourceKind(Enum):
    COMPUTE = "compute"
    NETWORK = "network"
    DATABASE = "database"
    STORAGE = "storage"
    SECURITY = "security"
    IDENTITY = "identity"
    MANAGEMENT = "management"
    OBSERVABILITY = "observability"
