# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Global type definitions for CodeWeaver.

We usually try to keep types close to where they are used, but some types
are used so widely that it makes sense to define them globally here.
"""

from importlib import import_module
from types import MappingProxyType
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    # Import everything for IDE and type checker support
    # These imports are never executed at runtime, only during type checking
    from codeweaver.core.chunks import (
        ChunkSequence,
        CodeChunk,
        CodeChunkDict,
        SerializedCodeChunk,
        SerializedStrOnlyCodeChunk,
        StructuredDataInput,
    )
    from codeweaver.core.discovery import DiscoveredFile
    from codeweaver.core.language import (
        ConfigLanguage,
        ConfigNamePair,
        LanguageConfigFile,
        SemanticSearchLanguage,
        find_config_paths,
        has_semantic_extension,
        is_semantic_config_ext,
        language_from_config_file,
        languages_present_from_configs,
    )
    from codeweaver.core.metadata import (
        ChunkKind,
        ChunkSource,
        ExtKind,
        ExtLangPair,
        Metadata,
        SemanticMetadata,
    )
    from codeweaver.core.spans import Span, SpanGroup, SpanTuple
    from codeweaver.core.stores import (
        BlakeHashKey,
        BlakeKey,
        BlakeStore,
        StoreDict,
        UUIDStore,
        make_blake_store,
        make_uuid_store,
        to_uuid,
    )
    from codeweaver.core.types import (
        BASEDMODEL_CONFIG,
        DATACLASS_CONFIG,
        FROZEN_BASEDMODEL_CONFIG,
        UNSET,
        AnonymityConversion,
        BaseDataclassEnum,
        BasedModel,
        BaseEnum,
        BaseEnumData,
        CategoryName,
        CategoryNameT,
        DataclassSerializationMixin,
        DeserializationKwargs,
        DevToolName,
        DevToolNameT,
        DictView,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        EmbeddingModelName,
        EmbeddingModelNameT,
        EnvVarInfo,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        LanguageName,
        LanguageNameT,
        LiteralStringT,
        LlmToolName,
        LlmToolNameT,
        ModelName,
        ModelNameT,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        RootedRoot,
        Sentinel,
        SentinelName,
        SentinelNameT,
        SerializationKwargs,
        ThingName,
        ThingNameT,
        Unset,
        UUID7Hex,
        UUID7HexT,
        generate_field_title,
        generate_title,
    )


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "DATACLASS_CONFIG": (__spec__.parent, "types"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "UNSET": (__spec__.parent, "types"),
    "AnonymityConversion": (__spec__.parent, "types"),
    "BaseDataclassEnum": (__spec__.parent, "types"),
    "BaseEnum": (__spec__.parent, "types"),
    "BaseEnumData": (__spec__.parent, "types"),
    "BasedModel": (__spec__.parent, "types"),
    "CategoryName": (__spec__.parent, "types"),
    "CategoryNameT": (__spec__.parent, "types"),
    "DataclassSerializationMixin": (__spec__.parent, "types"),
    "DeserializationKwargs": (__spec__.parent, "types"),
    "DevToolName": (__spec__.parent, "types"),
    "DevToolNameT": (__spec__.parent, "types"),
    "DirectoryName": (__spec__.parent, "types"),
    "DirectoryNameT": (__spec__.parent, "types"),
    "DirectoryPath": (__spec__.parent, "types"),
    "DirectoryPathT": (__spec__.parent, "types"),
    "EmbeddingModelName": (__spec__.parent, "types"),
    "EmbeddingModelNameT": (__spec__.parent, "types"),
    "EnvVarInfo": (__spec__.parent, "types"),
    "ExtLangPair": (__spec__.parent, "metadata"),
    "FileExt": (__spec__.parent, "types"),
    "FileExtensionT": (__spec__.parent, "types"),
    "FileGlob": (__spec__.parent, "types"),
    "FileGlobT": (__spec__.parent, "types"),
    "FileName": (__spec__.parent, "types"),
    "FileNameT": (__spec__.parent, "types"),
    "FilePath": (__spec__.parent, "types"),
    "FilePathT": (__spec__.parent, "types"),
    "FilteredKey": (__spec__.parent, "types"),
    "FilteredKeyT": (__spec__.parent, "types"),
    "LanguageName": (__spec__.parent, "types"),
    "LanguageNameT": (__spec__.parent, "types"),
    "LiteralStringT": (__spec__.parent, "types"),
    "LlmToolName": (__spec__.parent, "types"),
    "LlmToolNameT": (__spec__.parent, "types"),
    "ModelName": (__spec__.parent, "types"),
    "ModelNameT": (__spec__.parent, "types"),
    "RerankingModelName": (__spec__.parent, "types"),
    "RerankingModelNameT": (__spec__.parent, "types"),
    "Role": (__spec__.parent, "types"),
    "RoleT": (__spec__.parent, "types"),
    "RootedRoot": (__spec__.parent, "types"),
    "Sentinel": (__spec__.parent, "types"),
    "SentinelName": (__spec__.parent, "types"),
    "SentinelNameT": (__spec__.parent, "types"),
    "SerializationKwargs": (__spec__.parent, "types"),
    "ThingName": (__spec__.parent, "types"),
    "ThingNameT": (__spec__.parent, "types"),
    "Unset": (__spec__.parent, "types"),
    "UUID7Hex": (__spec__.parent, "types"),
    "UUID7HexT": (__spec__.parent, "types"),
    "generate_field_title": (__spec__.parent, "types"),
    "generate_title": (__spec__.parent, "types"),
    "ChunkSequence": (__spec__.parent, "chunks"),
    "CodeChunk": (__spec__.parent, "chunks"),
    "CodeChunkDict": (__spec__.parent, "chunks"),
    "SerializedCodeChunk": (__spec__.parent, "chunks"),
    "StructuredDataInput": (__spec__.parent, "chunks"),
    "DictView": (__spec__.parent, "types"),
    "DiscoveredFile": (__spec__.parent, "discovery"),
    "ConfigLanguage": (__spec__.parent, "language"),
    "ConfigNamePair": (__spec__.parent, "language"),
    "LanguageConfigFile": (__spec__.parent, "language"),
    "SemanticSearchLanguage": (__spec__.parent, "language"),
    "find_config_paths": (__spec__.parent, "language"),
    "has_semantic_extension": (__spec__.parent, "language"),
    "is_semantic_config_ext": (__spec__.parent, "language"),
    "language_from_config_file": (__spec__.parent, "language"),
    "languages_present_from_configs": (__spec__.parent, "language"),
    "Metadata": (__spec__.parent, "metadata"),
    "ChunkKind": (__spec__.parent, "metadata"),
    "ChunkSource": (__spec__.parent, "metadata"),
    "ExtKind": (__spec__.parent, "metadata"),
    "SemanticMetadata": (__spec__.parent, "metadata"),
    "SerializedStrOnlyCodeChunk": (__spec__.parent, "chunks"),
    "Span": (__spec__.parent, "spans"),
    "SpanGroup": (__spec__.parent, "spans"),
    "SpanTuple": (__spec__.parent, "spans"),
    "BlakeHashKey": (__spec__.parent, "stores"),
    "BlakeKey": (__spec__.parent, "stores"),
    "BlakeStore": (__spec__.parent, "stores"),
    "StoreDict": (__spec__.parent, "stores"),
    "UUIDStore": (__spec__.parent, "stores"),
    "make_blake_store": (__spec__.parent, "stores"),
    "make_uuid_store": (__spec__.parent, "stores"),
    "to_uuid": (__spec__.parent, "stores"),
})
"""Dynamically import submodules and classes for the core package.

Maps class/function/type names to their respective module paths for lazy loading.
"""


def __getattr__(name: str) -> object:
    """Dynamically import submodules and classes for the core package."""
    if name in _dynamic_imports:
        module_name, submodule_name = _dynamic_imports[name]
        module = import_module(f"{module_name}.{submodule_name}")
        result = getattr(module, name)
        globals()[name] = result  # Cache in globals for future access
        return result
    if globals().get(name) is not None:
        return globals()[name]
    raise AttributeError(f"module {__name__} has no attribute {name}")


__all__ = (
    "BASEDMODEL_CONFIG",
    "DATACLASS_CONFIG",
    "FROZEN_BASEDMODEL_CONFIG",
    "UNSET",
    "AnonymityConversion",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BasedModel",
    "BlakeHashKey",
    "BlakeKey",
    "BlakeStore",
    "CategoryName",
    "CategoryNameT",
    "ChunkKind",
    "ChunkSequence",
    "ChunkSource",
    "CodeChunk",
    "CodeChunkDict",
    "ConfigLanguage",
    "ConfigNamePair",
    "DataclassSerializationMixin",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictView",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DiscoveredFile",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "EnvVarInfo",
    "ExtKind",
    "ExtLangPair",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FilteredKey",
    "FilteredKeyT",
    "LanguageConfigFile",
    "LanguageName",
    "LanguageNameT",
    "LiteralStringT",
    "LlmToolName",
    "LlmToolNameT",
    "Metadata",
    "ModelName",
    "ModelNameT",
    "RerankingModelName",
    "RerankingModelNameT",
    "Role",
    "RoleT",
    "RootedRoot",
    "SemanticMetadata",
    "SemanticSearchLanguage",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "SerializationKwargs",
    "SerializedCodeChunk",
    "SerializedStrOnlyCodeChunk",
    "Span",
    "SpanGroup",
    "SpanTuple",
    "StoreDict",
    "StructuredDataInput",
    "ThingName",
    "ThingNameT",
    "UUID7Hex",
    "UUID7HexT",
    "UUIDStore",
    "Unset",
    "find_config_paths",
    "generate_field_title",
    "generate_title",
    "has_semantic_extension",
    "is_semantic_config_ext",
    "language_from_config_file",
    "languages_present_from_configs",
    "make_blake_store",
    "make_uuid_store",
    "to_uuid",
)


def __dir__() -> list[str]:
    """List available attributes for the core package."""
    return list(__all__)
