"""Enhance resource types with comprehensive lists."""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data" / "resource_types"


def enhance_gcp() -> None:
    """Enhance GCP resource types to ~100+ services."""
    file_path = DATA_DIR / "gcp.json"
    
    with open(file_path, "r") as f:
        data = json.load(f)
    
    existing = set(data["resource_types"])
    
    additional_gcp_services = [
        "Cloud Filestore",
        "Cloud Storage Transfer",
        "Cloud Storage for Firebase",
        "Persistent Disk",
        "Local SSD",
        "Cloud SQL for MySQL",
        "Cloud SQL for PostgreSQL",
        "Cloud SQL for SQL Server",
        "AlloyDB",
        "Firestore",
        "Cloud Spanner",
        "Cloud Bigtable",
        "Memorystore for Redis",
        "Memorystore for Memcached",
        "Cloud Datastore",
        "Cloud Firestore",
        "Cloud BigQuery",
        "BigQuery ML",
        "BigQuery Data Transfer Service",
        "BigQuery Omni",
        "BigQuery BI Engine",
        "Cloud Dataflow",
        "Cloud Dataproc",
        "Cloud Composer",
        "Cloud Data Fusion",
        "Cloud Dataform",
        "Cloud Dataplex",
        "Cloud Life Sciences",
        "Cloud Healthcare API",
        "Cloud Genomics",
        "Cloud Pub/Sub",
        "Cloud Pub/Sub Lite",
        "Cloud Scheduler",
        "Cloud Tasks",
        "Cloud Workflows",
        "Eventarc",
        "Cloud Functions",
        "Cloud Run",
        "App Engine",
        "App Engine Flexible",
        "App Engine Standard",
        "GKE",
        "GKE Autopilot",
        "GKE on-prem",
        "Anthos",
        "Anthos Service Mesh",
        "Anthos Config Management",
        "Anthos Multi-Cloud",
        "Cloud Build",
        "Cloud Deploy",
        "Cloud Source Repositories",
        "Artifact Registry",
        "Container Registry",
        "Cloud Code",
        "Cloud Shell",
        "Cloud Console",
        "Cloud APIs",
        "Cloud SDK",
        "Cloud Client Libraries",
        "Cloud Endpoints",
        "API Gateway",
        "Apigee",
        "Cloud Armor",
        "Cloud CDN",
        "Cloud Load Balancing",
        "Cloud DNS",
        "Cloud Domains",
        "Cloud Interconnect",
        "Cloud VPN",
        "Cloud NAT",
        "VPC",
        "Virtual Private Cloud",
        "Cloud Router",
        "Cloud Firewall",
        "Cloud IDS",
        "Cloud Security Command Center",
        "Cloud DLP",
        "Cloud IAP",
        "Cloud Identity",
        "Cloud IAM",
        "Cloud KMS",
        "Cloud HSM",
        "Cloud Secret Manager",
        "Cloud Resource Manager",
        "Cloud Asset",
        "Cloud Billing",
        "Cloud Cost Management",
        "Cloud Recommender",
        "Cloud Monitoring",
        "Cloud Logging",
        "Cloud Trace",
        "Cloud Debugger",
        "Cloud Profiler",
        "Cloud Error Reporting",
        "Cloud Operations Suite",
        "Cloud Vision",
        "Cloud Vision API",
        "Cloud Video Intelligence",
        "Cloud Speech-to-Text",
        "Cloud Text-to-Speech",
        "Cloud Translation",
        "Cloud Natural Language",
        "Cloud AutoML",
        "Cloud AI Platform",
        "Vertex AI",
        "Vertex AI Workbench",
        "Vertex AI Pipelines",
        "Vertex AI Feature Store",
        "Vertex AI Model Garden",
        "Cloud TPU",
        "Cloud Inference API",
        "Cloud Talent Solution",
        "Cloud Recommendations AI",
        "Cloud Document AI",
        "Cloud Retail",
        "Cloud Contact Center AI",
        "Cloud Dialogflow",
        "Cloud Dialogflow CX",
        "Cloud Dialogflow ES",
        "Cloud Text-to-Speech",
        "Cloud Speech-to-Text",
        "Cloud Translation",
        "Cloud Natural Language",
        "Cloud Video Intelligence",
        "Cloud Vision",
        "Cloud AutoML",
        "Cloud AI Platform",
        "Cloud TPU",
        "Cloud Inference API",
        "Cloud Talent Solution",
        "Cloud Recommendations AI",
        "Cloud Document AI",
        "Cloud Retail",
        "Cloud Contact Center AI",
        "Cloud Dialogflow",
        "Cloud Maps",
        "Maps JavaScript API",
        "Maps SDK for Android",
        "Maps SDK for iOS",
        "Places API",
        "Routes API",
        "Geocoding API",
        "Geolocation API",
        "Time Zone API",
        "Elevation API",
        "Street View Static API",
        "Cloud Gaming",
        "Stadia",
        "Cloud Gaming Platform",
    ]
    
    all_types = existing | set(additional_gcp_services)
    data["resource_types"] = sorted(list(all_types))
    
    with open(file_path, "w") as f:
        json.dump(data, f, indent=2)
    
    print(f"GCP: {len(data['resource_types'])} unique resource types (was {len(existing)})")


def enhance_azure() -> None:
    """Enhance Azure resource types to ~150+ services."""
    file_path = DATA_DIR / "azure.json"
    
    with open(file_path, "r") as f:
        data = json.load(f)
    
    existing = set(data["resource_types"])
    
    additional_azure_services = [
        "Azure Database for MySQL",
        "Azure Database for PostgreSQL",
        "Azure Database for MariaDB",
        "Azure SQL Managed Instance",
        "Azure SQL Edge",
        "Azure Cosmos DB",
        "Azure Table Storage",
        "Azure Queue Storage",
        "Azure File Storage",
        "Azure Blob Storage",
        "Azure Disk Storage",
        "Azure NetApp Files",
        "Azure Archive Storage",
        "Azure Data Lake Storage Gen1",
        "Azure Data Lake Storage Gen2",
        "Azure Files",
        "Azure StorSimple",
        "Azure Backup",
        "Azure Site Recovery",
        "Azure Migrate",
        "Azure Database Migration Service",
        "Azure Data Box",
        "Azure Data Box Disk",
        "Azure Data Box Heavy",
        "Azure Data Box Edge",
        "Azure Data Box Gateway",
        "Azure Stack",
        "Azure Stack Edge",
        "Azure Stack Hub",
        "Azure Stack HCI",
        "Azure Arc",
        "Azure Arc enabled Kubernetes",
        "Azure Arc enabled servers",
        "Azure Arc enabled data services",
        "Azure Arc enabled SQL Server",
        "Azure Arc enabled PostgreSQL",
        "Azure Arc enabled MySQL",
        "Azure Kubernetes Service",
        "Azure Container Instances",
        "Azure Container Apps",
        "Azure Container Registry",
        "Azure Red Hat OpenShift",
        "Azure Service Fabric",
        "Azure Spring Cloud",
        "Azure Batch",
        "Azure Cloud Services",
        "Azure Virtual Machines",
        "Azure VM Scale Sets",
        "Azure Dedicated Host",
        "Azure Spot Virtual Machines",
        "Azure Reserved VM Instances",
        "Azure Functions",
        "Azure App Service",
        "Azure App Service Environment",
        "Azure Static Web Apps",
        "Azure Logic Apps",
        "Azure Power Apps",
        "Azure Power Automate",
        "Azure Power BI",
        "Azure Power Virtual Agents",
        "Azure API Management",
        "Azure Service Bus",
        "Azure Event Hubs",
        "Azure Event Grid",
        "Azure Notification Hubs",
        "Azure Relay",
        "Azure SignalR Service",
        "Azure Communication Services",
        "Azure Cognitive Services",
        "Azure Computer Vision",
        "Azure Custom Vision",
        "Azure Face API",
        "Azure Form Recognizer",
        "Azure Ink Recognizer",
        "Azure Video Analyzer",
        "Azure Content Moderator",
        "Azure Personalizer",
        "Azure Immersive Reader",
        "Azure Language Understanding",
        "Azure QnA Maker",
        "Azure Translator",
        "Azure Text Analytics",
        "Azure Speech Services",
        "Azure Speech to Text",
        "Azure Text to Speech",
        "Azure Speech Translation",
        "Azure Speaker Recognition",
        "Azure Bot Service",
        "Azure Machine Learning",
        "Azure Machine Learning Studio",
        "Azure Databricks",
        "Azure HDInsight",
        "Azure Synapse Analytics",
        "Azure Data Factory",
        "Azure Data Lake Analytics",
        "Azure Stream Analytics",
        "Azure Time Series Insights",
        "Azure Data Explorer",
        "Azure Data Share",
        "Azure Data Catalog",
        "Azure Purview",
        "Azure Digital Twins",
        "Azure IoT Hub",
        "Azure IoT Central",
        "Azure IoT Edge",
        "Azure Sphere",
        "Azure RTOS",
        "Azure Maps",
        "Azure Location Based Services",
        "Azure Search",
        "Azure Cognitive Search",
        "Azure Media Services",
        "Azure Video Indexer",
        "Azure Content Delivery Network",
        "Azure Front Door",
        "Azure Application Gateway",
        "Azure Load Balancer",
        "Azure Traffic Manager",
        "Azure DNS",
        "Azure Private DNS",
        "Azure DDoS Protection",
        "Azure Firewall",
        "Azure Network Watcher",
        "Azure Virtual Network",
        "Azure Virtual Network Manager",
        "Azure VPN Gateway",
        "Azure ExpressRoute",
        "Azure ExpressRoute Direct",
        "Azure ExpressRoute Global Reach",
        "Azure Private Link",
        "Azure Bastion",
        "Azure Network Security Groups",
        "Azure Application Security Groups",
        "Azure Route Tables",
        "Azure Service Endpoints",
        "Azure VNet Peering",
        "Azure Virtual WAN",
        "Azure Key Vault",
        "Azure Managed HSM",
        "Azure Active Directory",
        "Azure AD B2C",
        "Azure AD B2B",
        "Azure AD Domain Services",
        "Azure AD Privileged Identity Management",
        "Azure AD Identity Protection",
        "Azure AD Conditional Access",
        "Azure AD Application Proxy",
        "Azure AD Multi-Factor Authentication",
        "Azure Information Protection",
        "Azure Rights Management",
        "Azure Security Center",
        "Azure Defender",
        "Azure Sentinel",
        "Azure Security Benchmark",
        "Azure Policy",
        "Azure Blueprints",
        "Azure Resource Manager",
        "Azure Management Groups",
        "Azure Subscriptions",
        "Azure Resource Groups",
        "Azure Tags",
        "Azure Cost Management",
        "Azure Advisor",
        "Azure Monitor",
        "Azure Log Analytics",
        "Azure Application Insights",
        "Azure Network Watcher",
        "Azure Service Health",
        "Azure Resource Health",
        "Azure Activity Log",
        "Azure Metrics",
        "Azure Alerts",
        "Azure Action Groups",
        "Azure Automation",
        "Azure Update Management",
        "Azure Change Tracking",
        "Azure Inventory",
        "Azure State Configuration",
        "Azure Desired State Configuration",
        "Azure PowerShell",
        "Azure CLI",
        "Azure Cloud Shell",
        "Azure Portal",
        "Azure Mobile App",
        "Azure REST API",
        "Azure SDK",
        "Azure Developer Tools",
        "Azure DevOps",
        "Azure Repos",
        "Azure Pipelines",
        "Azure Artifacts",
        "Azure Test Plans",
        "Azure Boards",
        "Azure GitHub Actions",
        "Azure GitHub Integration",
    ]
    
    all_types = existing | set(additional_azure_services)
    data["resource_types"] = sorted(list(all_types))
    
    with open(file_path, "w") as f:
        json.dump(data, f, indent=2)
    
    print(f"Azure: {len(data['resource_types'])} unique resource types (was {len(existing)})")


if __name__ == "__main__":
    print("Enhancing resource types...")
    enhance_gcp()
    enhance_azure()
    print("Done!")

