from enum import Enum


class Languages(str, Enum):
    ARABIC = "ar"
    AZERBAIJANI = "az"
    BELARUSIAN = "be"
    BULGARIAN = "bg"
    BENGALI = "bn"
    BOSNIAN = "bs"
    CATALAN = "ca"
    CZECH = "cs"
    WELSH = "cy"
    DANISH = "da"
    GERMAN = "de"
    GREEK = "el"
    ENGLISH = "en"
    ESPERANTO = "eo"
    SPANISH = "es"
    ESTONIAN = "et"
    PERSIAN = "fa"
    FINNISH = "fi"
    FRENCH = "fr"
    IRISH = "ga"
    GAELIC = "gd"
    HEBREW = "he"
    HINDI = "hi"
    CROATIAN = "hr"
    HUNGARIAN = "hu"
    INDONESIAN = "id"
    ICELANDIC = "is"
    ITALIAN = "it"
    JAPANESE = "ja"
    GEORGIAN = "ka"
    KANNADA = "kn"
    KOREAN = "ko"
    CORNISH = "kw"
    LATVIAN = "lv"
    MALAYAM = "ml"
    MARATHI = "mr"
    NORWEGIAN_BOKMAL = "nb"
    DUTCH = "nl"
    NORWEGIAN_BOKMAL_NB = "no"
    PUNJABI = "pa"
    POLISH = "pl"
    PORTUGUESE = "pt"
    ROMANIAN = "ro"
    RUSSIAN = "ru"
    SLOVAK = "sk"
    SLOVENIAN = "sl"
    SERBIAN = "sr"
    SWEDISH = "sv"
    TAMIL = "ta"
    TELUGU = "te"
    TETUM = "tet"
    TURKISH = "tr"
    UKRAINIAN = "uk"
    URDU = "ur"
    VIETNAMESE = "vi"
    IGPAY_ATINLAY = "x-pig-latin"
    SIMPLIFIED_CHINESE = "zh"
    TRADITIONAL_CHINESE = "zh-tw"

    @classmethod
    def list(cls):
        return list(map(lambda c: c.value, cls))
