from __future__ import annotations
from typing import Protocol, runtime_checkable

from zempy.zosapi.editors.protocols.i_solve_data import ISolveData

@runtime_checkable
class ISolveMaterialOffset(ISolveData, Protocol):
    """Protocol for ISolveMaterialOffset (refactored to inherit ISolveData; unique fields only)."""
    @property
    def NdOffset(self) -> float: ...
    @NdOffset.setter
    def NdOffset(self, value: float) -> None: ...
    @property
    def VdOffset(self) -> float: ...
    @VdOffset.setter
    def VdOffset(self, value: float) -> None: ...
    @property
    def Documentation(self) -> str: ...
    @property
    def set(self) -> str: ...
    @property
    def by(self) -> str: ...
