from __future__ import annotations
from typing import Protocol, runtime_checkable

from zempy.zosapi.editors.protocols.i_solve_data import ISolveData

@runtime_checkable
class ISolveEdgeThickness(ISolveData, Protocol):
    """Protocol for ISolveEdgeThickness (refactored to inherit ISolveData; unique fields only)."""
    @property
    def Thickness(self) -> float: ...
    @Thickness.setter
    def Thickness(self, value: float) -> None: ...
    @property
    def RadialHeight(self) -> float: ...
    @RadialHeight.setter
    def RadialHeight(self, value: float) -> None: ...
    @property
    def Documentation(self) -> str: ...
    @property
    def set(self) -> str: ...
    @property
    def by(self) -> str: ...
