import sourcepp._sourcepp_impl.sourcepp.math


class GameInstance:
    @staticmethod
    def find(window_name_override: str = '') -> GameInstance | None: ...

    @property
    def window_title(self) -> str: ...

    @property
    def window_pos(self) -> sourcepp._sourcepp_impl.sourcepp.math.Vec2i32: ...

    @property
    def window_size(self) -> sourcepp._sourcepp_impl.sourcepp.math.Vec2i32: ...

    def command(self, command: str) -> GameInstance: ...

    def input_begin(self, input: str) -> GameInstance: ...

    def input_end(self, input: str) -> GameInstance: ...

    def input_once(self, input: str) -> GameInstance: ...

    def input_hold(self, input: str, sec: float) -> GameInstance: ...

    def wait(self, sec: float) -> GameInstance: ...
