from collections.abc import Iterator
import enum
from typing import overload

import sourcepp._sourcepp_impl.sourcepp.math


class KV1ElementReadable:
    @property
    def key(self) -> str: ...

    @property
    def value(self) -> str: ...

    @property
    def conditional(self) -> str: ...

    def has_child(self, child_key: str) -> bool: ...

    @property
    def child_count(self) -> int: ...

    def __len__(self) -> int: ...

    def get_child_count_with_key(self, child_key: str) -> int: ...

    def __iter__(self) -> Iterator[KV1ElementReadable]: ...

    @overload
    def __getitem__(self, n: int) -> KV1ElementReadable: ...

    @overload
    def __getitem__(self, child_key: str) -> KV1ElementReadable: ...

    def get_child(self, child_key: str, n: int) -> KV1ElementReadable: ...

    def is_invalid(self) -> bool: ...

    def get_invalid() -> : ...

    def __bool__(self) -> bool: ...

class KV1(KV1ElementReadable):
    def __init__(self, kv1_data: str, use_escape_sequences: bool = False) -> None: ...

class KV1ElementWritable:
    @property
    def key(self) -> str: ...

    @key.setter
    def key(self, arg: str, /) -> None: ...

    @property
    def value(self) -> str: ...

    @value.setter
    def value(self, arg: str, /) -> None: ...

    @property
    def conditional(self) -> str: ...

    @conditional.setter
    def conditional(self, arg: str, /) -> None: ...

    def has_child(self, child_key: str) -> bool: ...

    def add_child(self, key: str, value: str = '', conditional: str = '') -> KV1ElementWritable: ...

    @property
    def child_count(self) -> int: ...

    def __len__(self) -> int: ...

    def get_child_count_with_key(self, child_key: str) -> int: ...

    def __iter__(self) -> Iterator[KV1ElementWritable]: ...

    @overload
    def __getitem__(self, n: int) -> KV1ElementWritable: ...

    @overload
    def __getitem__(self, child_key: str) -> KV1ElementWritable: ...

    def get_child(self, child_key: str, n: int) -> KV1ElementWritable: ...

    @overload
    def remove_child(self, n: int) -> None: ...

    @overload
    def remove_child(self, child_key: str, n: int = -1) -> None: ...

    @overload
    def __delitem__(self, n: int) -> None: ...

    @overload
    def __delitem__(self, child_key: str, n: int = -1) -> None: ...

    def is_invalid(self) -> bool: ...

    def get_invalid() -> : ...

    def __bool__(self) -> bool: ...

class KV1Writer(KV1ElementWritable):
    def __init__(self, kv1_data: str = '', use_escape_sequences: bool = False) -> None: ...

    def bake(self) -> str: ...

    def bake_to_file(self, kv1_path: str) -> None: ...

class KV1BinaryValueType(enum.Enum):
    CHILDREN = 0

    STRING = 1

    INT32 = 2

    FLOAT = 3

    POINTER = 4

    WSTRING = 5

    COLOR_RGBA = 6

    UINT64 = 7

    COUNT = 8

class KV1BinaryElement:
    def __init__(self) -> None: ...

    @property
    def key(self) -> str: ...

    @key.setter
    def key(self, arg: str, /) -> None: ...

    @property
    def value(self) -> None | str | int | float | int | str | sourcepp._sourcepp_impl.sourcepp.math.Vec4ui8 | int: ...

    @value.setter
    def value(self, arg: str | int | float | int | str | sourcepp._sourcepp_impl.sourcepp.math.Vec4ui8 | int, /) -> None: ...

    def has_child(self, child_key: str) -> bool: ...

    def add_child(self, key: str, value: str | int | float | int | str | sourcepp._sourcepp_impl.sourcepp.math.Vec4ui8 | int | None = None) -> None: ...

    @property
    def child_count(self) -> int: ...

    def __len__(self) -> int: ...

    def get_child_count_with_key(self, child_key: str) -> int: ...

    def __iter__(self) -> Iterator[KV1BinaryElement]: ...

    @overload
    def __getitem__(self, n: int) -> KV1BinaryElement: ...

    @overload
    def __getitem__(self, child_key: str) -> KV1BinaryElement: ...

    def get_child(self, child_key: str, n: int) -> KV1BinaryElement: ...

    @overload
    def remove_child(self, n: int) -> None: ...

    @overload
    def remove_child(self, child_key: str, n: int = -1) -> None: ...

    @overload
    def __delitem__(self, n: int) -> None: ...

    @overload
    def __delitem__(self, child_key: str, n: int = -1) -> None: ...

    def is_invalid(self) -> bool: ...

    def get_invalid() -> : ...

    def __bool__(self) -> bool: ...

class KV1Binary(KV1BinaryElement):
    def __init__(self, kv1_data: bytes, use_escape_sequences: bool = False) -> KV1Binary: ...

    def bake(self) -> bytes: ...

    def bake_to_file(self, kv1_path: str) -> None: ...

    def bake_text(self) -> str: ...

    def bake_text_to_file(self, kv1_path: str) -> None: ...
