PROJECT_ROOT = "^^^"
LOCAL_ROOT = "^^"
PARENT_NODE = "^"
FILE_EXTENSION = ".xiatl"
BOLD_PREFIX = "\033[1m"
RED_PREFIX = "\033[31m"
GREEN_PREFIX = "\033[32m"
YELLOW_PREFIX = "\033[33m"
RESET_POSTFIX = "\033[0m"
NAME = "NAME"
VALUE = "VALUE"
VALIDATOR = "VALIDATOR"
SUCCEEDED = True
FAILED = False

