from . import KnownCodes as KnownCodes


def decrypt_bytes(data: bytes, code: str = 'x9Ke0BY7') -> bytes: ...

def decrypt_str(data: str, code: str = 'x9Ke0BY7') -> str: ...

def encrypt_bytes(data: bytes, code: str = 'x9Ke0BY7') -> bytes: ...

def encrypt_str(data: str, code: str = 'x9Ke0BY7') -> str: ...
