"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemas_cortex_v1_bridge_phrases_dictionarymetadata import (
    SchemasCortexV1BridgePhrasesDictionaryMetadata,
    SchemasCortexV1BridgePhrasesDictionaryMetadataTypedDict,
)
from syllable_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BridgePhrasesConfigTypedDict(TypedDict):
    r"""Configuration for conversational bridge phrases."""

    first_slow_messages: NotRequired[List[str]]
    r"""Messages to say when the agent is first delayed."""
    very_slow_messages: NotRequired[List[str]]
    r"""Messages to say when the agent is significantly delayed."""
    tool_responses: NotRequired[List[str]]
    r"""Messages to say when a tool call is in progress."""
    metadata: NotRequired[SchemasCortexV1BridgePhrasesDictionaryMetadataTypedDict]
    r"""Metadata for the bridge phrases dictionary."""


class BridgePhrasesConfig(BaseModel):
    r"""Configuration for conversational bridge phrases."""

    first_slow_messages: Optional[List[str]] = None
    r"""Messages to say when the agent is first delayed."""

    very_slow_messages: Optional[List[str]] = None
    r"""Messages to say when the agent is significantly delayed."""

    tool_responses: Optional[List[str]] = None
    r"""Messages to say when a tool call is in progress."""

    metadata: Optional[SchemasCortexV1BridgePhrasesDictionaryMetadata] = None
    r"""Metadata for the bridge phrases dictionary."""
