"""Standard Luna error codes."""

from enum import Enum


class ErrorCode(str, Enum):
    """Standard error codes for Luna SDK."""

    # Authentication errors
    AUTH_INVALID_KEY = "LUNA_ERR_AUTH_INVALID_KEY"
    AUTH_TOKEN_EXPIRED = "LUNA_ERR_AUTH_TOKEN_EXPIRED"
    AUTH_INSUFFICIENT_PERMISSIONS = "LUNA_ERR_AUTH_INSUFFICIENT_PERMISSIONS"

    # Rate limiting
    RATE_LIMIT_EXCEEDED = "LUNA_ERR_RATE_LIMIT_EXCEEDED"

    # Resource errors
    RESOURCE_NOT_FOUND = "LUNA_ERR_RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "LUNA_ERR_RESOURCE_CONFLICT"

    # Validation errors
    VALIDATION_FAILED = "LUNA_ERR_VALIDATION_FAILED"
    VALIDATION_INVALID_PARAMETER = "LUNA_ERR_VALIDATION_INVALID_PARAMETER"

    # Network errors
    NETWORK_TIMEOUT = "LUNA_ERR_NETWORK_TIMEOUT"
    NETWORK_CONNECTION = "LUNA_ERR_NETWORK_CONNECTION"

    # Server errors
    SERVER_INTERNAL = "LUNA_ERR_SERVER_INTERNAL"
    SERVER_UNAVAILABLE = "LUNA_ERR_SERVER_UNAVAILABLE"


# Set of retryable error codes
RETRYABLE_CODES = {
    ErrorCode.RATE_LIMIT_EXCEEDED,
    ErrorCode.NETWORK_TIMEOUT,
    ErrorCode.NETWORK_CONNECTION,
    ErrorCode.SERVER_INTERNAL,
    ErrorCode.SERVER_UNAVAILABLE,
}
