from _typeshed import Incomplete as Incomplete
from matplotlib.figure import Figure
from pathlib import Path
from rdetoolkit.graph.io.path_validator import PathValidator as PathValidator
from typing import Any

class FileWriter:
    validator: Incomplete
    def __init__(self, validator: PathValidator | None = None) -> None: ...
    def save_matplotlib(self, figure: Figure, output_dir: Path, filename: str, dpi: int = 300, **kwargs: Any) -> Path: ...
    def save_plotly_html(self, figure: Any, output_dir: Path, filename: str, **kwargs: Any) -> Path: ...
    def save_figure(self, figure: Any, output_dir: Path, filename: str, format_type: str = 'png', **kwargs: Any) -> Path: ...
