from typing import Callable

def Connect(Address: str = "", nPort: unsigned short = 0)-> bool: ...
def Disconnect() -> None: ...
def Login(UserName: str, Password: str, Software: str = "", Version: str = "", Company: str = "", Branch: str = "") -> None: ...
def Go() -> None: ...
def SubscribeToQuote(Symbol: str, Exc: int, sExc: int = -1, rlot:bool = False) -> int: ...
def CloseSubscribe(Index: int) -> bool: ...
def SubscribeToTick(Symbol: str, Exc: int, sExc: int = -1, rlot:bool = False) -> int: ...
def GetQuote(Index: int, Field: int) -> int | float: ...
def GetTick(Index:int)-> List[Dict[str, Union[int, float]]]: ...
def GetInfo(Exc:int, Symbol:str, Field:str, sExc:int)-> str: ...
def SetNoticeCallback(callback: Callable[[int, int, object, int], None]) -> None: ...
def SetLoginCallback(callback: Callable[[int, str, int], None]) -> None: ...
def SetExcInfoCallback(callback: Callable[[int, int], None]) -> None: ...
def SetStkiCallback(callback: Callable[[int, int, int], None]) -> None: ...
def SetQuoteCallback(callback: Callable[[int, int], None]) -> None: ...
def SetTickCallback(callback: Callable[[int], None]) -> None: ...