"""Extended Data Types Library.

This library provides extended functionality for handling various data types in Python.
It includes utilities for YAML, JSON, TOML, Base64, file paths, Git repositories, strings,
lists, maps, and more.
"""

from __future__ import annotations

from extended_data_types.base64_utils import base64_decode, base64_encode
from extended_data_types.export_utils import (
    make_raw_data_export_safe,
    wrap_raw_data_for_export,
)
from extended_data_types.file_data_type import (
    FilePath,
    clone_repository_to_temp,
    decode_file,
    delete_file,
    file_path_depth,
    file_path_rel_to_root,
    get_encoding_for_file_path,
    get_parent_repository,
    get_repository_name,
    get_tld,
    is_url,
    match_file_extensions,
    read_file,
    resolve_local_path,
    write_file,
)
from extended_data_types.hcl2_utils import decode_hcl2
from extended_data_types.import_utils import unwrap_raw_data_from_import
from extended_data_types.json_utils import decode_json, encode_json
from extended_data_types.list_data_type import filter_list, flatten_list
from extended_data_types.map_data_type import (
    SortedDefaultDict,
    all_values_from_map,
    create_merger,
    deduplicate_map,
    deep_merge,
    filter_map,
    first_non_empty_value_from_map,
    flatten_map,
    get_default_dict,
    unhump_map,
    zipmap,
)
from extended_data_types.matcher_utils import is_non_empty_match, is_partial_match
from extended_data_types.splitter_utils import split_dict_by_type, split_list_by_type
from extended_data_types.stack_utils import (
    filter_methods,
    get_available_methods,
    get_caller,
    get_inputs_from_docstring,
    get_unique_signature,
    update_docstring,
)
from extended_data_types.state_utils import (
    all_non_empty,
    all_non_empty_in_dict,
    all_non_empty_in_list,
    any_non_empty,
    are_nothing,
    first_non_empty,
    is_nothing,
    yield_non_empty,
)
from extended_data_types.string_data_type import (
    bytestostr,
    lower_first_char,
    removeprefix,
    removesuffix,
    sanitize_key,
    titleize_name,
    truncate,
    upper_first_char,
)
from extended_data_types.string_transformations import (
    humanize,
    ordinalize,
    pluralize,
    singularize,
    titleize,
    to_camel_case,
    to_kebab_case,
    to_pascal_case,
    to_snake_case,
)
from extended_data_types.toml_utils import decode_toml, encode_toml
from extended_data_types.type_utils import (
    convert_special_type,
    convert_special_types,
    get_default_value_for_type,
    get_primitive_type_for_instance_type,
    make_hashable,
    reconstruct_special_type,
    reconstruct_special_types,
    strtobool,
    strtodate,
    strtodatetime,
    strtofloat,
    strtoint,
    strtopath,
    strtotime,
    typeof,
)
from extended_data_types.yaml_utils import decode_yaml, encode_yaml, is_yaml_data


__version__ = "5.2.1"

__all__ = [
    "FilePath",
    "SortedDefaultDict",
    "all_non_empty",
    "all_non_empty_in_dict",
    "all_non_empty_in_list",
    "all_values_from_map",
    "any_non_empty",
    "are_nothing",
    "base64_decode",
    "base64_encode",
    "bytestostr",
    "clone_repository_to_temp",
    "convert_special_type",
    "convert_special_types",
    "create_merger",
    "decode_file",
    "decode_hcl2",
    "decode_json",
    "decode_toml",
    "decode_yaml",
    "deduplicate_map",
    "deep_merge",
    "delete_file",
    "encode_json",
    "encode_toml",
    "encode_yaml",
    "file_path_depth",
    "file_path_rel_to_root",
    "filter_list",
    "filter_map",
    "filter_methods",
    "first_non_empty",
    "first_non_empty_value_from_map",
    "flatten_list",
    "flatten_map",
    "get_available_methods",
    "get_caller",
    "get_default_dict",
    "get_default_value_for_type",
    "get_encoding_for_file_path",
    "get_inputs_from_docstring",
    "get_parent_repository",
    "get_primitive_type_for_instance_type",
    "get_repository_name",
    "get_tld",
    "get_unique_signature",
    # String transformation aliases
    "humanize",
    "is_non_empty_match",
    "is_nothing",
    "is_partial_match",
    "is_url",
    "is_yaml_data",
    "lower_first_char",
    "make_hashable",
    "make_raw_data_export_safe",
    "match_file_extensions",
    "ordinalize",
    "pluralize",
    "read_file",
    "reconstruct_special_type",
    "reconstruct_special_types",
    "removeprefix",
    "removesuffix",
    "resolve_local_path",
    "sanitize_key",
    "singularize",
    "split_dict_by_type",
    "split_list_by_type",
    "strtobool",
    "strtodate",
    "strtodatetime",
    "strtofloat",
    "strtoint",
    "strtopath",
    "strtotime",
    "titleize",
    "titleize_name",
    "to_camel_case",
    "to_kebab_case",
    "to_pascal_case",
    "to_snake_case",
    "truncate",
    "typeof",
    "unhump_map",
    "unwrap_raw_data_from_import",
    "update_docstring",
    "upper_first_char",
    "wrap_raw_data_for_export",
    "write_file",
    "yield_non_empty",
    "zipmap",
]
