"""Constants used throughout AgenticFleet.

This module centralizes magic numbers, strings, and configuration values
to improve maintainability and reduce code duplication.
"""

from __future__ import annotations

# Task validation constants
MAX_TASK_LENGTH = 10000
MIN_TASK_LENGTH = 1

# Cache constants
DEFAULT_CACHE_TTL = 300  # 5 minutes in seconds
ANALYSIS_CACHE_TTL = 3600  # 1 hour in seconds
CACHE_VERSION = 2
MIN_CACHE_SIZE_BYTES = 64

# Timeout constants
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_AGENT_TIMEOUT = 300  # 5 minutes
DEFAULT_WORKFLOW_TIMEOUT = 600  # 10 minutes

# Retry constants
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 1.0
MAX_RETRY_ATTEMPTS = 5

# Quality thresholds
DEFAULT_QUALITY_THRESHOLD = 8.0
DEFAULT_JUDGE_THRESHOLD = 7.0
DEFAULT_REFINEMENT_THRESHOLD = 8.0
PERFECT_SCORE = 10.0

# Workflow limits
DEFAULT_MAX_ROUNDS = 15
DEFAULT_MAX_STALLS = 3
DEFAULT_MAX_RESETS = 2
DEFAULT_MAX_REFINEMENT_ROUNDS = 2
DEFAULT_PARALLEL_THRESHOLD = 3

# DSPy constants
DEFAULT_DSPY_MODEL = "gpt-5-mini"
DEFAULT_DSPY_TEMPERATURE = 0.7
DEFAULT_DSPY_MAX_TOKENS = 2000
DEFAULT_MAX_BOOTSTRAPPED_DEMOS = 4

# Agent model defaults
DEFAULT_AGENT_MODEL = "gpt-4.1"
DEFAULT_RESEARCHER_TEMPERATURE = 0.5
DEFAULT_ANALYST_TEMPERATURE = 0.3
DEFAULT_WRITER_TEMPERATURE = 0.7
DEFAULT_REVIEWER_TEMPERATURE = 0.2
DEFAULT_JUDGE_TEMPERATURE = 0.4

# Reasoning effort levels
REASONING_EFFORT_MINIMAL = "minimal"
REASONING_EFFORT_MEDIUM = "medium"
REASONING_EFFORT_MAXIMAL = "maximal"
DEFAULT_REASONING_EFFORT = REASONING_EFFORT_MEDIUM

# Execution modes
EXECUTION_MODE_DELEGATED = "delegated"
EXECUTION_MODE_SEQUENTIAL = "sequential"
EXECUTION_MODE_PARALLEL = "parallel"

# File paths - runtime data consolidated under .var/
DEFAULT_CONFIG_PATH = "config/workflow_config.yaml"
DEFAULT_EXAMPLES_PATH = "src/agentic_fleet/data/supervisor_examples.json"
DEFAULT_VAR_DIR = ".var"
DEFAULT_CACHE_DIR = ".var/cache"
DEFAULT_LOGS_DIR = ".var/logs"
DEFAULT_DATA_DIR = ".var/data"
DEFAULT_CACHE_PATH = ".var/logs/compiled_supervisor.pkl"
DEFAULT_ANSWER_QUALITY_CACHE_PATH = ".var/logs/compiled_answer_quality.pkl"
DEFAULT_NLU_CACHE_PATH = ".var/logs/compiled_nlu.pkl"
DEFAULT_HISTORY_PATH = ".var/logs/execution_history.jsonl"
DEFAULT_LOG_PATH = ".var/logs/workflow.log"
DEFAULT_GEPA_LOG_DIR = ".var/logs/gepa"
DEFAULT_DSPY_CACHE_DIR = ".var/cache/dspy"
DEFAULT_DSPY_EXAMPLES_PATH = ".var/logs/dspy_examples.jsonl"
DEFAULT_EVALUATION_DIR = ".var/logs/evaluation"

# History constants
DEFAULT_HISTORY_FORMAT = "jsonl"
DEFAULT_MAX_HISTORY_ENTRIES = 1000

# Progress refresh rate
DEFAULT_REFRESH_RATE = 4  # refresh_per_second for Rich Live

# Error message limits
MAX_TASK_PREVIEW_LENGTH = 100
MAX_ERROR_MESSAGE_LENGTH = 500

# Browser tool defaults
DEFAULT_BROWSER_TIMEOUT_MS = 30000  # 30 seconds for page navigation
DEFAULT_BROWSER_SELECTOR_TIMEOUT_MS = 5000  # 5 seconds for element selectors
DEFAULT_BROWSER_MAX_TEXT_LENGTH = 10000  # Maximum characters for extracted text

# GEPA optimizer defaults
DEFAULT_GEPA_VAL_SPLIT = 0.2
DEFAULT_GEPA_SEED = 13
DEFAULT_GEPA_HISTORY_MIN_QUALITY = 8.0
DEFAULT_GEPA_HISTORY_LIMIT = 200
DEFAULT_GEPA_MAX_FULL_EVALS = 50
DEFAULT_GEPA_MAX_METRIC_CALLS = 150
DEFAULT_GEPA_PERFECT_SCORE = 1.0

# Agent names
AGENT_RESEARCHER = "Researcher"
AGENT_ANALYST = "Analyst"
AGENT_WRITER = "Writer"
AGENT_REVIEWER = "Reviewer"
AGENT_JUDGE = "Judge"
AGENT_PLANNER = "Planner"
AGENT_EXECUTOR = "Executor"
AGENT_CODER = "Coder"
AGENT_VERIFIER = "Verifier"
AGENT_GENERATOR = "Generator"
AGENT_COORDINATOR = "Coordinator"

# Tool names
TOOL_TAVILY_MCP = "TavilyMCPTool"
TOOL_TAVILY_SEARCH = "TavilySearchTool"
TOOL_BROWSER = "BrowserTool"
TOOL_HOSTED_CODE_INTERPRETER = "HostedCodeInterpreterTool"

# Phase names
PHASE_ANALYSIS = "analysis"
PHASE_ROUTING = "routing"
PHASE_EXECUTION = "execution"
PHASE_PROGRESS = "progress"
PHASE_QUALITY = "quality"
PHASE_JUDGE = "judge"
PHASE_REFINEMENT = "refinement"

# Status values
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"
STATUS_PENDING = "pending"
STATUS_IN_PROGRESS = "in_progress"
STATUS_TIMEOUT = "timeout"

# Serialization formats
SERIALIZER_PICKLE = "pickle"
SERIALIZER_DILL = "dill"
SERIALIZER_NONE = "none"

__all__ = [
    "AGENT_ANALYST",
    "AGENT_CODER",
    "AGENT_COORDINATOR",
    "AGENT_EXECUTOR",
    "AGENT_GENERATOR",
    "AGENT_JUDGE",
    "AGENT_PLANNER",
    "AGENT_RESEARCHER",
    "AGENT_REVIEWER",
    "AGENT_VERIFIER",
    "AGENT_WRITER",
    "ANALYSIS_CACHE_TTL",
    "CACHE_VERSION",
    "DEFAULT_AGENT_MODEL",
    "DEFAULT_AGENT_TIMEOUT",
    "DEFAULT_ANALYST_TEMPERATURE",
    "DEFAULT_ANSWER_QUALITY_CACHE_PATH",
    "DEFAULT_BROWSER_MAX_TEXT_LENGTH",
    "DEFAULT_BROWSER_SELECTOR_TIMEOUT_MS",
    "DEFAULT_BROWSER_TIMEOUT_MS",
    "DEFAULT_CACHE_DIR",
    "DEFAULT_CACHE_PATH",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_DATA_DIR",
    "DEFAULT_DSPY_CACHE_DIR",
    "DEFAULT_DSPY_EXAMPLES_PATH",
    "DEFAULT_DSPY_MAX_TOKENS",
    "DEFAULT_DSPY_MODEL",
    "DEFAULT_DSPY_TEMPERATURE",
    "DEFAULT_EVALUATION_DIR",
    "DEFAULT_EXAMPLES_PATH",
    "DEFAULT_GEPA_HISTORY_LIMIT",
    "DEFAULT_GEPA_HISTORY_MIN_QUALITY",
    "DEFAULT_GEPA_LOG_DIR",
    "DEFAULT_GEPA_MAX_FULL_EVALS",
    "DEFAULT_GEPA_MAX_METRIC_CALLS",
    "DEFAULT_GEPA_PERFECT_SCORE",
    "DEFAULT_GEPA_SEED",
    "DEFAULT_GEPA_VAL_SPLIT",
    "DEFAULT_HISTORY_FORMAT",
    "DEFAULT_HISTORY_PATH",
    "DEFAULT_JUDGE_TEMPERATURE",
    "DEFAULT_JUDGE_THRESHOLD",
    "DEFAULT_LOGS_DIR",
    "DEFAULT_LOG_PATH",
    "DEFAULT_MAX_BOOTSTRAPPED_DEMOS",
    "DEFAULT_MAX_HISTORY_ENTRIES",
    "DEFAULT_MAX_REFINEMENT_ROUNDS",
    "DEFAULT_MAX_RESETS",
    "DEFAULT_MAX_ROUNDS",
    "DEFAULT_MAX_STALLS",
    "DEFAULT_PARALLEL_THRESHOLD",
    "DEFAULT_QUALITY_THRESHOLD",
    "DEFAULT_REASONING_EFFORT",
    "DEFAULT_REFINEMENT_THRESHOLD",
    "DEFAULT_REFRESH_RATE",
    "DEFAULT_RESEARCHER_TEMPERATURE",
    "DEFAULT_RETRY_ATTEMPTS",
    "DEFAULT_RETRY_BACKOFF_SECONDS",
    "DEFAULT_REVIEWER_TEMPERATURE",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_VAR_DIR",
    "DEFAULT_WORKFLOW_TIMEOUT",
    "DEFAULT_WRITER_TEMPERATURE",
    "EXECUTION_MODE_DELEGATED",
    "EXECUTION_MODE_PARALLEL",
    "EXECUTION_MODE_SEQUENTIAL",
    "MAX_ERROR_MESSAGE_LENGTH",
    "MAX_RETRY_ATTEMPTS",
    "MAX_TASK_LENGTH",
    "MAX_TASK_PREVIEW_LENGTH",
    "MIN_CACHE_SIZE_BYTES",
    "MIN_TASK_LENGTH",
    "PERFECT_SCORE",
    "PHASE_ANALYSIS",
    "PHASE_EXECUTION",
    "PHASE_JUDGE",
    "PHASE_PROGRESS",
    "PHASE_QUALITY",
    "PHASE_REFINEMENT",
    "PHASE_ROUTING",
    "REASONING_EFFORT_MAXIMAL",
    "REASONING_EFFORT_MEDIUM",
    "REASONING_EFFORT_MINIMAL",
    "SERIALIZER_DILL",
    "SERIALIZER_NONE",
    "SERIALIZER_PICKLE",
    "STATUS_FAILED",
    "STATUS_IN_PROGRESS",
    "STATUS_PENDING",
    "STATUS_SUCCESS",
    "STATUS_TIMEOUT",
    "TOOL_BROWSER",
    "TOOL_HOSTED_CODE_INTERPRETER",
    "TOOL_TAVILY_MCP",
    "TOOL_TAVILY_SEARCH",
]
