"""Tool description management with two-tier system (short + detailed)."""

import logging
from typing import Optional

logger = logging.getLogger(__name__)


class ToolDescriptionManager:
    """Manages tool descriptions with short and detailed versions."""

    # Short descriptions (50-150 tokens) - shown to agents by default
    SHORT_DESCRIPTIONS = {
        "wistx_get_compliance_requirements": (
            "Get compliance requirements and controls for infrastructure resources. "
            "Supports PCI-DSS, HIPAA, CIS, SOC2, NIST, ISO-27001, GDPR, FedRAMP. "
            "Returns controls, remediation guidance, and verification procedures."
        ),
        "wistx_research_knowledge_base": (
            "Research DevOps, infrastructure, compliance, FinOps, and platform engineering knowledge. "
            "Searches best practices, patterns, strategies, and guides. "
            "Returns structured knowledge with examples and recommendations. "
            "⚠️ NOT for integration pattern recommendations - use wistx_manage_infrastructure_lifecycle instead."
        ),
        "wistx_calculate_infrastructure_cost": (
            "Calculate infrastructure costs for AWS, GCP, and Azure resources. "
            "Estimates compute, storage, networking, and database costs. "
            "Returns cost breakdown and optimization recommendations."
        ),
        "wistx_get_devops_infra_code_examples": (
            "Get DevOps and infrastructure code examples from curated repositories. "
            "Supports Terraform, CloudFormation, Helm, Ansible, Docker, Kubernetes. "
            "Returns production-ready code with explanations. "
            "⚠️ NOT for integration pattern recommendations - use wistx_manage_infrastructure_lifecycle instead."
        ),
        "wistx_web_search": (
            "Search the web for DevOps, infrastructure, and cloud-related information. "
            "Returns recent articles, documentation, and best practices. "
            "Useful for current information and latest tools."
        ),
        "wistx_search_codebase": (
            "Search indexed code repositories for DevOps and infrastructure code. "
            "Searches Terraform, CloudFormation, Helm, Ansible, Docker, Kubernetes. "
            "Returns code snippets with file paths and line numbers."
        ),
        "wistx_regex_search": (
            "Search code repositories using regex patterns. "
            "Supports complex pattern matching across multiple files. "
            "Returns matching code sections with context."
        ),
        "wistx_design_architecture": (
            "Design and initialize DevOps/infrastructure/SRE/platform engineering projects. "
            "Creates architecture diagrams, infrastructure code, and deployment guides. "
            "Returns complete project structure and implementation plan."
        ),
        "wistx_troubleshoot_issue": (
            "Troubleshoot infrastructure and DevOps issues. "
            "Analyzes error messages and logs to identify root causes. "
            "Returns diagnosis, solutions, and prevention strategies."
        ),
        "wistx_generate_documentation": (
            "Generate comprehensive documentation and reports. "
            "Creates architecture docs, runbooks, compliance reports, and guides. "
            "Returns formatted documentation ready for use."
        ),
        "wistx_manage_infrastructure_lifecycle": (
            "🎯 PRIMARY TOOL for integration pattern recommendations. "
            "Use when asked to connect, link, integrate, or set up connections between infrastructure components "
            "(e.g., 'connect EC2 to RDS', 'link Lambda with API Gateway', 'integrate web servers with database'). "
            "Recommends quality-scored integration patterns with security rules, monitoring config, and implementation guidance. "
            "Also supports infrastructure design, analysis, and lifecycle operations. "
            "NOTE: Does NOT generate code - provides analysis, recommendations, patterns, and guidance."
        ),
        "wistx_search_devops_resources": (
            "Unified search across all DevOps and infrastructure resources: packages, CLI tools, services, and documentation. "
            "Searches packages (PyPI, npm, Terraform Registry, Helm, etc.), CLI tools (terraform, kubectl, helm, etc.), "
            "services (GitHub Actions, GitLab CI, CircleCI, etc.), and documentation (guides, best practices). "
            "Returns comprehensive results across all resource types with unified ranking. "
            "DO NOT use 'cloud_provider' or 'code_types' parameters - include cloud provider in query instead."
        ),
        "wistx_index_repository": (
            "Index a code repository for searching and analysis (NON-BLOCKING, asynchronous). "
            "Supports Git repositories with Terraform, CloudFormation, Helm, Ansible code. "
            "Returns immediately - indexing runs in background. DO NOT wait for completion."
        ),
        "wistx_get_existing_infrastructure": (
            "Get existing infrastructure configuration and state. "
            "Retrieves current AWS, GCP, Azure resource configurations. "
            "Returns infrastructure details and relationships."
        ),
        "wistx_get_recommended_tools": (
            "Get recommended tools for a specific task. "
            "Returns tool recommendations with relevance scores, categories, and usage guidance. "
            "Use this tool when you need help discovering which tools to use."
        ),
        "wistx_list_tools_by_category": (
            "List all tools in a specific category. "
            "Use this tool to discover available tools organized by category. "
            "Categories: compliance, pricing, code, infrastructure, knowledge, indexing, documentation, packages, integration."
        ),
        "wistx_get_tool_documentation": (
            "Get detailed documentation for a specific tool. "
            "Returns comprehensive information about what a tool does, when to use it, when NOT to use it, and how to use it correctly."
        ),
        "wistx_index_resource": (
            "Index content (documentation website or document file) for user-specific search. "
            "Supports website crawling and single file indexing (PDF, DOCX, Markdown). "
            "Returns indexing status and search readiness."
        ),
        "wistx_list_resources": (
            "⚠️ DEPRECATED: Use `wistx_manage_resources` with action='list' instead. "
            "This tool is no longer registered. Use the unified tool for all resource management."
        ),
        "wistx_check_resource_status": (
            "⚠️ DEPRECATED: Use `wistx_manage_resources` with action='status' instead. "
            "This tool is no longer registered. Use the unified tool for all resource management."
        ),
        "wistx_delete_resource": (
            "⚠️ DEPRECATED: Use `wistx_manage_resources` with action='delete' instead. "
            "This tool is no longer registered. Use the unified tool for all resource management."
        ),
        "wistx_manage_resources": (
            "Unified resource management: list indexed resources, check indexing status, delete resources. "
            "Use action='list' to see all resources, action='status' to check indexing progress at intervals or when user asks, "
            "action='delete' to remove resources. Indexing runs asynchronously in background."
        ),
        "wistx_read_package_file": (
            "Read specific file sections from package source code using SHA256 hash. "
            "Use this tool to get complete context around code snippets found in `wistx_search_devops_resources` results. "
            "The filename_sha256 is provided in package search results under 'source_files'. "
            "No indexing required - fetches packages on-demand from registries."
        ),
    }

    # Detailed descriptions (original long versions) - available on-demand
    DETAILED_DESCRIPTIONS = {
        "wistx_get_compliance_requirements": (
            "Get compliance requirements for infrastructure resources.\n\n"
            "**Keywords:** compliance, PCI-DSS, HIPAA, CIS, SOC2, NIST, ISO 27001, security standards, controls, remediation\n\n"
            "**When to Use:**\n"
            "- Use when asked about compliance standards (PCI-DSS, HIPAA, CIS, SOC2, NIST-800-53, ISO-27001, GDPR, FedRAMP) for infrastructure\n"
            "- Use for AWS/GCP/Azure resources (RDS, S3, EC2, Lambda, EKS, VPC, IAM, etc.)\n"
            "- Use when need specific compliance controls, remediation guidance, or verification procedures\n"
            "- Use when building infrastructure that must meet compliance requirements\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for general compliance questions (use general knowledge)\n"
            "- Do NOT use for non-infrastructure resources (applications, databases without infrastructure context)\n"
            "- Do NOT use for compliance standards not related to infrastructure\n\n"
            "**Returns:**\n"
            "- Compliance controls with severity levels (CRITICAL, HIGH, MEDIUM, LOW)\n"
            "- Remediation guidance and code snippets\n"
            "- Verification procedures and checklists\n"
            "- Compliance report (if generate_report=true)\n\n"
            "**Common Workflows:**\n"
            "1. Design infrastructure → Get compliance requirements → Apply controls → Verify compliance\n"
            "2. Audit infrastructure → Get compliance requirements → Check violations → Remediate issues\n"
            "3. Build new resources → Get compliance requirements → Implement compliant configuration\n\n"
            "**Related Tools:**\n"
            "- `wistx_calculate_infrastructure_cost`: Use after compliance to estimate costs\n"
            "- `wistx_get_devops_infra_code_examples`: Use to find compliant code examples\n"
            "- `wistx_research_knowledge_base`: Use for compliance best practices"
        ),
        "wistx_research_knowledge_base": (
            "Deep research tool for DevOps, infrastructure, compliance, FinOps, and platform engineering knowledge.\n\n"
            "**Keywords:** research, knowledge base, best practices, patterns, strategies, guides, DevOps, infrastructure, compliance, FinOps, platform engineering\n\n"
            "**When to Use:**\n"
            "- Use for comprehensive research queries about best practices, patterns, strategies, and guides\n"
            "- Use when you need cross-domain insights and relationships\n"
            "- Use for deep research that requires both internal knowledge and real-time web search\n"
            "- Use when you need structured knowledge with examples and recommendations\n\n"
            "**When NOT to Use:**\n"
            "- ⚠️ Do NOT use for integration pattern recommendations (use `wistx_manage_infrastructure_lifecycle` with action='integrate')\n"
            "- Do NOT use for simple factual questions (use general knowledge)\n"
            "- Do NOT use for specific compliance requirements (use `wistx_get_compliance_requirements`)\n"
            "- Do NOT use for code examples (use `wistx_get_devops_infra_code_examples`)\n\n"
            "**Returns:**\n"
            "- Structured knowledge with examples and recommendations\n"
            "- Cross-domain relationships and impacts\n"
            "- Best practices and patterns\n"
            "- Real-time web search results (if include_web_search=true)\n\n"
            "**Common Workflows:**\n"
            "1. Research topic → Get comprehensive knowledge → Apply patterns → Implement solution\n"
            "2. Learn best practices → Research strategies → Find examples → Apply to project\n\n"
            "**Related Tools:**\n"
            "- `wistx_web_search`: Use for simple web searches\n"
            "- `wistx_get_compliance_requirements`: Use for specific compliance queries"
        ),
        "wistx_calculate_infrastructure_cost": (
            "Calculate infrastructure costs for cloud resources.\n\n"
            "**Keywords:** cost, pricing, cost optimization, AWS, GCP, Azure, infrastructure cost, monthly cost, annual cost\n\n"
            "**When to Use:**\n"
            "- Use when asked about pricing, costs, or cost optimization for AWS/GCP/Azure resources\n"
            "- Use to estimate monthly/annual costs for infrastructure\n"
            "- Use to get cost breakdown and optimization suggestions\n"
            "- Use when comparing costs across cloud providers\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for application-level costs (use general knowledge)\n"
            "- Do NOT use for non-cloud infrastructure costs\n\n"
            "**Returns:**\n"
            "- Monthly/annual costs\n"
            "- Cost breakdown by service/resource\n"
            "- Optimization suggestions\n"
            "- Cost comparison across providers\n\n"
            "**Common Workflows:**\n"
            "1. Design infrastructure → Calculate costs → Optimize → Recalculate\n"
            "2. Compare providers → Calculate costs → Choose provider → Implement\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_compliance_requirements`: Use to ensure compliance before cost calculation\n"
            "- `wistx_get_devops_infra_code_examples`: Use to find cost-optimized code examples"
        ),
        "wistx_get_devops_infra_code_examples": (
            "Search infrastructure code examples from curated repositories.\n\n"
            "**Keywords:** code examples, reference implementations, sample code, Terraform, Kubernetes, Docker, CloudFormation, Helm, Ansible\n\n"
            "**When to Use:**\n"
            "- Use when asked for code examples, reference implementations, or sample code for infrastructure resources\n"
            "- Use to find production-ready code for specific services or patterns\n"
            "- Use when you need compliant code examples\n"
            "- Use to find code examples with cost estimates\n"
            "- Use AFTER getting integration pattern recommendations from `wistx_manage_infrastructure_lifecycle` to find code examples\n\n"
            "**When NOT to Use:**\n"
            "- ⚠️ Do NOT use for integration pattern recommendations (use `wistx_manage_infrastructure_lifecycle` with action='integrate')\n"
            "- Do NOT use for searching user's own codebase (use `wistx_search_codebase`)\n"
            "- Do NOT use for general code questions (use general knowledge)\n\n"
            "**Parameters:**\n"
            "- `cloud_provider`: Use 'aws', 'gcp', 'azure', 'oracle', or 'alibaba' for specific provider. "
            "Use 'multi-cloud' or omit this parameter to search across all providers.\n"
            "- `code_types`: Filter by code types (terraform, kubernetes, docker, etc.)\n"
            "- `services`: Filter by cloud services (rds, s3, ec2, etc.)\n"
            "- `compliance_standard`: Filter by compliance standard (PCI-DSS, HIPAA, etc.)\n\n"
            "**Returns:**\n"
            "- Production-ready code examples with metadata\n"
            "- Compliance analysis\n"
            "- Cost estimates\n"
            "- Code explanations and best practices\n\n"
            "**Common Workflows:**\n"
            "1. Need code example → Search examples → Review code → Adapt to project\n"
            "2. Find compliant code → Search with compliance filter → Use example → Verify compliance\n"
            "3. Multi-cloud search → Use 'multi-cloud' or omit cloud_provider → Get examples from all providers\n\n"
            "**Related Tools:**\n"
            "- `wistx_search_codebase`: Use to search your own indexed codebase\n"
            "- `wistx_get_compliance_requirements`: Use to verify compliance of examples"
        ),
        "wistx_web_search": (
            "Web search for security information and general web content.\n\n"
            "**Keywords:** web search, security search, CVEs, advisories, security vulnerabilities, latest information\n\n"
            "**When to Use:**\n"
            "- Use for security searches (CVEs, advisories, security vulnerabilities)\n"
            "- Use for general web search via Tavily\n"
            "- Use when you need current information and latest tools\n"
            "- Use for recent articles, documentation, and best practices\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for compliance requirements (use `wistx_get_compliance_requirements`)\n"
            "- Do NOT use for deep research (use `wistx_research_knowledge_base`)\n"
            "- Do NOT use for searching your own codebase (use `wistx_search_codebase`)\n\n"
            "**Returns:**\n"
            "- Recent articles and documentation\n"
            "- CVE database results (if include_cves=true)\n"
            "- Security advisories (if include_advisories=true)\n"
            "- Web search results from Tavily\n\n"
            "**Common Workflows:**\n"
            "1. Need current info → Web search → Review results → Apply knowledge\n"
            "2. Check security → Search CVEs → Review advisories → Take action\n\n"
            "**Related Tools:**\n"
            "- `wistx_research_knowledge_base`: Use for deep research with web search\n"
            "- `wistx_get_compliance_requirements`: Use for compliance-specific queries"
        ),
        "wistx_search_codebase": (
            "Search user's indexed codebase including repositories, documentation, and documents.\n\n"
            "**Keywords:** codebase search, repository search, indexed code, user code, code snippets\n\n"
            "**When to Use:**\n"
            "- Use when asked to search through user's own code, documentation, or indexed resources\n"
            "- Use to find code patterns in your repositories\n"
            "- Use to search indexed documentation and documents\n"
            "- Use when you need code snippets with file paths and line numbers\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for searching curated code examples (use `wistx_get_devops_infra_code_examples`)\n"
            "- Do NOT use for regex pattern matching (use `wistx_regex_search`)\n"
            "- Do NOT use for general code questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Code snippets with file paths and line numbers\n"
            "- AI-analyzed results with explanations\n"
            "- Pattern detection and recommendations\n"
            "- Code snippets analysis\n\n"
            "**Common Workflows:**\n"
            "1. Need to find code → Search codebase → Review results → Use code\n"
            "2. Understand patterns → Search codebase → Analyze patterns → Apply insights\n\n"
            "**Related Tools:**\n"
            "- `wistx_regex_search`: Use for exact pattern matching\n"
            "- `wistx_get_devops_infra_code_examples`: Use for curated code examples"
        ),
        "wistx_regex_search": (
            "Search user's indexed codebase using regex patterns.\n\n"
            "**Keywords:** regex search, pattern matching, security audit, compliance check, code analysis\n\n"
            "**When to Use:**\n"
            "- Use for exact pattern matching across codebase\n"
            "- Use for security audits (finding secrets, API keys, credentials)\n"
            "- Use for compliance checks (finding violations)\n"
            "- Use for code analysis with complex patterns\n"
            "- Use with pre-built templates (api_key, password, ip_address, etc.)\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for natural language queries (use `wistx_search_codebase`)\n"
            "- Do NOT use for simple text search (use `wistx_search_codebase`)\n\n"
            "**Returns:**\n"
            "- Matching code sections with context\n"
            "- File paths and line numbers\n"
            "- Surrounding code context (if include_context=true)\n\n"
            "**Common Workflows:**\n"
            "1. Security audit → Regex search for secrets → Review findings → Remediate\n"
            "2. Compliance check → Regex search for violations → Fix issues → Verify\n\n"
            "**Related Tools:**\n"
            "- `wistx_search_codebase`: Use for natural language code search\n"
            "- `wistx_get_compliance_requirements`: Use to understand compliance requirements"
        ),
        "wistx_design_architecture": (
            "Design and initialize DevOps/infrastructure/SRE/platform engineering projects.\n\n"
            "**Keywords:** architecture design, project initialization, scaffold, architecture review, architecture optimization\n\n"
            "**When to Use:**\n"
            "- Use to scaffold new projects with compliance and security built-in\n"
            "- Use to design architectures for new systems\n"
            "- Use to review existing architectures\n"
            "- Use to optimize architectures\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for simple code generation (use general knowledge)\n"
            "- Do NOT use for troubleshooting (use `wistx_troubleshoot_issue`)\n\n"
            "**Returns:**\n"
            "- Complete project structure\n"
            "- Architecture diagrams\n"
            "- Infrastructure code\n"
            "- Deployment guides\n"
            "- Implementation plan\n\n"
            "**Common Workflows:**\n"
            "1. New project → Initialize project → Design architecture → Implement\n"
            "2. Review architecture → Analyze → Optimize → Update\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_compliance_requirements`: Use to ensure compliance in architecture\n"
            "- `wistx_calculate_infrastructure_cost`: Use to estimate costs for architecture"
        ),
        "wistx_troubleshoot_issue": (
            "Diagnose and fix infrastructure/code issues.\n\n"
            "**Keywords:** troubleshooting, error diagnosis, issue resolution, error analysis, fix recommendations\n\n"
            "**When to Use:**\n"
            "- Use when encountering errors or issues with infrastructure/code\n"
            "- Use to analyze error messages and logs\n"
            "- Use to identify root causes\n"
            "- Use to get fix recommendations and prevention strategies\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for architecture design (use `wistx_design_architecture`)\n"
            "- Do NOT use for general questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Diagnosis of the issue\n"
            "- Root cause analysis\n"
            "- Fix recommendations\n"
            "- Prevention strategies\n\n"
            "**Common Workflows:**\n"
            "1. Encounter error → Troubleshoot → Get diagnosis → Apply fix\n"
            "2. Analyze logs → Troubleshoot → Identify root cause → Prevent recurrence\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_compliance_requirements`: Use to check if issue is compliance-related\n"
            "- `wistx_research_knowledge_base`: Use to research similar issues"
        ),
        "wistx_generate_documentation": (
            "Generate comprehensive documentation and reports.\n\n"
            "**Keywords:** documentation generation, reports, architecture docs, runbooks, compliance reports, security reports, cost reports\n\n"
            "**When to Use:**\n"
            "- Use when asked to create documentation or reports\n"
            "- Use to generate architecture docs, runbooks, compliance reports, security reports, cost reports\n"
            "- Use to create API documentation and deployment guides\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for simple text generation (use general knowledge)\n"
            "- Do NOT use for code generation (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Formatted documentation ready for use\n"
            "- Reports in requested format (markdown, PDF, HTML, JSON)\n"
            "- Comprehensive documentation with all requested sections\n\n"
            "**Common Workflows:**\n"
            "1. Need documentation → Generate docs → Review → Publish\n"
            "2. Create report → Generate report → Review → Share\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_compliance_requirements`: Use to include compliance information in reports\n"
            "- `wistx_calculate_infrastructure_cost`: Use to include cost information in reports"
        ),
        "wistx_manage_infrastructure_lifecycle": (
            "🎯 PRIMARY TOOL for integration pattern recommendations and infrastructure lifecycle management.\n\n"
            "**IMPORTANT:** This tool does NOT generate code. It provides analysis, recommendations, patterns, "
            "and guidance. Use an LLM to generate code based on these recommendations.\n\n"
            "**Keywords:** connect, link, integrate, integration patterns, component integration, EC2 RDS, Lambda API Gateway, "
            "networking patterns, security patterns, set up connection, infrastructure management, lifecycle, design, Kubernetes, multi-cloud\n\n"
            "**Natural Language Patterns:**\n"
            "- \"I need to connect X to Y\" → Use action='integrate'\n"
            "- \"How should I link X with Y?\" → Use action='integrate'\n"
            "- \"What's the best way to integrate X and Y?\" → Use action='integrate'\n"
            "- \"Set up connection between X and Y\" → Use action='integrate'\n"
            "- \"How do I connect my EC2 to RDS?\" → Use action='integrate'\n\n"
            "**Action Categories:**\n"
            "1. **Integration Management (PRIMARY USE):** integrate, analyze_integration\n"
            "   - Use action='integrate' to recommend integration patterns for connecting components\n"
            "   - Example: \"How should I connect EC2 to RDS?\" → Use action='integrate'\n"
            "2. **Design & Analysis:** analyze, design, validate\n"
            "3. **Lifecycle Operations:** create, update, upgrade, backup, restore, monitor, optimize\n\n"
            "**When to Use:**\n"
            "- 🎯 Use action='integrate' when asked to connect, link, or integrate components (e.g., \"connect EC2 to RDS\", \"link Lambda with API Gateway\")\n"
            "- 🎯 Use action='integrate' when asked about integration patterns or how components should communicate\n"
            "- 🎯 Use action='integrate' when asked to recommend patterns for connecting components\n"
            "- 🎯 Use action='integrate' when asked \"How should I connect X to Y?\" or \"What's the best way to link X with Y?\"\n"
            "- Use action='analyze' to analyze existing infrastructure code for issues\n"
            "- Use action='design' to design new infrastructure with integration recommendations\n"
            "- Use action='analyze_integration' to analyze integration patterns in existing code\n"
            "- Use for Kubernetes cluster and multi-cloud lifecycle management\n"
            "- Use action='validate' to validate infrastructure designs and integrations\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for application deployment (use general knowledge)\n"
            "- Do NOT use for simple resource creation without lifecycle management\n"
            "- Do NOT expect code generation - tool provides recommendations only\n\n"
            "**Returns:**\n"
            "- Design & Analysis: missing_connections, dependency_issues, security_gaps, recommendations, visualization\n"
            "- Integration: recommended_patterns, dependencies, security_rules, monitoring config, implementation_guidance\n"
            "- Lifecycle: resource_id, status, endpoints, compliance_status, cost_summary, recommendations\n\n"
            "**Common Workflows:**\n"
            "1. Design → Analyze existing code → Design new infrastructure → Validate → Create\n"
            "2. Integrate → Recommend patterns → Analyze integration → Validate → Implement\n"
            "3. Lifecycle → Create → Monitor → Optimize → Backup → Upgrade\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_existing_infrastructure`: Use to get current infrastructure state before design\n"
            "- `wistx_calculate_infrastructure_cost`: Use to estimate costs for infrastructure changes\n"
            "- `wistx_get_devops_infra_code_examples`: Use to find code examples after getting recommendations\n"
            "- `wistx_research_knowledge_base`: Use to research best practices and patterns"
        ),
        "wistx_search_devops_resources": (
            "⚠️ **CRITICAL WARNING**: DO NOT use 'cloud_provider' or 'code_types' parameters - they are NOT supported and will cause errors. "
            "Include cloud provider directly in the query string instead (e.g., 'terraform gcp GKE cluster' or 'terraform aws rds').\n\n"
            "Unified search across all DevOps and infrastructure resources: packages, CLI tools, services, and documentation.\n\n"
            "**Keywords:** devops resources, packages, CLI tools, services, documentation, terraform, kubectl, helm, github actions, gitlab ci\n\n"
            "**Available Parameters:**\n"
            "- `query` (string, required): Search query - MUST include cloud provider in query if needed (e.g., 'terraform gcp GKE cluster' or 'terraform aws rds')\n"
            "- `resource_types` (array, optional): Filter by types - [\"package\", \"tool\", \"service\", \"documentation\", \"template\", \"all\"] (default: [\"all\"])\n"
            "- `registry` (string, optional): Filter by registry for packages (pypi, npm, terraform, crates_io, golang, helm, ansible, maven, nuget, rubygems)\n"
            "- `domain` (string, optional): Filter by domain (devops, infrastructure, compliance, finops, platform, sre)\n"
            "- `category` (string, optional): Filter by category (infrastructure-as-code, cloud-providers, kubernetes, etc.)\n"
            "- `search_type` (string, optional): For packages only - \"semantic\", \"regex\", or \"hybrid\" (default: \"semantic\")\n"
            "- `pattern` (string, optional): Regex pattern for package regex search\n"
            "- `template` (string, optional): Pre-built template for package regex search\n"
            "- `package_name` (string, optional): Search specific package by name\n"
            "- `limit` (integer, optional): Maximum results per resource type (1-100, default: 20)\n\n"
            "**Invalid Parameters (DO NOT USE):**\n"
            "- `cloud_provider` - NOT supported. Include cloud provider in `query` instead (e.g., 'terraform aws rds' or 'gcp gke')\n"
            "- `code_types` - NOT supported. Use `category` parameter or include in `query` instead\n\n"
            "**When to Use:**\n"
            "- Use to discover all types of DevOps resources in one search\n"
            "- Use to find packages, CLI tools, services, or documentation\n"
            "- Use for comprehensive DevOps resource discovery\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for searching code examples (use `wistx_get_devops_infra_code_examples`)\n"
            "- Do NOT use for general questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Packages: List of packages from registries\n"
            "- Tools: List of CLI tools with install commands\n"
            "- Services: List of services/integrations with URLs\n"
            "- Documentation: List of guides and best practices\n"
            "- Unified results: Cross-type ranked results\n\n"
            "**Common Workflows:**\n"
            "1. Need DevOps resource → Search all types → Review unified results → Use resource\n"
            "2. Find tool → Search with resource_types=[\"tool\"] → Get install command → Install\n"
            "3. Find package → Search with resource_types=[\"package\"] → Review → Use package\n\n"
            "**Related Tools:**\n"
            "- `wistx_search_packages_read_file`: Use to read package source code\n"
            "- `wistx_get_devops_infra_code_examples`: Use to find code examples"
        ),
        "wistx_index_repository": (
            "Index a GitHub repository for code search and analysis.\n\n"
            "**⚠️ CRITICAL: This tool is NON-BLOCKING and ASYNCHRONOUS**\n"
            "- Indexing starts immediately and runs in the background\n"
            "- The tool returns immediately with resource_id and status='pending'\n"
            "- **DO NOT wait for indexing to complete before proceeding with the user's task**\n"
            "- **DO NOT repeatedly check status** - proceed with available tools/knowledge immediately\n"
            "- Indexing can take minutes/hours depending on repository size\n"
            "- Use other tools (knowledge base, code examples, best practices) to answer the user's query NOW\n\n"
            "**Resource Type:** GitHub Repository ONLY\n"
            "- **Use for:** GitHub repositories (public or private)\n"
            "- **Use for:** Code search and analysis\n"
            "- **Use for:** Infrastructure code indexing\n\n"
            "**Do NOT Use For:**\n"
            "- Documentation websites → use `wistx_index_resource` with content_type='documentation'\n"
            "- Document files (PDF, DOCX, etc.) → use `wistx_index_resource` with content_type='pdf'/'docx'\n"
            "- Searching already indexed repositories → use `wistx_search_codebase`\n"
            "- If the user's query can be answered without indexing → use knowledge base, code examples\n\n"
            "**Parameters:**\n"
            "- repo_url: GitHub repository URL (REQUIRED) - e.g., 'https://github.com/owner/repo'\n"
            "- branch: Branch name (default: 'main')\n"
            "- include_patterns: Glob patterns for file paths (e.g., ['**/*.tf', '**/examples/**'])\n"
            "- exclude_patterns: Glob patterns to exclude (e.g., ['**/test/**', '**/node_modules/**'])\n\n"
            "**Returns:**\n"
            "- Resource ID (for future reference)\n"
            "- Status: 'pending' (indexing started, running in background)\n"
            "- Progress: 0.0 (will update asynchronously)\n\n"
            "**Common Workflows:**\n"
            "1. User asks to index repo → Index repository → **Proceed immediately with user's actual task** → Indexing completes in background\n"
            "2. User needs repo searchable → Index repository → Use other tools to answer query → Repository becomes searchable later\n\n"
            "**Related Tools:**\n"
            "- `wistx_search_codebase`: Use to search indexed repositories (only after indexing completes)\n"
            "- `wistx_index_resource`: Use for documentation websites or document files (NOT repositories)\n"
            "- `wistx_research_knowledge_base`: Use to answer queries immediately without waiting for indexing\n"
            "- `wistx_get_devops_infra_code_examples`: Use to find code examples immediately\n"
            "- `wistx_manage_resources`: Use with action='status' to check indexing progress at intervals or when user asks"
        ),
        "wistx_get_existing_infrastructure": (
            "Get existing infrastructure context for a repository.\n\n"
            "**Keywords:** existing infrastructure, infrastructure context, infrastructure state, repository infrastructure\n\n"
            "**When to Use:**\n"
            "- Use when coding agents need to understand existing infrastructure before creating new resources\n"
            "- Use to get cost analysis, compliance status, and recommendations based on indexed repository data\n"
            "- Use to understand current infrastructure state\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for designing new infrastructure (use `wistx_design_architecture`)\n"
            "- Do NOT use for general infrastructure questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Infrastructure details and relationships\n"
            "- Cost analysis\n"
            "- Compliance status\n"
            "- Recommendations\n\n"
            "**Common Workflows:**\n"
            "1. Understand infrastructure → Get existing infrastructure → Review → Plan changes\n"
            "2. Audit infrastructure → Get existing infrastructure → Analyze → Report\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_compliance_requirements`: Use to check compliance of existing infrastructure\n"
            "- `wistx_calculate_infrastructure_cost`: Use to calculate costs for existing infrastructure"
        ),
        "wistx_get_recommended_tools": (
            "Get recommended tools for a specific task.\n\n"
            "**Keywords:** tool recommendations, tool discovery, tool suggestions, tool guidance\n\n"
            "**When to Use:**\n"
            "- Use when you need help discovering which tools to use for a given task\n"
            "- Use to get tool recommendations with relevance scores\n"
            "- Use to understand tool categories and usage guidance\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use if you already know which tool to use\n"
            "- Do NOT use for general questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- Tool recommendations with relevance scores (0-1)\n"
            "- Tool categories\n"
            "- Usage guidance\n"
            "- Explanations for recommendations\n\n"
            "**Common Workflows:**\n"
            "1. New task → Get recommended tools → Review recommendations → Use tools\n"
            "2. Explore tools → Get recommendations → Learn about tools → Use appropriate tool\n\n"
            "**Related Tools:**\n"
            "- `wistx_list_tools_by_category`: Use to list tools by category\n"
            "- `wistx_get_tool_documentation`: Use to get detailed information about recommended tools"
        ),
        "wistx_list_tools_by_category": (
            "List all tools in a specific category.\n\n"
            "**Keywords:** tool list, tool categories, tool discovery, category filter\n\n"
            "**When to Use:**\n"
            "- Use to discover available tools organized by category\n"
            "- Use when you know the category but want to see all tools in that category\n"
            "- Use to explore tools by domain (compliance, pricing, code, infrastructure, etc.)\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use if you need tool recommendations (use `wistx_get_recommended_tools`)\n"
            "- Do NOT use for general questions (use general knowledge)\n\n"
            "**Returns:**\n"
            "- List of tools in the specified category\n"
            "- Short descriptions for each tool (if include_descriptions=true)\n"
            "- Available categories list\n\n"
            "**Common Workflows:**\n"
            "1. Explore category → List tools by category → Review tools → Use appropriate tool\n"
            "2. Find tools → List by category → Get documentation → Use tool\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_recommended_tools`: Use to get tool recommendations\n"
            "- `wistx_get_tool_documentation`: Use to get detailed information about tools"
        ),
        "wistx_get_tool_documentation": (
            "Get detailed documentation for a specific tool.\n\n"
            "**Keywords:** tool documentation, tool help, tool guide, tool information\n\n"
            "**When to Use:**\n"
            "- Use when you need comprehensive information about what a tool does\n"
            "- Use to understand when to use a tool and when NOT to use it\n"
            "- Use to learn how to use a tool correctly\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for general questions (use general knowledge)\n"
            "- Do NOT use if you already understand the tool\n\n"
            "**Returns:**\n"
            "- Detailed tool description\n"
            "- When to use and when NOT to use guidance\n"
            "- Usage examples\n"
            "- Related tools information\n\n"
            "**Common Workflows:**\n"
            "1. Learn about tool → Get documentation → Understand usage → Use tool\n"
            "2. Verify tool usage → Get documentation → Confirm usage → Use tool\n\n"
            "**Related Tools:**\n"
            "- `wistx_get_recommended_tools`: Use to discover tools\n"
            "- `wistx_list_tools_by_category`: Use to list tools by category"
        ),
        "wistx_index_resource": (
            "Index content (documentation website or document file) for user-specific search.\n\n"
            "**⚠️ CRITICAL: This tool is for DOCUMENTATION and DOCUMENTS ONLY**\n"
            "- **Do NOT use for GitHub repositories** → use `wistx_index_repository` instead\n"
            "- Indexing starts immediately and runs in the background\n"
            "- The tool returns immediately with resource_id and status='pending'\n\n"
            "**Resource Types Supported:**\n"
            "1. **Documentation Websites:**\n"
            "   - Provide: content_url (website URL)\n"
            "   - Set: content_type='documentation'\n"
            "   - Example: 'https://docs.example.com'\n"
            "   - Crawls multiple pages based on include_patterns/exclude_patterns\n\n"
            "2. **Document Files:**\n"
            "   - Provide: content_url (file URL) OR file_path (local path)\n"
            "   - Set: content_type='pdf'/'docx'/'markdown'/'txt' (or auto-detect)\n"
            "   - Example: 'https://example.com/doc.pdf' or '/path/to/file.pdf'\n"
            "   - Processes single file\n\n"
            "**Do NOT Use For:**\n"
            "- GitHub repositories → use `wistx_index_repository`\n"
            "- Code repositories → use `wistx_index_repository`\n"
            "- Searching already indexed content → use `wistx_search_codebase`\n\n"
            "**Parameters:**\n"
            "- content_url: Website URL or document URL (REQUIRED if file_path not provided)\n"
            "- file_path: Local file path (REQUIRED if content_url not provided)\n"
            "- content_type: 'documentation' for websites, file type for documents (auto-detected if not provided)\n"
            "- include_patterns: URL patterns to include (for documentation websites only)\n"
            "- exclude_patterns: URL patterns to exclude (for documentation websites only)\n\n"
            "**Returns:**\n"
            "- Resource ID (for future reference)\n"
            "- Status: 'pending' (indexing started, running in background)\n"
            "- Progress: 0.0 (will update asynchronously)\n\n"
            "**Common Workflows:**\n"
            "1. Index documentation site → Index resource (content_type='documentation') → Wait → Search codebase\n"
            "2. Index PDF document → Index resource (content_type='pdf') → Wait → Search codebase\n\n"
            "**Related Tools:**\n"
            "- `wistx_index_repository`: Use for GitHub repositories (NOT documentation)\n"
            "- `wistx_search_codebase`: Use to search indexed resources\n"
            "- `wistx_manage_resources`: Use with action='status' to check indexing progress"
        ),
        "wistx_list_resources": (
            "⚠️ **DEPRECATED** - This tool is no longer registered.\n\n"
            "**Use `wistx_manage_resources` with `action='list'` instead.**\n\n"
            "Example: `wistx_manage_resources(action='list', resource_type='repository')`\n\n"
            "The unified `wistx_manage_resources` tool provides list, status, and delete functionality."
        ),
        "wistx_check_resource_status": (
            "⚠️ **DEPRECATED** - This tool is no longer registered.\n\n"
            "**Use `wistx_manage_resources` with `action='status'` instead.**\n\n"
            "Example: `wistx_manage_resources(action='status', resource_id='abc123')`\n\n"
            "The unified `wistx_manage_resources` tool provides list, status, and delete functionality."
        ),
        "wistx_delete_resource": (
            "⚠️ **DEPRECATED** - This tool is no longer registered.\n\n"
            "**Use `wistx_manage_resources` with `action='delete'` instead.**\n\n"
            "Example: `wistx_manage_resources(action='delete', resource_id='abc123')`\n\n"
            "The unified `wistx_manage_resources` tool provides list, status, and delete functionality."
        ),
        "wistx_manage_resources": (
            "Unified resource management tool for listing, checking status, and deleting indexed resources.\n\n"
            "**Keywords:** list resources, resource status, delete resource, indexing status, resource management\n\n"
            "**Actions:**\n"
            "- `list`: List all indexed resources (repositories, documentation, documents)\n"
            "- `status`: Check indexing status/progress for a specific resource\n"
            "- `delete`: Remove an indexed resource and all associated knowledge articles\n\n"
            "**Status Checking Guidance:**\n"
            "- Indexing runs asynchronously in the background\n"
            "- Check status at reasonable intervals (e.g., every 30-60 seconds) after initiating indexing\n"
            "- Check status when the user explicitly asks about indexing progress\n"
            "- Once status is 'completed' or 'failed', no further checks are needed\n\n"
            "**Parameters:**\n"
            "- `action` (required): 'list', 'status', or 'delete'\n"
            "- `resource_id`: Resource ID (required for 'status' and 'delete')\n"
            "- `resource_type`: Filter by type ('repository', 'documentation', 'document')\n"
            "- `status_filter`: Filter by status ('pending', 'indexing', 'completed', 'failed') - for 'list' only\n"
            "- `identifier`: Alternative to resource_id for 'delete' (repo URL, doc URL)\n"
            "- `deduplicate`: Show only latest completed resource per repo (default: true) - for 'list' only\n"
            "- `show_duplicates`: Include duplicate information (default: false) - for 'list' only\n"
            "- `include_ai_analysis`: Include AI insights (default: true) - for 'list' only\n\n"
            "**Common Workflows:**\n"
            "1. View resources → action='list' → Review status → Use in searches\n"
            "2. Index + monitor → Index repo → action='status' at intervals → Report completion to user\n"
            "3. Check progress → action='status' with resource_id → Report to user\n"
            "4. Clean up → action='list' → Get resource_id → action='delete' with resource_id\n\n"
            "**Related Tools:**\n"
            "- `wistx_index_repository`: Index a GitHub repository\n"
            "- `wistx_index_resource`: Index documentation or documents\n"
            "- `wistx_search_codebase`: Search indexed resources"
        ),
        "wistx_read_package_file": (
            "Read specific file sections from package source code using SHA256 hash.\n\n"
            "**Keywords:** read package file, package source code, file reading, code context\n\n"
            "**Available Parameters:**\n"
            "- `registry` (string, required): Package registry (pypi, npm, terraform, crates_io, golang, helm, ansible, maven, nuget, rubygems)\n"
            "- `package_name` (string, required): Package name\n"
            "- `filename_sha256` (string, required): SHA256 hash of filename (from `wistx_search_devops_resources` results under 'source_files')\n"
            "- `start_line` (integer, required): Starting line (1-based, minimum: 1)\n"
            "- `end_line` (integer, required): Ending line (must be >= start_line, max 200 lines from start_line)\n"
            "- `version` (string, optional): Package version (defaults to latest)\n\n"
            "**When to Use:**\n"
            "- Use to get complete context around code snippets found in `wistx_search_devops_resources` results\n"
            "- Use to read specific file sections from package source code\n"
            "- Use when you need more context than search results provide\n"
            "- Use when you have filename_sha256 from package search results\n\n"
            "**When NOT to Use:**\n"
            "- Do NOT use for searching packages (use `wistx_search_devops_resources`)\n"
            "- Do NOT use for general code questions (use general knowledge)\n"
            "- Do NOT use without filename_sha256 from search results\n\n"
            "**Returns:**\n"
            "- File content with line numbers\n"
            "- Code context around requested section\n"
            "- Package and file metadata\n"
            "- Total lines in file\n\n"
            "**Common Workflows:**\n"
            "1. Find package → Use `wistx_search_devops_resources` → Get filename_sha256 from 'source_files' → Use `wistx_read_package_file` → Review code\n"
            "2. Need context → Read file → Review code → Apply pattern\n\n"
            "**Related Tools:**\n"
            "- `wistx_search_devops_resources`: Use to find packages first (provides filename_sha256 in results)\n"
            "- `wistx_get_devops_infra_code_examples`: Use for curated code examples"
        ),
    }

    @classmethod
    def get_short_description(cls, tool_name: str) -> str:
        """Get short description for a tool (50-150 tokens)."""
        return cls.SHORT_DESCRIPTIONS.get(
            tool_name,
            f"Tool: {tool_name}. Use wistx_get_tool_documentation to see detailed description."
        )

    @classmethod
    def get_detailed_description(cls, tool_name: str) -> Optional[str]:
        """Get detailed description for a tool (on-demand)."""
        return cls.DETAILED_DESCRIPTIONS.get(tool_name)

    @classmethod
    def has_short_description(cls, tool_name: str) -> bool:
        """Check if short description exists for tool."""
        return tool_name in cls.SHORT_DESCRIPTIONS

    @classmethod
    def has_detailed_description(cls, tool_name: str) -> bool:
        """Check if detailed description exists for tool."""
        return tool_name in cls.DETAILED_DESCRIPTIONS

    @classmethod
    def add_short_description(cls, tool_name: str, description: str) -> None:
        """Add or update short description for a tool."""
        cls.SHORT_DESCRIPTIONS[tool_name] = description
        logger.info("Added short description for %s", tool_name)

    @classmethod
    def add_detailed_description(cls, tool_name: str, description: str) -> None:
        """Add or update detailed description for a tool."""
        cls.DETAILED_DESCRIPTIONS[tool_name] = description
        logger.info("Added detailed description for %s", tool_name)

