from sirc.core.logic import LogicValue as LogicValue

class Node:
    def __init__(self) -> None: ...
    def set_resolved_value(self, value: LogicValue) -> None: ...
    @property
    def value(self) -> LogicValue: ...
    def add_driver(self, value: LogicValue) -> None: ...
    def clear_drivers(self) -> None: ...
    def get_drivers(self) -> tuple[LogicValue, ...]: ...
    def add_connection(self, other: Node) -> None: ...
    def remove_connection(self, other: Node) -> None: ...
    def connect(self, other: Node) -> None: ...
    def disconnect(self, other: Node) -> None: ...
    def get_connections(self) -> tuple[Node, ...]: ...
