# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from kubevirt.configuration import Configuration


class V1PodNetwork(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vm_ipv6_network_cidr': 'str',
        'vm_network_cidr': 'str'
    }

    attribute_map = {
        'vm_ipv6_network_cidr': 'vmIPv6NetworkCIDR',
        'vm_network_cidr': 'vmNetworkCIDR'
    }

    def __init__(self, vm_ipv6_network_cidr=None, vm_network_cidr=None, _configuration=None):  # noqa: E501
        """V1PodNetwork - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._vm_ipv6_network_cidr = None
        self._vm_network_cidr = None
        self.discriminator = None

        if vm_ipv6_network_cidr is not None:
            self.vm_ipv6_network_cidr = vm_ipv6_network_cidr
        if vm_network_cidr is not None:
            self.vm_network_cidr = vm_network_cidr

    @property
    def vm_ipv6_network_cidr(self):
        """Gets the vm_ipv6_network_cidr of this V1PodNetwork.  # noqa: E501

        IPv6 CIDR for the vm network. Defaults to fd10:0:2::/120 if not specified.  # noqa: E501

        :return: The vm_ipv6_network_cidr of this V1PodNetwork.  # noqa: E501
        :rtype: str
        """
        return self._vm_ipv6_network_cidr

    @vm_ipv6_network_cidr.setter
    def vm_ipv6_network_cidr(self, vm_ipv6_network_cidr):
        """Sets the vm_ipv6_network_cidr of this V1PodNetwork.

        IPv6 CIDR for the vm network. Defaults to fd10:0:2::/120 if not specified.  # noqa: E501

        :param vm_ipv6_network_cidr: The vm_ipv6_network_cidr of this V1PodNetwork.  # noqa: E501
        :type: str
        """

        self._vm_ipv6_network_cidr = vm_ipv6_network_cidr

    @property
    def vm_network_cidr(self):
        """Gets the vm_network_cidr of this V1PodNetwork.  # noqa: E501

        CIDR for vm network. Default 10.0.2.0/24 if not specified.  # noqa: E501

        :return: The vm_network_cidr of this V1PodNetwork.  # noqa: E501
        :rtype: str
        """
        return self._vm_network_cidr

    @vm_network_cidr.setter
    def vm_network_cidr(self, vm_network_cidr):
        """Sets the vm_network_cidr of this V1PodNetwork.

        CIDR for vm network. Default 10.0.2.0/24 if not specified.  # noqa: E501

        :param vm_network_cidr: The vm_network_cidr of this V1PodNetwork.  # noqa: E501
        :type: str
        """

        self._vm_network_cidr = vm_network_cidr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1PodNetwork, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1PodNetwork):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1PodNetwork):
            return True

        return self.to_dict() != other.to_dict()
