<hr style="height:0pt; visibility:hidden;" />

# radon

Computes four different code metrics:

* `radon-cc`: cyclomatic complexity (measures the number of independent paths through code).
* `radon-mi`: maintainability index (estimates ease of maintenance).
* `radon-raw`: raw metrics (counts lines, comments, blanks, etc.).
* `radon-hal`: halstead metrics (quantifies code complexity based on operators (symbols) and operands (variables)).

See the [radon documentation](https://radon.readthedocs.io/en/latest/intro.html) for more details.

```{python}
#| echo: false
# pylint: disable=missing-module-docstring
# Import required packages
import subprocess
import sys

# Add parent directory to sys.path
sys.path.insert(0, "..")

# Import the helper functions
# pylint: disable = import-error, wrong-import-position
from helpers import generate_html, print_quarto  # type: ignore # noqa: E402
```

```{python}
#| echo: false
#| output: asis
generate_html(
    pypi_url="https://pypi.org/project/radon/",
    github_url="https://github.com/rubik/radon",
    conda_url="https://anaconda.org/conda-forge/radon"
)
```

## Example Quarto `.qmd` file:

{{< downloadthis examples/complexity_example.qmd dname="complexity_example" label="Download the example" type="light" >}}

:::{.pale-grey}
```{python}
#| echo: false
print_quarto("examples/complexity_example.qmd")
```
:::

## Run radon using `lintquarto`

```{.bash}
lintquarto -l radon-cc -p complexity_example.qmd
```

:::{.pale-green}
<style>
.cell-output-stdout code {
  word-break: break-word !important;
  white-space: pre-wrap !important;
}
</style>
```{python}
#| echo: false
result = subprocess.run(
    ["lintquarto", "-l", "radon-cc", "-p", "examples/complexity_example.qmd"],
    capture_output=True, text=True, check=False
)
print(result.stdout)
```
:::

```{.bash}
lintquarto -l radon-mi -p complexity_example.qmd
```

:::{.pale-green}
<style>
.cell-output-stdout code {
  word-break: break-word !important;
  white-space: pre-wrap !important;
}
</style>
```{python}
#| echo: false
result = subprocess.run(
    ["lintquarto", "-l", "radon-mi", "-p", "examples/complexity_example.qmd"],
    capture_output=True, text=True, check=False
)
print(result.stdout)
```
:::

```{.bash}
lintquarto -l radon-raw -p complexity_example.qmd
```

:::{.pale-green}
<style>
.cell-output-stdout code {
  word-break: break-word !important;
  white-space: pre-wrap !important;
}
</style>
```{python}
#| echo: false
result = subprocess.run(
    ["lintquarto", "-l", "radon-raw", "-p", "examples/complexity_example.qmd"],
    capture_output=True, text=True, check=False
)
print(result.stdout)
```
:::

```{.bash}
lintquarto -l radon-hal -p complexity_example.qmd
```

:::{.pale-green}
<style>
.cell-output-stdout code {
  word-break: break-word !important;
  white-space: pre-wrap !important;
}
</style>
```{python}
#| echo: false
result = subprocess.run(
    ["lintquarto", "-l", "radon-hal", "-p", "examples/complexity_example.qmd"],
    capture_output=True, text=True, check=False
)
print(result.stdout)
```
:::