# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ..configuration import Configuration


class HostedTemplate(object):
    """
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'effective_permission': 'int',
        'id': 'int',
        'name': 'str',
        'organization': 'int',
        'tparams': 'list[Parameter]',
        'url': 'str'
    }

    attribute_map = {
        'effective_permission': 'effective_permission',
        'id': 'id',
        'name': 'name',
        'organization': 'organization',
        'tparams': 'tparams',
        'url': 'url'
    }

    def __init__(self, effective_permission=None, id=None, name=None, organization=None, tparams=[], url=None, local_vars_configuration=None):  # noqa: E501
        """HostedTemplate - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._effective_permission = None
        self._id = None
        self._name = None
        self._organization = None
        self._tparams = None
        self._url = None
        self.discriminator = None

        if effective_permission is not None:
            self.effective_permission = effective_permission
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if organization is not None:
            self.organization = organization
        if tparams is not None:
            self.tparams = tparams
        if url is not None:
            self.url = url

    @property
    def effective_permission(self):
        """
        Effective permission mask for this entity.

        :return: The effective_permission of this HostedTemplate. 
        :rtype: int
        """
        return self._effective_permission

    @effective_permission.setter
    def effective_permission(self, effective_permission):
        """
        Effective permission mask for this entity.

        :param effective_permission: The effective_permission of this HostedTemplate.
        :type: int
        """

        self._effective_permission = effective_permission

    @property
    def id(self):
        """
        Unique integer identifying the hosted template.

        :return: The id of this HostedTemplate. 
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Unique integer identifying the hosted template.

        :param id: The id of this HostedTemplate.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Unique name of the hosted template.

        :return: The name of this HostedTemplate. 
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Unique name of the hosted template.

        :param name: The name of this HostedTemplate.
        :type: str
        """

        self._name = name

    @property
    def organization(self):
        """
        Unique integer identifying the organization associated with the hosted template.

        :return: The organization of this HostedTemplate. 
        :rtype: int
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """
        Unique integer identifying the organization associated with the hosted template.

        :param organization: The organization of this HostedTemplate.
        :type: int
        """

        self._organization = organization

    @property
    def tparams(self):
        """
        Template parameters used for rendering hosted template, if set.

        :return: The tparams of this HostedTemplate. 
        :rtype: list[Parameter]
        """
        return self._tparams

    @tparams.setter
    def tparams(self, tparams):
        """
        Template parameters used for rendering hosted template, if set.

        :param tparams: The tparams of this HostedTemplate.
        :type: list[Parameter]
        """

        self._tparams = tparams

    @property
    def url(self):
        """
        URL where jinja2 template is hosted, must be retrievable with a GET using supplied headers.

        :return: The url of this HostedTemplate. 
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        URL where jinja2 template is hosted, must be retrievable with a GET using supplied headers.

        :param url: The url of this HostedTemplate.
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostedTemplate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HostedTemplate):
            return True

        return self.to_dict() != other.to_dict()
