from __future__ import annotations
from typing import Protocol, runtime_checkable

from zempy.zosapi.editors.protocols.i_solve_data import ISolveData

@runtime_checkable
class ISolveOpticalPathDifference(ISolveData, Protocol):
    """Protocol for ISolveOpticalPathDifference (refactored to inherit ISolveData; unique fields only)."""
    @property
    def OPD(self) -> float: ...
    @OPD.setter
    def OPD(self, value: float) -> None: ...
    @property
    def PupilZone(self) -> float: ...
    @PupilZone.setter
    def PupilZone(self, value: float) -> None: ...
    @property
    def Documentation(self) -> str: ...
    @property
    def set(self) -> str: ...
    @property
    def by(self) -> str: ...
