from ..engine.redis_engine import RedisEngine as RedisEngine

class RedisService:
    def __init__(self, engine_name: str) -> None: ...
    def set_cache(self, key: str, value: str, expire: int = 300): ...
    def get_cache(self, key: str): ...
