# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/lambda_sstore.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'services/lambda_sstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
from . import basic_types_pb2 as services_dot_basic__types__pb2
from . import hook_types_pb2 as services_dot_hook__types__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cservices/lambda_sstore.proto\x12\x1a\x63om.hedera.hapi.node.hooks\x1a\x1aservices/basic_types.proto\x1a\x19services/hook_types.proto\"\x87\x01\n\x1bLambdaSStoreTransactionBody\x12\x1e\n\x07hook_id\x18\x01 \x01(\x0b\x32\r.proto.HookId\x12H\n\x0fstorage_updates\x18\x02 \x03(\x0b\x32/.com.hedera.hapi.node.hooks.LambdaStorageUpdateB%\n!com.hedera.hapi.node.hooks.legacyP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.lambda_sstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hedera.hapi.node.hooks.legacyP\001'
  _globals['_LAMBDASSTORETRANSACTIONBODY']._serialized_start=116
  _globals['_LAMBDASSTORETRANSACTIONBODY']._serialized_end=251
# @@protoc_insertion_point(module_scope)
