from abc import ABC
from sirc.core.logic import LogicValue as LogicValue
from sirc.core.node import Node as Node

class LogicDevice(ABC):
    def __init__(self) -> None: ...
    @property
    def terminal(self) -> Node: ...
    @property
    def value(self) -> LogicValue: ...

class VDD(LogicDevice):
    def __init__(self) -> None: ...

class GND(LogicDevice):
    def __init__(self) -> None: ...

class Input(LogicDevice):
    def set_value(self, value: LogicValue) -> None: ...

class Probe(LogicDevice):
    def sample(self) -> LogicValue: ...

class Port(LogicDevice): ...
