from maze.tool.csv_reader import csv_reader
from maze.tool.doc_reader import doc_reader
from maze.tool.figure_reader import figure_reader
from maze.tool.mp3_reader import mp3_reader
from maze.tool.pdf_reader import pdf_reader
from maze.tool.search import google_search
from maze.tool.text_reader import text_reader
from maze.tool.video_reader import video_reader
from maze.tool.weather import weather
from maze.tool.xlsx_reader import xlsx_reader
