from _typeshed import Incomplete as Incomplete

class GraphPlottingError(Exception): ...

class ColumnNotFoundError(GraphPlottingError):
    column_name: Incomplete
    available_columns: Incomplete
    def __init__(self, column_name: str, available_columns: list[str] | None = None) -> None: ...

class InvalidMetadataError(GraphPlottingError): ...
class InvalidCSVFormatError(GraphPlottingError): ...
class DirectionError(GraphPlottingError): ...
class DualAxisError(GraphPlottingError): ...
class PlotConfigError(GraphPlottingError): ...
class RendererError(GraphPlottingError): ...
